### ISSUE TITLE
vast.ai ubuntu 16.04 1080Ti

### ISSUE THREAD

**Issue by europound** [3rdIteration/btcrecover#110]
recover-master$
root@C.738109:~/btcrecover-master$
root@C.738109:~/btcrecover-master$
root@C.738109:~/btcrecover-master$ python3 -m btcrecover.test.test_passwords -v GPUTests
test_bitcoincore_OpenCL_JTR (__main__.Test08KeyDecryption) ... FAIL

Stdout:
pthread-Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz  PyOpenCL Exception:  pytools.persistent_dict.WriteOncePersistentDict(pyopencl-invoker-cache-v38) encountered an invalid key file for key cf93262437ecca2353232c656e29057a7529d579caf18caf5c056e94106b4f36. Remove the directory '/root/.cache/pytools/pdict-v2-pyopencl-invoker-cache-v38-py3.6.9.final.0/cf93262437ecca2353232c656e29057a7529d579caf18caf5c056e94106b4f36' if necessary.
test_bitcoincore_OpenCL_JTR_unicode (__main__.Test08KeyDecryption) ... FAIL

Stdout:
pthread-Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz  PyOpenCL Exception:  pytools.persistent_dict.WriteOncePersistentDict(pyopencl-invoker-cache-v38) encountered an invalid key file for key cf93262437ecca2353232c656e29057a7529d579caf18caf5c056e94106b4f36. Remove the directory '/root/.cache/pytools/pdict-v2-pyopencl-invoker-cache-v38-py3.6.9.final.0/cf93262437ecca2353232c656e29057a7529d579caf18caf5c056e94106b4f36' if necessary.
test_bitcoincore_OpenCL_JTR_low_interrupt_rate (__main__.Test08KeyDecryption) ... FAIL

Stdout:
pthread-Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz  PyOpenCL Exception:  pytools.persistent_dict.WriteOncePersistentDict(pyopencl-invoker-cache-v38) encountered an invalid key file for key cf93262437ecca2353232c656e29057a7529d579caf18caf5c056e94106b4f36. Remove the directory '/root/.cache/pytools/pdict-v2-pyopencl-invoker-cache-v38-py3.6.9.final.0/cf93262437ecca2353232c656e29057a7529d579caf18caf5c056e94106b4f36' if necessary.
test_bitcoincore_OpenCL_JTR_sli (__main__.Test08KeyDecryption) ... skipped 'requires two identical OpenCL devices'

======================================================================
FAIL: test_bitcoincore_OpenCL_JTR (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/root/btcrecover-master/btcrecover/test/test_passwords.py", line 1677, in test_bitcoincore_OpenCL_JTR
    self.assertTrue(test_succeeded) #Check that at least one device successfully ran the test
AssertionError: False is not true

Stdout:
pthread-Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz  PyOpenCL Exception:  pytools.persistent_dict.WriteOncePersistentDict(pyopencl-invoker-cache-v38) encountered an invalid key file for key cf93262437ecca2353232c656e29057a7529d579caf18caf5c056e94106b4f36. Remove the directory '/root/.cache/pytools/pdict-v2-pyopencl-invoker-cache-v38-py3.6.9.final.0/cf93262437ecca2353232c656e29057a7529d579caf18caf5c056e94106b4f36' if necessary.

======================================================================
FAIL: test_bitcoincore_OpenCL_JTR_unicode (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/root/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/root/btcrecover-master/btcrecover/test/test_passwords.py", line 1702, in test_bitcoincore_OpenCL_JTR_unicode
    self.assertTrue(test_succeeded)  # Check that at least one device successfully ran the test
AssertionError: False is not true

Stdout:
pthread-Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz  PyOpenCL Exception:  pytools.persistent_dict.WriteOncePersistentDict(pyopencl-invoker-cache-v38) encountered an invalid key file for key cf93262437ecca2353232c656e29057a7529d579caf18caf5c056e94106b4f36. Remove the directory '/root/.cache/pytools/pdict-v2-pyopencl-invoker-cache-v38-py3.6.9.final.0/cf93262437ecca2353232c656e29057a7529d579caf18caf5c056e94106b4f36' if necessary.

======================================================================
FAIL: test_bitcoincore_OpenCL_JTR_low_interrupt_rate (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/root/btcrecover-master/btcrecover/test/test_passwords.py", line 1727, in test_bitcoincore_OpenCL_JTR_low_interrupt_rate
    self.assertTrue(test_succeeded)  # Check that at least one device successfully ran the test
AssertionError: False is not true

Stdout:
pthread-Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz  PyOpenCL Exception:  pytools.persistent_dict.WriteOncePersistentDict(pyopencl-invoker-cache-v38) encountered an invalid key file for key cf93262437ecca2353232c656e29057a7529d579caf18caf5c056e94106b4f36. Remove the directory '/root/.cache/pytools/pdict-v2-pyopencl-invoker-cache-v38-py3.6.9.final.0/cf93262437ecca2353232c656e29057a7529d579caf18caf5c056e94106b4f36' if necessary.

----------------------------------------------------------------------
Ran 4 tests in 0.070s

FAILED (failures=3, skipped=1)
root@C.738109:~/btcrecover-master$

**Comment by 3rdIteration** [comment]
That configuration is not supported, use the Ubuntu 18.04 images with the guide here: https://btcrecover.readthedocs.io/en/latest/Usage_Examples/2020-10-06_Multi-GPU_with_vastai/Example_Multi-GPU_with_vastai/
