### ISSUE TITLE
skipped 'requires OpenCL and a compatible device'

### ISSUE THREAD

**Issue by europound** [3rdIteration/btcrecover#111]
FAILED (failures=3, skipped=1)
root@C.738109:~/btcrecover-master$ pip3 install -r requirements.txt
Requirement already satisfied: coincurve~=13.0.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line1)) (13.0.0)
Requirement already satisfied: green~=3.2.5 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2)) (3.2.5)
Requirement already satisfied: protobuf~=3.14.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 3)) (3.14.0)
Requirement already satisfied: pycryptodome~=3.9.9 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 4)) (3.9.9)
Requirement already satisfied: ecdsa==0.16.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 5))(0.16.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.6/dist-packages (from ecdsa==0.16.0->-r requirements.txt (line 5)) (1.15.0)
Requirement already satisfied: asn1crypto in /usr/lib/python3/dist-packages (from coincurve~=13.0.0->-r requirements.txt (line 1)) (0.24.0)
Requirement already satisfied: cffi>=1.3.0 in /usr/local/lib/python3.6/dist-packages (from coincurve~=13.0.0->-r requirements.txt (line 1)) (1.14.4)
Requirement already satisfied: colorama in /usr/local/lib/python3.6/dist-packages (from green~=3.2.5->-r requirements.txt (line 2)) (0.4.4)
Requirement already satisfied: unidecode in /usr/local/lib/python3.6/dist-packages (from green~=3.2.5->-r requirements.txt(line 2)) (1.1.2)
Requirement already satisfied: coverage in /usr/local/lib/python3.6/dist-packages (from green~=3.2.5->-r requirements.txt (line 2)) (5.4)
Requirement already satisfied: lxml in /usr/local/lib/python3.6/dist-packages (from green~=3.2.5->-r requirements.txt (line 2)) (4.6.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi>=1.3.0->coincurve~=13.0.0->-r requirements.txt (line 1)) (2.20)
root@C.738109:~/btcrecover-master$ python3 -m btcrecover.test.test_passwords -v OpenCL_Tests
test_bitcoincore_OpenCL_Brute (__main__.Test08KeyDecryption) ... skipped 'requires OpenCL and a compatible device'
test_blockchain_main_OpenCL_Brute (__main__.Test08KeyDecryption) ... skipped 'requires OpenCL and a compatible device'
test_blockchain_second_OpenCL_Brute (__main__.Test07WalletDecryption) ... skipped 'requires OpenCL and a compatible device'
test_Electrum28_OpenCL_Brute (__main__.Test07WalletDecryption) ... skipped 'requires OpenCL and a compatible device'

----------------------------------------------------------------------
Ran 4 tests in 0.004s

OK (skipped=4)
root@C.738109:~/btcrecover-master$

satisfied: protobuf in /usr/local/lib/python3.6/dist-packages (3.14.0)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.6/dist-packages (from protobuf) (1.15.0)
root@C.738109:~$ pip3 install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
root@C.738109:~$ nvidia-smi
Tue Feb  2 07:58:21 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:03:00.0 Off |                  N/A |
|  0%   38C    P8    12W / 150W |      2MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
root@C.738109:~$

**Comment by 3rdIteration** [comment]
What's the issue? Looks like you haven't got a working PyOpenCL installation.

PyOpenCL isn't installed as part of the requirements. See here: https://btcrecover.readthedocs.io/en/latest/GPU_Acceleration/
