### ISSUE TITLE
BIP 38 useage example

### ISSUE THREAD

**Issue by CybertSys** [3rdIteration/btcrecover#112]
How can this be used with a BIP 38 paper wallet. I see the functionality has been added but I don't see any documentation.

**Comment by 3rdIteration** [comment]
Yea it only just got added and hasn't found its way into the docco yet. (I will likely do a video and writeup for it this weekend)

Basically it works the same as other wallet types in terms of tokenlists, password lists, etc, and you pass the BIP38 encrypted key via the command line with --bip38-enc-privkey argument. (As opposed to passing a wallet file, or extract)  So something like btcrecover.py --bip38-enc-privkey 6PnM7h9sBC9EMZxLVsKzpafvBN8zjKp8MZj6h9mfvYEQRMkKBTPTyWZHHx --tokenlist <path to tokenlist>

If you want to test it, the password for the encrypted key I posted above is btcr-test-password

You can also specify a coin if it's something other than Bitcoin. (Eg: Litecoin, Dash)

Also, depending on your system, you probaby won't get a massive boost using GPU acceleration for this type of wallet. (It might even be slower)

**Comment by 3rdIteration** [comment]
Added, now available here: https://btcrecover.readthedocs.io/en/latest/Usage_Examples/basic_password_recoveries/
