### ISSUE TITLE
how to fix relationship between stupid<=>moron, that stupid[variable] comes exactly before moron[variable]  but flexible position?

### ISSUE THREAD

**Issue by europound** [3rdIteration/btcrecover#115]
thanks helped me to recover some old wallets

another questions is how to force sequence?

lets say password is "you are a stupid moron forgot 69 password"
I know that these words could be different

stupid => dumb, retarded, slow
moron => idiot, imbecile, monkey
I can use 
+ ^1^ stupid dumb retarded  slow
+ ^2^ moron => idiot  imbecile  monkey

but this is specific order

but, there are might be before and after some tokens

how to fix relationship between stupid<=>moron, that stupid[variable] comes exactly before moron[variable]  but flexible position?

**Comment by 3rdIteration** [comment]
https://btcrecover.readthedocs.io/en/latest/tokenlist_file/#relative-anchors
