### ISSUE TITLE
Coinomi mobile wallet password recovery

### ISSUE THREAD

**Issue by tomas223** [3rdIteration/btcrecover#116]
I would like to ask about continuing https://github.com/3rdIteration/btcrecover/issues/9

I'm still having the issue.
I was able to recover wallet file from rooted phone.

Wallet is secured only by password.
Do you think you could take a look on it? Is there anything I can do to help?
Thank you

**Comment by 3rdIteration** [comment]
Honestly it's not something I have looked at and am unlikely to do so for a few months at least. (If at all, as there are plenty of other open issues)

If you want it done faster, you could basically sponsor it as an assisted recovery. (This is exactly what happened with the cadano Yoroi wallet) World likely have working code within a few weeks. It's so open source and python, so you could also have a go at implementation.

If that's something you want to pursue then email me at steve@cryptoguide.tips

**Comment by anywalletrecovery** [comment]
if your phone has root access you can recover you wallet file and if it is password protected you can bruteforce it.
i have done coinomi recovery several times

**Comment by 3rdIteration** [comment]
Added in https://github.com/3rdIteration/btcrecover/commit/354cba6d7fa26de81ac7336b19e44eb2680b39d0
