### ISSUE TITLE
Add documentation/examples around using different BIP39 languages

### ISSUE THREAD

**Issue by esimf9806** [3rdIteration/btcrecover#117]
i run the seed recover.py but it dosent rcognize the words cause the are not all in enghlish what can i do? i must pyt another language i must put ASCII -characters and if yes how is it done?

**Comment by 3rdIteration** [comment]
seedrecover supports all the languages here: https://github.com/3rdIteration/btcrecover/tree/master/btcrecover/wordlists

Are you saying your seed isn't one of them?

**Comment by esimf9806** [comment]
Yes I am saying that exactly.As I read in your instructions bip39 has 2408 words and none of them is on the examined seed,as you write on yous manuals,I am considering that the examined seed is an ASCII text format.So I tried to us the —utf8 command but it is being rejected from the coo and line unrecognised command

ILIAS iPhone

8 Φεβ 2021, 8:13 μμ, ο χρήστης «3rd Iteration <notifications@github.com>» έγραψε:

﻿

seedrecover supports BIP39 seed in all the languages here: https://github.com/3rdIteration/btcrecover/tree/master/btcrecover/wordlists

Are you saying your seed isn't one of them?

**Comment by 3rdIteration** [comment]
Is your seed in the language of any of the wordlists here: https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

Each of the supported languages has a different list of 2048 words.

**Comment by 3rdIteration** [comment]
I just had a look and there have been some additional languages added to BIP39 that were not yet in BTCRecover. 

These have now been added and the documentation for using them is here: https://btcrecover.readthedocs.io/en/latest/wordlist_notes/

**Comment by esimf9806** [comment]
No it’s not in any, as I see it I need to fork it and applie for a download

ILIAS iPhone

9 Φεβ 2021, 5:50 πμ, ο χρήστης «3rd Iteration <notifications@github.com>» έγραψε:

﻿

I just had a look and there have been some additional languages added to BIP39 that were not yet in BTCRecover.

These have now been added and the documentation for using them is here: https://btcrecover.readthedocs.io/en/latest/wordlist_notes/

**Comment by 3rdIteration** [comment]
Which wallet did you originally use to generate the seed? If it isn't using any of the lists that are part of the BIP 39 GitHub then it might not be a BIP 39 seed at all.

**Comment by esimf9806** [comment]
The wallet is supported in seedrecover.py the problem is that  i have entered my own words ,and when i run seed recover it  find sonly  a few of the that i wrote in english and it tells my that only those are regognized as english so seed ...not recovered

________________________________

**Comment by 3rdIteration** [comment]
You can't customise BIP 39 seed phrases, all the words must come from one
of the lists for it to be a valid seed. If you added additional words,
these are likely a BIP39 passphrase.

**Comment by esimf9806** [comment]
thnk you thats not a nice think to know ...now it seeems it will be hard for me to recover wallets pass:(:(

________________________________

**Comment by 3rdIteration** [comment]
So what did you use to create the wallet in the first place? Are you sure it's even a BIP39 seed?

Of the words in the backup you do have, how many of them are valid if it came from one of the language lists?
