### ISSUE TITLE
^r1^ ^r2^ ^r3^ ... massively slows down init and speed

### ISSUE THREAD

**Issue by europound** [3rdIteration/btcrecover#119]
^r1^ ^r2^ ^r3^ ... massively slow down

i use 6 ^r1^ ^r2^ ^r3^ ^r4^ ^r5^ ^r6^
in each there are two words
total ~4k combinations

CPU 4800H
Wallet difficulty: 61,887 SHA-512 iterations
Counting passwords ...
Done
2021-02-09 15:29:38 : Using OpenCL ALL | GPU GeForce GTX 1650 Ti
3240 of 3240 [####################
it takes 15 minutes to init and then a lot to brute force

if i dont use relative mark then all instant and fluent
why is that?

each has + must include sign

Starting btcrecover 1.6.0-Cryptoguide on Python 3.8.5 64-bit, 21-bit unicodes, 64-bit ints
Warning: --threads ignored for GPU based Bitcoin Core recovery

**Comment by 3rdIteration** [comment]
This is normal and a limitation with how the current seed generator works. (Just uses basic permutation functions in Python and filters things that don't match)

There is an item in one of the BIP39 seeds issues about implementing a more effecient generator, but it's a low priority.

**Comment by europound** [comment]
permutation functions in Python 
is there a inbuilt permutator in btcrecovery?
i am not a coder

**Comment by 3rdIteration** [comment]
BTCRecover uses the ones built in to Python. It's not efficient, but normally isn't the bottleneck in terms of performance.
