### ISSUE TITLE
Password search exhausted

### ISSUE THREAD

**Issue by satoshidoriannakamoto** [3rdIteration/btcrecover#12]
I have a Trezor.  I have the correct 24 seed phrase.  I have a 25 pass phrase that I somewhat remember.  I am running `python btcrecover.py --bip39 --tokenlist tokens.txt --max-token 5`

My password is in the tokens.txt file which contains only one line.  It searches and the password search is exhausted and does not find the password.

The address I am using has a "3" in front so I imagine it is a segwit address.  I am using 10 as the number of addresses to search.  I am confident my 24 seed is correct.  Can you help guide me?

**Comment by 3rdIteration** [comment]
If you are using an address with a 3 in front, you will need to use the correct derivation path for this. 

It will likely be something like m/49'/0'/0'/0 if you are trying to recover an address from the first account, m/49'/0'/1'/0 for second account, etc. (So you will need to add something like --bip32-path "m/49'/0'/0'/0"0

Have you checked out my videos on YouTube that cover this? I have one that looks at doing it with a segwit derivation path and also a few that look at passphrase recovery. (None of them are exactly your situation, but should put you on the right track)

**Comment by satoshidoriannakamoto** [comment]
Yes, I watched your video.  I was able to get one step further.  I used https://github.com/madacol/btcrecover/tree/p2wpkh-p2sh and it was able to find a test passphrase.

Now I am having a problem with memory and I will open a new ticket.
