### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hamnaz** [3rdIteration/btcrecover#121]
i3-6100:~/btcrecover$ python3 seedrecover.py --no-dupchecks --mnemonic-length 12 --language EN --dsw --wallet-type BIP39 --addr-limit 1 --addrs 17GR7xWtWrfYm6y3xoZy8cXioVqBbSYcpU --tokenlist ./docs/Usage_Examples/2020-05-02_Descrambling_a_12_word_seed/lastcombination_bip39.txt

Starting seedrecover 1.7.0-CryptoGuide, btcrecover 1.7.0-Cryptoguide on Python 3.7.3 64-bit, 21-bit unicodes, 64-bit ints
Using the 'en' wordlist.
2021-02-10 01:08:40 : Phase 1/1: up to 12 mistakes, 12 of which can be an entirely different seed word.

Interrupted after counting 0 passwords
Traceback (most recent call last):
  File "seedrecover.py", line 38, in <module>
    mnemonic_sentence, path_coin = btcrseed.main(sys.argv[1:])
  File "/home/btcrecover/btcrecover/btcrseed.py", line 2656, in main
    mnemonic_found = run_btcrecover(**phase_params)
  File "/home/btcrecover/btcrecover/btcrseed.py", line 2083, in run_btcrecover
    (mnemonic_found, not_found_msg) = btcrpass.main()
  File "/home/btcrecover/btcrecover/btcrpass.py", line 6369, in main
    passwords_count = count_and_check_eta(est_secs_per_password)
  File "/home/btcrecover/btcrecover/btcrpass.py", line 6120, in count_and_check_eta
    return password_generator_factory(est_secs_per_password = est)[1]
  File "/home/btcrecover/btcrecover/btcrpass.py", line 6156, in password_generator_factory
    for passwords_counted_last in passwords_count_iterator:
  File "/home/btcrecover/btcrecover/btcrpass.py", line 4959, in password_generator
    for password_base in base_password_generator() if callable(base_password_generator) else base_password_generator:
  File "/home/btcrecover/btcrecover/btcrpass.py", line 5089, in tokenlist_base_password_generator
    if args.keep_tokens_order:
AttributeError: 'Namespace' object has no attribute 'keep_tokens_order'

**Comment by nicoschtein** [comment]
Hi !

Can you run the tests first to see if everything is set up properly ?

`python run-all-tests.py -vv`

**Comment by hamnaz** [comment]
Ran 152 tests in 29.460s using 4 processes

OK (passes=152)


*** Full Results ***

Ran 479 tests in 146.211s using 4 processes

FAILED (errors=9, passes=469, skips=1)

**Comment by hamnaz** [comment]
after upgrade protobuf
results are

Ran 152 tests in 28.858s using 4 processes

OK (passes=152)


*** Full Results ***

Ran 479 tests in 145.383s using 4 processes

OK (passes=478, skips=1)

**Comment by nicoschtein** [comment]
Great ! Now, can you run your command again ?

**Comment by hamnaz** [comment]
yes same error

**Comment by hamnaz** [comment]
Interrupted after counting 0 passwords
Traceback (most recent call last):
  File "seedrecover.py", line 38, in <module>
    mnemonic_sentence, path_coin = btcrseed.main(sys.argv[1:])
  File "/home/chawla/btcrecover/btcrecover/btcrseed.py", line 2656, in main
    mnemonic_found = run_btcrecover(**phase_params)
  File "/home/chawla/btcrecover/btcrecover/btcrseed.py", line 2083, in run_btcrecover
    (mnemonic_found, not_found_msg) = btcrpass.main()
  File "/home/chawla/btcrecover/btcrecover/btcrpass.py", line 6369, in main
    passwords_count = count_and_check_eta(est_secs_per_password)
  File "/home/chawla/btcrecover/btcrecover/btcrpass.py", line 6120, in count_and_check_eta
    return password_generator_factory(est_secs_per_password = est)[1]
  File "/home/chawla/btcrecover/btcrecover/btcrpass.py", line 6156, in password_generator_factory
    for passwords_counted_last in passwords_count_iterator:
  File "/home/chawla/btcrecover/btcrecover/btcrpass.py", line 4959, in password_generator
    for password_base in base_password_generator() if callable(base_password_generator) else base_password_generator:
  File "/home/chawla/btcrecover/btcrecover/btcrpass.py", line 5089, in tokenlist_base_password_generator
    if args.keep_tokens_order:
AttributeError: 'Namespace' object has no attribute 'keep_tokens_order'

**Comment by hamnaz** [comment]
i try all command mention in video, but always same error
https://www.youtube.com/watch?v=ruSF8OKwBRk&feature=youtu.be

**Comment by 3rdIteration** [comment]
This bug was introduced with some of the code from the downstream BIP38 fork, has been fixed now as of https://github.com/3rdIteration/btcrecover/commit/1f21ba3f9d45f7f8db82a8f3cc5db0c9683d9a31

**Comment by hamnaz** [comment]
thankx

**Comment by hamnaz** [comment]
python3 seedrecover.py --no-dupchecks --mnemonic-length 12 --language EN --dsw --wallet-type bip39 --addr-limit 1 --addrs 17GR7xWtWrfYm6y3xoZy8cXioVqBbSYcpU --tokenlist ./docs/Usage_Examples/2020-05-02_Descrambling_a_12_word_seed/randomcombination_bip39.txt
how to use gpu  for above command as shown in vido

**Comment by 3rdIteration** [comment]
Basically just add the --enable-opencl argument after doing the PyOpenCL install covered here https://btcrecover.readthedocs.io/en/latest/GPU_Acceleration/  and in the install guide on YouTube.

**Comment by hamnaz** [comment]
first screen after add opencl command

Starting seedrecover 1.7.0-CryptoGuide, btcrecover 1.7.0-Cryptoguide on Python 3.7.3 64-bit, 21-bit unicodes, 64-bit ints
Loading address database ...
Loaded 162262344 addresses from database ...
Using the 'en' wordlist.
OpenCL: Auto Selecting Best Platform
2021-02-10 04:27:50 : Phase 1/1: up to 12 mistakes, 12 of which can be an entirely different seed word.

OpenCL: Available Platforms
Platform 0 - Name NVIDIA CUDA, Vendor NVIDIA Corporation

OpenCL: Auto Selecting Best Platform
OpenCL: Using Platform: 0
OpenCL: Using Work Group Size:  51200

Counting passwords ...
  172,100,000  ETA: 6 hours and counting

**Comment by hamnaz** [comment]
2nd screen

Starting seedrecover 1.7.0-CryptoGuide, btcrecover 1.7.0-Cryptoguide on Python 3.7.3 64-bit, 21-bit unicodes, 64-bit ints
Loading address database ...
Loaded 162262344 addresses from database ...
Using the 'en' wordlist.
OpenCL: Auto Selecting Best Platform
2021-02-10 04:27:50 : Phase 1/1: up to 12 mistakes, 12 of which can be an entirely different seed word.

OpenCL: Available Platforms
Platform 0 - Name NVIDIA CUDA, Vendor NVIDIA Corporation

OpenCL: Auto Selecting Best Platform
OpenCL: Using Platform: 0
OpenCL: Using Work Group Size:  51200

Counting passwords ...
Done
2021-02-10 04:32:04 : Using 4 worker threads
102400 of 479001600 [-----------------------------------------------------------------------] 0:01:08, ETA:  3 days, 17:27:34

**Comment by hamnaz** [comment]
gpu test

 python3 -m btcrecover.test.test_passwords -v GPUTests
test_bitcoincore_OpenCL_JTR (__main__.Test08KeyDecryption) ... ok
test_bitcoincore_OpenCL_JTR_unicode (__main__.Test08KeyDecryption) ... ok
test_bitcoincore_OpenCL_JTR_low_interrupt_rate (__main__.Test08KeyDecryption) ... ok
test_bitcoincore_OpenCL_JTR_sli (__main__.Test08KeyDecryption) ... skipped 'requires two identical OpenCL devices'

----------------------------------------------------------------------
Ran 4 tests in 16.041s

OK (skipped=1)

**Comment by 3rdIteration** [comment]
@hamnaz is there a question in there? It looks like it's working fine with OpenCL.

**Comment by hamnaz** [comment]
yes bro,
102400 of 479001600 [-----------------------------------------------------------------------] 0:01:08, ETA: 3 days, 17:27:34
this line make me confus, if there is 479m combination in test at gpu why 3days 17 hours required in gpu, and above line 
Using 4 worker threads
says cpu 4 threads useing

**Comment by 3rdIteration** [comment]
It depends on your GPU/CPU. 

Read the performance notes here https://btcrecover.readthedocs.io/en/latest/GPU_Acceleration/

**Comment by hamnaz** [comment]
ok thankx i will study more, and will back if have any issue, thankx for your prompt replies and updates
