### ISSUE TITLE
Can I show private key?

### ISSUE THREAD

**Issue by ntminh611** [3rdIteration/btcrecover#125]
I have dogecoin wallet backup file and used btcrecover to scanned and got my password but I can not import it into dogecoin wallet for android. So, I want to show private key, can I and somebody can help me?

**Comment by 3rdIteration** [comment]
Is this Dogecoin core or something else?

**Comment by ntminh611** [comment]
I don't remember about the app, maybe dogecoin core or something else, it run on android and backup to this file, the file's content (I change some characters to X): 
`U2FsdGVkX1/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXP9ou1sKPns3xr3ye0Og
07y0Tb6fR+FyWac2wOnmDUc96wFo5Ox4GIBNvU9qJ1coDR54iLSJry/lgfz037RwQHV3CxrIva7x
DGy2YFhCqXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXMLT1SZTJ4GF
CWTRwfA=`

**Comment by GitMoDu** [comment]
I'm also having this issue, an altcoin forked MultiBit and now I can't read my private keys, even though I have the password.

**Comment by jimtje** [comment]
As long as your private keys decrypted out to start with either a 6 or a Q you should be good on that front. [There are quite a few reports that newer versions of the Android Dogecoin wallet in question failing to import/restore valid wallet backups made by older versions.](https://www.reddit.com/r/dogecoin/comments/lffdn4/trying_to_restore_wallet_with_3m_doge_get_error/gmug6h2/)

**Comment by 3rdIteration** [comment]
Closed due to inactivity
