### ISSUE TITLE
Can I brute force a certain range of indexes?

### ISSUE THREAD

**Issue by AngeloMetal** [3rdIteration/btcrecover#127]
As far as I've seen, I can only pick a number and it'll find all addresses with that derivation path starting from 0. For example if I enter number 3 it'll search these:
```
m/84'/0'/0'/0
m/84'/0'/0'/1
m/84'/0'/0'/2
```
What I want is to change the starting index. I don't want it to be 0, but something I'll choose. Is there an option for that?
Thanks.

**Comment by 3rdIteration** [comment]
No, you currently need to start at zero, but keep in mind that the performance penalty for a large address generation limit is quite low.

Honestly if you are unsure how far in to the wallet your address is, then your best best is to just use an address database, as if your wallet followed standards, the first address should be used. (Unless you have used a wallet that deliberately makes the gap limit really large)

Which wallet were you using for this seed?

**Comment by AngeloMetal** [comment]
> Which wallet were you using for this seed?

It's not my seed. It's a hunt, someone else's seed. I would never put my money below 100, but due to Wasabi functionalities (coinjoin) I have to search really deep. If you know how deep can CoinJoin reach, drop a reply here, because it'll help me a lot.

As for the starting point. Where exactly is it located and on what file? Or there isn't anywhere? It wouldn't bother me implementing it.

**Comment by 3rdIteration** [comment]
> > Which wallet were you using for this seed?
> 
> It's not my seed. It's a hunt, someone else's seed. I would never put my money below 100, but due to Wasabi functionalities (coinjoin) I have to search really deep. If you know how deep can CoinJoin reach, drop a reply here, because it'll help me a lot.
> 
> As for the starting point. Where exactly is it located and on what file? Or there isn't anywhere? It wouldn't bother me implementing it.

Basically happens here:
https://github.com/3rdIteration/btcrecover/blob/750a096c9825517a1d9033fa33a2f4c40edaa9cf/btcrecover/btcrseed.py#L956

At the moment it just starts at 0, so it's a trivial change to have it start elsewhere via an extra argument. (Or just hardcode it for your use-case)

I haven't really looked in to it, but if you find what some sensible defaults would be for wasabi in terms of this, let me know and I can add it in.

**Comment by 3rdIteration** [comment]
Added in https://github.com/3rdIteration/btcrecover/commit/e196c5ff03336cae689442cf3cd95d1d673f6325
