### ISSUE TITLE
A large token file seems to crash the program and it goes to command prompt.

### ISSUE THREAD

**Issue by satoshidoriannakamoto** [3rdIteration/btcrecover#13]
When I have a short list of tokens the program runs ok.  When the list of tokens is large, say 8000 tokens, the program crashes.  How to fix this?

**Comment by 3rdIteration** [comment]
Try with --no-dupchecks

**Comment by satoshidoriannakamoto** [comment]
Yes, I've tried --no-dupchecks and also --no-eta, but the programs just exits to command prompt.

**Comment by 3rdIteration** [comment]
I just noticed that this was a tokenlist, not a password list. So are you saying that you have 8,000 different building blocks that could make up your password?

**Comment by satoshidoriannakamoto** [comment]
Yes, I have a token list with 8000 words on each line.  However, I specify --max-tokens 3 or --max-tokens 4 to limit the search.

**Comment by 3rdIteration** [comment]
That is an extremely large token list and I can see why it would quickly hit memory limits. Will knock some stuff up at my end to reproduce and have a look after the Py3, multi-derivation path and seed unscrambling stuff is sorted.

**Comment by satoshidoriannakamoto** [comment]
Ok.  Just FYI I am using https://github.com/madacol/btcrecover/tree/p2wpkh-p2sh 

Also the dictionary I am using is: https://github.com/first20hours/google-10000-english

I removed words less than 3 chars.

**Comment by satoshidoriannakamoto** [comment]
Ok, I just downloaded https://github.com/3rdIteration/btcrecover and was able to test the bip39 functionality.  It found a test wallet I made.  Now to find the real passphrase...

**Comment by satoshidoriannakamoto** [comment]
I shorted the list to 5000 with --max-tokens 4.  It no longer crashes and is now running and counting the passwords...
