### ISSUE TITLE
Not working, nothing appening

### ISSUE THREAD

**Issue by Miky94x** [3rdIteration/btcrecover#130]
Hi i've installed python 3.9 with the PATH checked, and then:
`pip3 install -r requirements.txt`
`pip install pycryptodome` 
All without error, but when launching:
`python run-all-tests.py -vv`
nothing happen, what can be the problem? have a good day

**Comment by 3rdIteration** [comment]
You don't need to install pycryptodome, it is part of the requirements.txt.

Nothing happening sounds like you have an issue with your Python environment. What happens if you just run "python" with no other arguments?

**Comment by Miky94x** [comment]
i'm using windows 10
i just discovered the error, for other user with the same error, you just need to go in the search bar in windows and type "Manage App Execution Aliases", open it and there should be two aliases for python, unselect them, which will allow the usual python aliases "python" and "python3"
Have a good day and thanks

**Comment by 3rdIteration** [comment]
Good job sorting it out :)
