### ISSUE TITLE
blockchain main passwors

### ISSUE THREAD

**Issue by yousii-s** [3rdIteration/btcrecover#132]
i got possible pass how look like the real password 
Possible Password ==>Diankey200,&[<== in Decrypted Block ==>{GA"-ls`us38 Ia<==
the real password is Diankey200-@@&

**Comment by 3rdIteration** [comment]
Thanks for the submission, but this is just random characters :)

**Comment by yousii-s** [comment]
?????

**Comment by yousii-s** [comment]
i hade the same probleme whit a wallet whit 5 btc and i cant acces to it

**Comment by 3rdIteration** [comment]
What's your actual question?

**Comment by yousii-s** [comment]
Possible Password ==>Corbina200,&[<== in Decrypted Block ==>{GA"-ls`us38 Ia<==
THIS IS THE REAL
AND THE REAL PASSWORD START WHIT Corbina200

**Comment by 3rdIteration** [comment]
It doesn't matter that the password starts with the same words, is it not detecting the password you it tests the actual one or is it finding an actual match on the incorrect password?

**Comment by yousii-s** [comment]
how i can find the real password when im sure it start with the word Corbina200 and i need to know the characters after
sorry for my english

**Comment by 3rdIteration** [comment]
https://btcrecover.readthedocs.io/en/latest/tokenlist_file/#expanding-wildcards

**Comment by yousii-s** [comment]
i do all this in my token file i use %y and %Y %P Corbina200
%y
%y
%y

**Comment by yousii-s** [comment]
and when i made the password the characters  i use are @ or & or - or euro symbole

**Comment by yousii-s** [comment]
if i can get send me email
souidiyouness@yahoo.com i will give 30%

**Comment by 3rdIteration** [comment]
If you want to organise a paid consultation or assisted recovery, email me
at steve@cryptoguide.tips and we can go from there.
