### ISSUE TITLE
Feature-Request: Specify the filename of "possible_passwords.log"

### ISSUE THREAD

**Issue by ChristophCaina** [3rdIteration/btcrecover#136]
Hi,
the Idea with the possible passwords log file is great!
But I would like to have an option to define the filename of the log file.

e.g. I have more than one wallet which I want to recover - and I would like to run btcrecover for these wallets in parallel (two or more instances of the software).

example:
btcrecover.py --wallet wallet_1.aes.json --autosave wallet_1.savefile --token tokens.txt --password-log possPassword_wallet1.log
btcrecover.py --wallet wallet_2.aes.json --autosave wallet_2.savefile --token tokens.txt --password-log possPassword_wallet2.log

Right now, btcrecover is using the same log file name for possible wallets - which mean, that I need to create different copies of the software to run more instances at the same time - or that it could cause a conflict between these instances since they're trying to use the same log file.

Would such a change be possible?

**Comment by 3rdIteration** [comment]
Added in https://github.com/3rdIteration/btcrecover/commit/e196c5ff03336cae689442cf3cd95d1d673f6325
