### ISSUE TITLE
addresses.db file on Mega is probably incomplete

### ISSUE THREAD

**Issue by aznowak** [3rdIteration/btcrecover#141]
I have run a list of known brainwallets against:
1) addresses.db downloaded from Mega
2) addresses.db generated from my own blockchain

Many well known brainwallets were found in case 2) while they were not found in 1). Examples:
'bitcoin'
'1E984zyYbNmeuumzEdqT8VSL8QGJi3byAD' uncompressed
'18VkRiDhFu2Z17AvtpU3vL2LbTXDzCvDVo' compressed

'satoshi'
'1ADJqstUMBB5zFquWg19UqZ7Zc6ePCpzLE' uncompressed
'1xm4vFerV3pSgvBFkyzLgT1Ew3HQYrS1V' compressed

Those are all compromised brainwallets that should be present in addresses.db. I've used them as a test if the tool worked and I was surprised it wasn't. Only after generating my own database of addresses I've started trusting the tool.
I think it should be checked and fixed since it can give false negatives and people will not get their coins back (!). It is a matter of trust.
```
Wallet difficulty: 1 SHA-256 iteration
Notice: Loading File:  bitcoin.txt
Notice: Finished File:  bitcoin.txt
Notice: Loading File:  bitcoin.txt-----------------------------------------------------------------------------------------] 0:00:00, ETA:  --:--:--
Notice: Finished File:  bitcoin.txt
1 of 1 [#################################################################################################################################] 0:00:00, 
All possible passwords (as specified in your tokenlist or passwordlist) have been checked and none are correct for this wallet. You could consider trying again with a different password list or expanded tokenlist...
```

**Comment by 3rdIteration** [comment]
Can't reproduce.

I tried with a single line passwordlist containing either "satoshi" or "bitcoin" and both work fine, correctly finding both compressed and uncompressed addresses for each.

Sha256 of the address.db that I am using is: DB2CD01E787B414E06621D59538851A11B77025711737B27A4734D8DC5FEA53F and this should be identical to the one on mega for Bitcoin.

Can you confirm that the addresses.db file in use has the same hash?

**Comment by aznowak** [comment]
No. sha256sum on Ubuntu returned:
3ffd1b96a94c2aff2d2e29c214123be6b9b363dd1b1fb687ab6ebd45ec9e03e6 
I have downloaded it already 3 times from Mega, and couldn't make it work.

**Comment by 3rdIteration** [comment]
That's very odd. I downloaded it again from Mega and got a separate SHA256 to what you reported as well as a CRC failure when unzipping it, so will just re-zip and upload. Thanks for the report :)
