### ISSUE TITLE
openCl running with 12 GPUs and Celeron RIG : Context failed: OUT_OF_HOST_MEMORY0  P/s

### ISSUE THREAD

**Issue by lyncker** [3rdIteration/btcrecover#142]
I am trying to run btcrecover on my mining RIG with 12 GPUs and a Celeron CPU. 
In --performance mode I get about 8 kp/s with 4 threads which is realy not much at all , but if I try to increase the threads f.e. to 6 I got the error message :  Context failed: OUT_OF_HOST_MEMORY0  P/s.
The RIG has 8 GB main memory and I am using Windows... 
any ideas?

**Comment by lyncker** [comment]
it seems the --no-dupchecks solved the problem, but its still pretty slow... If I run it with my 4 3060TI + 1660 I got about 8 kp/s not more... my testwallet is a Blockchain.com wallet, here the call : 

5 GPUs in Platoform 0 installed :
btcrecover.py --wallet wallet.aes.json --enable-opencl --performance --thread 10 --opencl-platform 0 --no-dupchecks --no-eta
is the limiting factor the celeron CPU which of course has only 2 physical threads?

**Comment by 3rdIteration** [comment]
Yea you are likely bottlenecking hard with a CPU that weak relative to the GPUs you are trying to keep busy. What is the CPU utilization?

I haven't looked how how 3060s perform but a you can get a general indication of performance here https://btcrecover.readthedocs.io/en/latest/Usage_Examples/2020-10-06_Multi-GPU_with_vastai/Example_Multi-GPU_with_vastai/

**Comment by lyncker** [comment]
I have btcrecover now running in HiveOS (Ubuntu) to see if the problem persists without linux. Here I get with my 4 3060TI 25 kp/s which is still to slow i think... The CPU uitlization is 100% ( 0% idle in Top). 
The strange thing is, I can only run the system with max 4 threads...if I try 6 or more ( they should be 8 for 4 GPUs) I get OUT OF MEM ERROR (yes no-dupechecks is turned on) or the following exception is comming up:

`
multiprocessing.pool.RemoteTraceback:                                                                               
"""                                                                                                                 
Traceback (most recent call last):                                                                                  
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker                                            
    result = (True, func(*args, **kwds))                                                                            
  File "/root/btcrecover/btcrecover/btcrpass.py", line 6052, in return_verified_password_or_false                   
    return loaded_wallet.return_verified_password_or_false(passwords)                                               
  File "/root/btcrecover/btcrecover/btcrpass.py", line 1796, in return_verified_password_or_false                   
    return self._return_verified_password_or_false_opencl(passwords) if (not isinstance(self.opencl_algo,int)) \   
  File "/root/btcrecover/btcrecover/btcrpass.py", line 1849, in _return_verified_password_or_false_opencl           
    clResult = self.opencl_algo.cl_pbkdf2(self.opencl_context_pbkdf2_sha1, passwords, salt_and_iv, iter_count, 32)  
  File "/root/btcrecover/lib/opencl_brute/opencl.py", line 559, in cl_pbkdf2                                       
    prg = ctx[0]                                                                                                    
TypeError: 'int' object is not subscriptable                                                                        
"""                                                                                                                
                                                                                                                   
The above exception was the direct cause of the following exception:                                               
                                                                                                                   
Traceback (most recent call last):                                                                                 
  File "btcrecover.py", line 39, in <module>                                                                       
    (password_found, not_found_msg) = btcrpass.main()                                                              
  File "/root/btcrecover/btcrecover/btcrpass.py", line 6617, in main                                               
    for password_found, passwords_tried_last in password_found_iterator:                                           
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next                                             
    raise value                                                                                                    
TypeError: 'int' object is not subscriptable 
`

The GPUs are connected to riser externders via USB Cables... the data connection for mining is sufficient, but is it also for btcrecover? 
What is this Memory error saying? This cant have anything todo with my so-small CPU, right? I have 8 GB main memory, do I need more?

**Comment by 3rdIteration** [comment]
Have you looked at how the system is going in terms of available ram?

**Comment by lyncker** [comment]
Ok I changed the CPU to a Core i-5 and I added 8 GB to 16 GB RAM... now it works , the 4 3060ti and one 1660 make about 40 mh/s ... Maybe I can optimize it a bit changing the Work Group Size ... 

But the system also has an AMD platform build in , there are 4 RX5700 GPUs If I trigger this platoform I get some Compilewarnings: 

`/usr/local/lib/python3.6/dist-packages/pyopencl/__init__.py:235: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.`

These GPUs then make only around 20 mh/s , which is still to slow ... does this has anything to do with the warnings?

And by the way, is it possible to trigger both systems at the same time? Platform 0 and Platoform 1 ? The comandlineparameter takes only one number ...

**Comment by 3rdIteration** [comment]
At the moment you can only use one platform at a time, the only workaround is to run two instances of BTCRecover and use the --worker command to prevent them from doing the same work. There have been other reports of issues with AMD cards, but at least it is working.

**Comment by lyncker** [comment]
yes thats what I do ... its working now with about 30 Kphs with the Nividias and 30 Kphs with the AMDs ...
