### ISSUE TITLE
Fails to handle large electrum wallet

### ISSUE THREAD

**Issue by fireduck64** [3rdIteration/btcrecover#148]
I was testing btcrecover on encrypted Electrum wallet files just to see how things worked.

I have a large wallet file (104kb) (lots of transaction history) with a known password and btcrecover was unable to open it.  (I put parts of the password in the tokenlist and set a low max-tokens).  

I did some more tests and determined that if I loaded the wallet without a server to create a small file (no history) then btcrecover worked on it.

But if I take the same file, connect to an electrum server and it gets updated with history, then btcrecover no longer works on it.

My guess is that some code that is doing a quick evaluation on the decrypt is not handling the case of a large amount of data.

This is using the latest version from github now.

**Comment by 3rdIteration** [comment]
Confirmed with a wallet about 99Kb, seems to work fine with wallets smaller than this.

[electrum28_largewallet.zip](https://github.com/3rdIteration/btcrecover/files/6182322/electrum28_largewallet.zip) (password is btcr-test-password)

**Comment by 3rdIteration** [comment]
Fixed in https://github.com/3rdIteration/btcrecover/commit/bddc29d5ffe624d4c0bea54a49d31f7c74a51bfc
