### ISSUE TITLE
Implementing Waves platform

### ISSUE THREAD

**Issue by dutchpatriot** [3rdIteration/btcrecover#150]
Great work with this project, came by this project because I am having trouble with a waves wallet right now and tried everything but nothing works to find the seed. The seed is 15 words and I have 13, now I am looking in to implementing Waves but looking into the code I am certain this is never going to work for me due to the lack of python knowledge. So maybe dropping the question here would make your project support recovery of wave coins too...

https://github.com/PyWaves/PyWaves/

I have no Idea how to implement pywaves in the code so that it works for wave to...
Thanks in advance.

**Comment by 3rdIteration** [comment]
It doesn't look like that altcoin is likely to be using BIP39 seeds in the wallet as per: https://medium.com/wavesprotocol/hd-wallet-creation-with-waves-39371d29d7bd

Do you have access to any kind of code or documentation that allows you to reproduce the derivation your wallet uses? (With a test seed)

**Comment by dutchpatriot** [comment]
Ok I ready noticed it to be different. BIP39 usually just doesn't work with the wrong seed, WAVES on the other hand already works after putting in 5 words, it shows you a valid address and all! A friend of mine came to me with his problem and me being the only one he could actually turn to I looked in to it and came by your tool... When I see how WAVES seeds work one could actually use the pywaves to figure out kinda seed algo and than reverse engineer that generating random addresses, check the blockchain if it has value on it and than claim that with the seed...

I know it's far fetched and you need to be lucky but as a matter of fact the whole world gambles in mining farms to kinda do exactly that...

My programming knowledge on python is not good enough to implement pywaves in btcrecover, but I think with a implementation of the address using the pywaves.py you could smash in 10 of the 15 seed words wait like 2 weeks and let it check it against the public address...

The 13 words I have create the same public address on all wallets, and when I put a extra space in between a 3 letter word and a more than 3 letter word it's a completely different wallet. The seed words I have are all 13 on the BIP39-en.txt list... Actually WAVES is so weird and cool at the same time, than when you tell the software you want to import a wallet and you just make up your own 15 (or anything above 5 or 6 for that matter) words it will also work....

Anyways thanks for the response tho...
Hope you can use this to implement it and have your program do even more crazy stuff ;)

**Comment by 3rdIteration** [comment]
So what wallet did you use to generate this seed in the first place? Is it open source? In terms of implementation, I have never heard of this, but if open source wallet implementations exist that mean there is something reproducible, you could always sponsor it as a feature.

**Comment by dutchpatriot** [comment]
Like I said I didn't create the wallet, it was a friend of mine. A friend who has no clue on how to write down a private key or public key, took me 2 hours to decrypt his handwriting on the public address, z written as 2, cap G written as small cap G...

I was astonished too when I saw what happend when trying to figure things out! This looks kinda like a big security thing!

My understanding of this file in pywaves: https://github.com/PyWaves/PyWaves/blob/master/address.py 

Does the magic, it has the seed words in it, and I guess the algo for generating addresses with it. 
If you install this wallet https://waves.exchange/ and import a wallet, ANY WORDS ARE GOOD,  +5 or 6 gives you a valid public address and a wallet access with it...

**Comment by 3rdIteration** [comment]
Even if they wanted to sponsor it they need to work out exactly which wallet they were using with this seed so that can be used as a reference implementation of sorts.

Anyway the question is whether this is something they want to sponsor, as the reality is that something as obscure as this is unlikely to get added any other way unless someone from the waves community decides to put together a pull request.

**Comment by 3rdIteration** [comment]
Closed due to lack of interest from OP
