### ISSUE TITLE
Possible Password , false positive

### ISSUE THREAD

**Issue by absurdnut** [3rdIteration/btcrecover#151]
So i ran btcrecover using --passwordlist option with the downloaded wallet.aes.json file . After the command ran and checked all passwords, i viewed the possible_passwords.log file . There it shows a password as possible password, but i tried it with my wallet, it doesnt work.

 Decrypted Block ==>{kj"TA$ 2FP0-|k<==

**Comment by anywalletrecovery** [comment]
then it hasn't been successful in finding your pass
edit your passlist and try again. or use token file

**Comment by 3rdIteration** [comment]
Thanks for the submission.

This is just random characters, nothing like the examples given in the file.
