### ISSUE TITLE
unable to descramble a 12 word ethereum seed with a list of 18

### ISSUE THREAD

**Issue by pcsimple** [3rdIteration/btcrecover#154]
Hello i have a list of 18 words that i know  my 12 wordseed are in. I know the position of 4 of them but when i try to launch :
python seedrecover.py --no-dupchecks --mnemonic-length 12 --language EN --dsw --wallet-type ethereum --addr-limit 1 --addrs 0x66F9C09118B1C726BC24811a611baf60af42070A --tokenlist randomcombination_bip39.txt --bip32-path "m/44'/60'/0'/0"
The program doesn't recognize 
--dsw
and the file i have created 
--tokenlist randomcombination_bip39.txt
Can you help me to understand how to make a wordlist of 18 word with knowed position of 4?
Thanks

**Comment by 3rdIteration** [comment]
I just tried that exact command with the demo seed and tokenlist file from here: https://btcrecover.readthedocs.io/en/latest/Usage_Examples/2020-05-23_multi_device_descrambling_12_word_seed_with_extras/Example_multi_device_descrambling_12_word_seed_with_extras/ and it worked fine

**Comment by pcsimple** [comment]
Yes sorry i just have try to use your help with with the gurnec version who doesn't contain the directory.
Now i have istalled your version and every thing is fine...
Sorry for the trouble!
Thanks

**Comment by 3rdIteration** [comment]
No worries, good luck with your recovery.
