### ISSUE TITLE
Seedrecover: Add ability to group words together in tokenlists. (Ability for a token to be multiple words)

### ISSUE THREAD

**Issue by amirhglshn** [3rdIteration/btcrecover#155]
Hi. I want to make a token list for descrambling 24 word seed mnemonic and i just know their position 3 by 3 
For example:
1- (picnic culture begin)
2- (frozen average ability)
3- (hobby dog until)
4- (observe valve leisure)
5- (tray birth pride)
6- (approve muffin income)
7- (sketch genius main)
8- (almost onion marriage)
How can i make a tokenlist  just for changing the position of these groups? Sorry for bad english and thanks alot

**Comment by 3rdIteration** [comment]
This is not currently supported, though could be added fairly easily.

**Comment by 3rdIteration** [comment]
Added in https://github.com/3rdIteration/btcrecover/commit/4fa47951df2b5b0e24046d546b29bffc58c6e30b
