### ISSUE TITLE
Please add GPU support for WalletAndroidSpendingPIN

### ISSUE THREAD

**Issue by acoulson2000** [3rdIteration/btcrecover#159]
Apparently it is not yet supported?

Error: WalletAndroidSpendingPIN does not support GPU acceleration (Though it might support OpenCL acceleration using your GPU, so try --enable-opencl)

Error: Wallet Type: WalletAndroidSpendingPIN does not support OpenCL acceleration

**Comment by 3rdIteration** [comment]
Those wallets only require 3 md5 hash operations so and are quite old/obscure now, what ETA are you looking at if you just use CPU? (I haven't bothered to look at seeing whether this would get a meaningful performance boost)

**Comment by acoulson-epicor** [comment]
Hmm. Interesting. I confess I don't really understand the bitcoin protocol wallet internals at all...in fact I don't entirely understand how I can be able to see my balance, but not be able to access it outside of the app without..hashing the pin, I guess?
Well, so far I've gone up to 8 digits (numeric) and it takes 10 days (Ryzen 5 3400G [8 core]), so going beyond that is becoming unfeasible. Was hoping there might be a 10x or 100x improvement (or better if I got another graphics card).

**Comment by 3rdIteration** [comment]
It's normal to have a spending pin, basically the addresses aren't
encrypted but the private keys are.

I haven't implemented it but if you are happy to sponsor it, though unsure
whether it would be a big improvement, I would be surprised if it was as
much as 10x, but it's hard to say until it is implemented.

**Comment by 3rdIteration** [comment]
Closed due to inactivity
