### ISSUE TITLE
Metamask seed recovery

### ISSUE THREAD

**Issue by pcsimple** [3rdIteration/btcrecover#162]
Hello i have try to make seedrecovery recover my metamask account but i have failed...
I have make a tokenlist with the position of 11 of the 12 seeds using : 
"
+ ^1^ word1
+^2^ word2
...
+^11^ word 11
" 
and use 
python seedrecover.py --no-dupchecks --mnemonic-length 12 --language EN --dsw --wallet-type ethereum --addr-limit 1 --addrs 0xxxxxxxxxxxxxxxxxxxxxxxxx --tokenlist ./docs/Usage_Examples/2020-05-02_Descrambling_a_12_word_seed/words.txt --bip32-path "m/44'/60'/0'/0"
but finished with "seed not found sorry..."
Could you explain me what i am doing wrong?
Thanks

**Comment by 3rdIteration** [comment]
So do you know 11/12 of the words and their position? In that case, you can just run seedrecover without any additional arguments and put an X in the place of the missing word. (It will prompt you for your wallet type and you can just select Eth)

**Comment by anywalletrecovery** [comment]
one word missing piece of cake, you can recover in 1 second
