### ISSUE TITLE
Nvidia CUDA implementation request

### ISSUE THREAD

**Issue by MojoMoe** [3rdIteration/btcrecover#163]
This is a request rather than an issue:

Any chance of implementing your code so it works with Nvidia CUDA GPUs?

[https://developer.nvidia.com/blog/unifying-the-cuda-python-ecosystem/?ncid=so-twit-593261#cid=gtcs21_so-twit_en-us](url)

I hope it's doable. The performance gains would be awesome.

**Comment by 3rdIteration** [comment]
I can have a look but it isn't likely to be much better than the existing pyOpencl implementation that enables GPU acceleration.

**Comment by 3rdIteration** [comment]
Looks like this is now released and is a drop-in replacement for Numpy.

Given that BTCRecover doesn't do lots of matrix math operations it isn't really applicable in terms of boosting performance beyond what we get in pyopencl.
