### ISSUE TITLE
Using external password generator at runtime

### ISSUE THREAD

**Issue by willykleitinho** [3rdIteration/btcrecover#166]
My password is very long and I probably don't have enough space to store it in a file.
Is it possible to use some external password generator at runtime (like crunch)?

**Comment by 3rdIteration** [comment]
You can't directly pipe passwords straight in to it at runtime. If you are doing a seed based recovery, you can achieve something similar with the --multi-file-seedlist argument, basically it can consume seedlist files on the fly even if they weren't there at the start. (The main issue is that this just terminates when it runs out of files)

Is there a complexity issue that means you wouldn't just use a tokenlist?

**Comment by willykleitinho** [comment]
> You can't directly pipe passwords straight in to it at runtime. If you are doing a seed based recovery, you can achieve something similar with the --multi-file-seedlist argument, basically it can consume seedlist files on the fly even if they weren't there at the start. (The main issue is that this just terminates when it runs out of files)
> 
> Is there a complexity issue that means you wouldn't just use a tokenlist?

Thank you for your reply!
My password is very long but it follows a simple structure. So I made a python program to generate passwords with the specifications.
But I've remembered more of the password and now I made a list using crunch. Hope it works.
