### ISSUE TITLE
seedrecover problem with opencl

### ISSUE THREAD

**Issue by martinkan20** [3rdIteration/btcrecover#168]
hi all,
previously i was using seedrecover without any issues both on my cpu and opencl.
but it is almost a weak that i get a lot of errors when running it on opencl
here are some on problem and I will attach all of the problem
i even check with a new computer, i got the same errors
clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'NVIDIA GeForce GTX 1080 Ti' on 'NVIDIA CUDA' at 0x2828c4343d0>:

<kernel>:494:71: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
    hash_private(input_2, hashBlockSize_bytes + hashDigestSize_bytes, output);
                                                                      ^~~~~~
<kernel>:393:1: note: passing argument to parameter 'hash' here
def_hash(hash_private, __private, __private, md_pad__private, printFromLong_n)
^
<kernel>:304:103: note: expanded from macro 'def_hash'
static void funcName(inputTag unsigned long *input, const unsigned int length, hashTag unsigned long* hash)    \
                                                                                                      ^
<kernel>:624:20: warning: initializing '__global unsigned long *__attribute__((address_space(16776963)))' with an expression of type 'unsigned long const __global[4]' discards qualifiers
    __global word *pwdBuffer = pwdbuffer_arg[0].buffer;

[errorr.txt](https://github.com/3rdIteration/btcrecover/files/6350865/errorr.txt)

**Comment by martinkan20** [comment]
I solved the error myself

**Comment by CryptoCoinLab** [comment]
> 
> 
> I solved the error myself

I encounter this problem too, how to deal with this.

/tmp/OCL8914T31.cl:693:20: warning: initializing '__global unsigned int *' with an expression of type 'unsigned int const __global[8]' discards qualifiers
    __global word *pwdBuffer = pwdbuffer_arg[0].buffer;

**Comment by anywalletrecovery** [comment]
> > I solved the error myself
> 
> I encountered this problem too, how to deal with this.
> 
> Build on <pyopencl.Device 'Ellesmere' on 'AMD Accelerated Parallel Processing' at 0x1d09a10> succeeded, but said:
> 
> /tmp/OCL8914T31.cl:693:20: warning: initializing '__global unsigned int *' with an expression of type 'unsigned int const __global[8]' discards qualifiers
> __global word *pwdBuffer = pwdbuffer_arg[0].buffer;

this is an issue with your gpu driver

**Comment by 3rdIteration** [comment]
OP solved it themselves
