### ISSUE TITLE
Add Support to Import into Python Code

### ISSUE THREAD

**Issue by csek06** [3rdIteration/btcrecover#171]
I looked through various use cases and couldn't find the answer.
I am looking to generate public ethereum addresses from a list of valid mnemonics. I already have the mnemonics.

I believe btcrecover would have the most performant code.

something like the following...
```python
import btcrecover as btcr
mn = 'element entire sniff tired miracle solve shadow scatter hello never tank side sight isolate sister uniform advice pen praise soap lizard festival connect baby'
path = "m/44'/2'/0'/0"
print(btcr.pubAddressFromMnemonic(mn, path))
```
```
LQ6uvyPGK4Lgr38am5oEFqHve3zV76Uxcb
```

**Comment by 3rdIteration** [comment]
You can already import btcrseed wallets as a module, though not in the way that you describe. BTCRecover doesn't actually go as far as to generate addresses, it works entirely off checking the hash160. (Which is then used by wallets as the input for generating an address) 

Unless you are looking to generate billions of addresses continuously, then something like https://pypi.org/project/pywallet/ is a good candidate.

If you are just looking to check a list of mnemonics to see if any of them match a given address (or addresses) then you could just use the seedlist functionality for this.
