### ISSUE TITLE
PLEASE HELP!!!!! Know Prefix and Suffix of my private keys...

### ISSUE THREAD

**Issue by trextrader** [3rdIteration/btcrecover#172]
Hello,

If I have the prefixes and suffixes of my private keys, most 8 characters in the beginning and 8,9 or 10 at the end but everything in the middle is unknown, how to setup btcrecover to fill in the missing middle part?

For example - Compressed priv key is 52 characters:

xxxxxxxx-************************-yyyyyyyyy

In this case x's and y's chars are known. 8 chars for X and 9 chars for y summing to 17 of the 52, leaving 35 chars (case sensitive) unknown in the center for a BASE58 (P2PKH) bitcoin address.

Effectively, my kids accidentally spilled kool-aid on the sheet of paper I had left on the counter which is the only copy that had my priv keys, I managed to salvage the prefixes and suffixes, however, the middle is lost to the kool-aid monster.

Please help.  This is literally approx. 22K in BTC which I purchased in 2009/2010 for sub penny.  I went to sell some and damn near fainted.  Of course its not the kids fault they did not know and my fault for leaving it on the counter. If this can be cracked using BTCrecover would be more than happy to give 5% of the total recovered to you.  Its a total of 7 btc addresses ranging from 25 BTC to > 11,000 btc.

I have no other way of recovery.

PLEASE HELP!!!

**Comment by 3rdIteration** [comment]
Just did some quick math and basically the max missing characters that you could realistically hope to recover from a raw base58 encoded private key is 6.... If you only have 17/52 then you realistically have nothing... (From what you have described, you are missing over half, so over 128 bits worth of data...)

Basically you need to narrow down the number of missing characters dramatically... Is this likely to be possible?

**Comment by anywalletrecovery** [comment]
> Hello,
> 
> If I have the prefixes and suffixes of my private keys, most 8 characters in the beginning and 8,9 or 10 at the end but everything in the middle is unknown, how to setup btcrecover to fill in the missing middle part?
> 
> For example - Compressed priv key is 52 characters:
> 
> xxxxxxxx-************************-yyyyyyyyy
> 
> In this case x's and y's chars are known. 8 chars for X and 9 chars for y summing to 17 of the 52, leaving 35 chars (case sensitive) unknown in the center for a BASE58 (P2PKH) bitcoin address.
> 
> Effectively, my kids accidentally spilled kool-aid on the sheet of paper I had left on the counter which is the only copy that had my priv keys, I managed to salvage the prefixes and suffixes, however, the middle is lost to the kool-aid monster.
> 
> Please help. This is literally approx. 22K in BTC which I purchased in 2009/2010 for sub penny. I went to sell some and damn near fainted. Of course its not the kids fault they did not know and my fault for leaving it on the counter. If this can be cracked using BTCrecover would be more than happy to give 5% of the total recovered to you. Its a total of 7 btc addresses ranging from 25 BTC to > 11,000 btc.
> 
> I have no other way of recovery.
> 
> PLEASE HELP!!!

Brainflayer has an option exactly for this purpose
however your missing character are so high which demands hashrate of several galaxies to recover it

**Comment by 3rdIteration** [comment]
Closed due to impractical recovery with no other request
