### ISSUE TITLE
btcrecover 1.9.0 don't work with opencl under AMD R470

### ISSUE THREAD

**Issue by CryptoCoinLab** [3rdIteration/btcrecover#173]
ubuntu 16 LTS, git clone https://github.com/3rdIteration/btcrecover just now.

**python btcrecover.py --opencl-info**

Starting btcrecover 1.9.0-Cryptoguide on Python 3.9.1 64-bit, 21-bit unicodes, 64-bit ints

============================================================
OpenCL Platforms and Devices
============================================================
Platform 0 - Name: AMD Accelerated Parallel Processing
Platform 0 - Vendor: Advanced Micro Devices, Inc.
Platform 0 - Version: OpenCL 2.1 AMD-APP (3004.6)
Platform 0 - Profile: FULL_PROFILE
 --------------------------------------------------------

 Device 0 - Name: Ellesmere
 Device 0 - Type: ALL | GPU
 Device 0 - Max Clock Speed: 1126 Mhz
 Device 0 - Compute Units: 28
 Device 0 - Local Memory: 32 KB
 Device 0 - Constant Memory: 3341948 KB
 Device 0 - Global Memory: 4 GB
 Device 0 - Max Buffer/Image Size: 3264 MB
 Device 0 - Max Work Group Size: 256

Encountered error: 

warning: initializing '__global unsigned int *' with an expression of type 'unsigned int const __global[8]' discards qualifiers
    __global word *pwdBuffer = pwdbuffer_arg[0].buffer;
                   ^           ~~~~~~~~~~~~~~~~~~~~~~~

**Comment by CryptoCoinLab** [comment]
ok ,it is simple to solve this issue, 

__global word *pwdBuffer = pwdbuffer_arg[0].buffer; 

=>  __global word *pwdBuffer = (__global word *) pwdbuffer_arg[0].buffer;


**However, when I run :**
python btcrecover.py --enable-opencl  --no-dupchecks  --addr-limit 1 --addressdb btc_2021_2_5.db  --mnemonic "replaced by 12 words" --bip32-path "m/44'/0'/0'/0"  --dsw --wallet-type bip39 --language en  --tokenlist dict.txt  --opencl-devices 0,1,2,3,4,5,6,7 --no-eta

**dict.txt like** 

%2ia%3d%3y

**The result:** 

Starting btcrecover 1.9.0-Cryptoguide on Python 3.9.1 64-bit, 21-bit unicodes, 64-bit ints
Loading address database ...
Using the 'en' wordlist.
Assuming a 12 word mnemonic. (This can be overridden with --mnemonic-length)

OpenCL: Available Platforms
Platform 0 - Name AMD Accelerated Parallel Processing, Vendor Advanced Micro Devices, Inc.

OpenCL: Auto Selecting Best Platform
OpenCL: Using Platform: 0
OpenCL: Using Work Group Size:  256

Wallet difficulty: 2048 PBKDF2-SHA512 iterations + ECC
2021-04-28 10:15:54 : Using 2 worker threads                                                                                                                                                         
| 432896  elapsed: 0:12:21  rate: 583.59  P/s               

**Obviously,  the GPUs didn't work.  This computer has 8 R470 VGA cards,  Why ?

Another computer with one GeForce GTX 950A VGA card.**

Starting btcrecover 1.9.0-Cryptoguide on Python 3.8.5 64-bit, 21-bit unicodes, 64-bit ints
Loading address database ...
Using the 'en' wordlist.
Assuming a 12 word mnemonic. (This can be overridden with --mnemonic-length)

OpenCL: Available Platforms
Platform 0 - Name NVIDIA CUDA, Vendor NVIDIA Corporation
Platform 1 - Name Intel(R) OpenCL, Vendor Intel(R) Corporation

OpenCL: Auto Selecting Best Platform
OpenCL: Using Platform: 0
OpenCL: Using Work Group Size:  1024

Wallet difficulty: 2048 PBKDF2-SHA512 iterations + ECC
2021-04-28 13:16:02 : Using 4 worker threads
\ 60932096  elapsed: 3:14:03  rate:   5.23 kP/s

So, how to improve the performance of  btcrecover with 8 R470 VGA cards ?

**Comment by CryptoCoinLab** [comment]
More reports about bip39 wallet bruting with btcrecover enabling opencl.

Laptop :  Intel i7-10875H 8 cores ,   Nivida 3060 Laptop GPU,   32G memory

**Test 1: With GPU :  1.22 kP/s** 
python btcrecover.py --enable-opencl --no-dupchecks --addr-limit 1 --addressdb btc_2021_2_5.db --mnemonic "replaced by 12 words" --bip32-path "m/44'/0'/0'/0" --dsw --wallet-type bip39 --language en --tokenlist dict.txt --no-eta

Starting btcrecover 1.9.0-Cryptoguide on Python 3.9.1 64-bit, 21-bit unicodes, 64-bit ints
Loading address database ...
Using the 'en' wordlist.
Assuming a 12 word mnemonic. (This can be overridden with --mnemonic-length)

OpenCL: Available Platforms
Platform 0 - Name NVIDIA CUDA, Vendor NVIDIA Corporation
Platform 1 - Name Intel(R) OpenCL HD Graphics, Vendor Intel(R) Corporation
Platform 2 - Name Intel(R) OpenCL, Vendor Intel(R) Corporation

OpenCL: Auto Selecting Best Platform
OpenCL: Using Platform: 0
OpenCL: Using Work Group Size:  1024

Wallet difficulty: 2048 PBKDF2-SHA512 iterations + ECC
2021-04-29 09:01:28 : Using 16 worker threads
- 705536  elapsed: 0:09:36  rate:   1.22 kP/s

**Test 2:  No GPU :  1.78 kP/s** 
python btcrecover.py --no-dupchecks --addr-limit 1 --addressdb btc_2021_2_5.db --mnemonic "replaced by 12 words" --bip32-path "m/44'/0'/0'/0" --dsw --wallet-type bip39 --language en --tokenlist dict.txt  --no-eta

Starting btcrecover 1.9.0-Cryptoguide on Python 3.9.1 64-bit, 21-bit unicodes, 64-bit ints
Loading address database ...
Using the 'en' wordlist.
Assuming a 12 word mnemonic. (This can be overridden with --mnemonic-length)
Wallet difficulty: 2048 PBKDF2-SHA512 iterations + ECC
2021-04-29 09:11:43 : Using 16 worker threads
- 974897  elapsed: 0:09:08  rate:   1.78 kP/s

**Comment by 3rdIteration** [comment]
What CPU do you have in that system, if it's a mining rig you are likely hitting a CPU bottlekneck with BIP39 seeds...

**Comment by CryptoCoinLab** [comment]
> 
> 
> What CPU do you have in that system, if it's a mining rig you are likely hitting a CPU bottlekneck with BIP39 seeds...

This is a GPU miner with Intel(R) Celeron(R) CPU 3855U @ 1.60GHz and 8 RTX R480/470 VGA adapters. 

Hashcat runs very well on it, and gets  80-90kP/s on cracking Bitcoin Core wallet,  however it seems hashcat doesn't support BIP39 passphrase cracking.

**Comment by CryptoCoinLab** [comment]
**More reports**

**Aliyun Clould VPS:  12  Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz / 92 GiB /  1 NVIDIA V100  GPU** 

**Test 1  without GPU : 2.82 kP/s ** 

python3 btcrecover.py  --no-dupchecks  --addr-limit 1 --addressdb btc_2021_2_5.db  --mnemonic "12 words" --bip32-path "m/44'/0'/0'/0"  --dsw --wallet-type bip39 --language en  --tokenlist dict.txt  --no-eta 

Starting btcrecover 1.9.0-Cryptoguide on Python 3.8.5 64-bit, 21-bit unicodes, 64-bit ints
Loading address database ...
Using the 'en' wordlist.
Assuming a 12 word mnemonic. (This can be overridden with --mnemonic-length)
Wallet difficulty: 2048 PBKDF2-SHA512 iterations + ECC
2021-04-30 12:57:09 : Using 12 worker threads
621930  elapsed: 0:03:40  rate:   2.82 kP/s 

**Test 2  with GPU:  5.76 kP/s ** 

python3 btcrecover.py --enable-opencl  --no-dupchecks  --addr-limit 1 --addressdb btc_2021_2_5.db  --mnemonic "12 words" --bip32-path "m/44'/0'/0'/0"  --dsw --wallet-type bip39 --language en  --tokenlist dict.txt  --opencl-devices 0 --no-eta --opencl-workgroup-size 4096

Starting btcrecover 1.9.0-Cryptoguide on Python 3.8.5 64-bit, 21-bit unicodes, 64-bit ints
Loading address database ...
Using the 'en' wordlist.
Assuming a 12 word mnemonic. (This can be overridden with --mnemonic-length)

OpenCL: Available Platforms
Platform 0 - Name NVIDIA CUDA, Vendor NVIDIA Corporation

OpenCL: Auto Selecting Best Platform
OpenCL: Using Platform: 0
OpenCL: Using Work Group Size:  10240

Wallet difficulty: 2048 PBKDF2-SHA512 iterations + ECC
2021-04-30 12:39:28 : Using 12 worker threads
4945920  elapsed: 0:14:18  rate:   5.76 kP/s

**Comment by 3rdIteration** [comment]
You are just hitting CPU bottleknecks trying to use a mining rig for a BIP39 seed recovery... It uses both a lot of CPU and GPU resources... 

Have a read of the documentation here: https://btcrecover.readthedocs.io/en/latest/GPU_Acceleration/ You can decrease the CPU usage by doing things like decreasing the number of derivation paths checked, decreasing the address generation limit and possibly not using an addressDB (depending on how much ram you have, as you will need at least as much ram as the size of the addressDB)

Is there an actual bug that you are reporting?

**Comment by CryptoCoinLab** [comment]
Thank you for your answer, it help me a lot.  I am trying all your advices. 

In fact, I am cracking a wallet's BIP39 passphrase, and without address, so it seems that seedrecover.py is not a good choice. 

BTW,  I tested my mining rig with 8 AMD R470 adapters using these commands :

          python -m btcrecover.test.test_passwords -v GPUTests
and    python -m btcrecover.test.test_seeds -v OpenCL_Tests  

are ok.  

However,  when I run

            python -m btcrecover.test.test_passwords -v OpenCL_Tests

 I encountered errors, I don't know why.

test_bitcoincore_OpenCL_Brute (__main__.Test08KeyDecryption) ... ok
test_blockchain_main_OpenCL_Brute (__main__.Test08KeyDecryption) ... ok
test_blockchain_second_OpenCL_Brute (__main__.Test07WalletDecryption) ... ok
test_Electrum28_OpenCL_Brute (unittest.loader._FailedTest) ... ERROR
test_bip39_mpk_opencl_brute (__main__.Test08BIP39Passwords) ... ERROR

Stdout:
xpub depth:       3
xpub parent fingerprint: b'BE532DE9'
xpub child #:     0'
WARNING: Derivaton path: 4 does not match the xpub you have provided.
Using the 'en' wordlist.
Assuming a 12 word mnemonic. (This can be overridden with --mnemonic-length)
OpenCL: Auto Selecting Best Platform

Stderr:
Exception ignored in: <_io.FileIO name='/home/work/bk/btcrecover/lib/bitcoinlib/config/VERSION' mode='rb' closefd=True>
Traceback (most recent call last):
  File "/home/work/bk/btcrecover/lib/bitcoinlib/config/config.py", line 301, in <module>
    BITCOINLIB_VERSION = Path(BCL_INSTALL_DIR, 'config/VERSION').open().read().strip()
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/work/bk/btcrecover/lib/bitcoinlib/config/VERSION' mode='r' encoding='UTF-8'>
test_Electrum2_mpk_opencl_brute (__main__.Test08BIP39Passwords) ... ERROR

Stdout:
xpub depth:       1
xpub parent fingerprint: b'E00F7BFB'
xpub child #:     0'
WARNING: Derivaton path: 1 does not match the xpub you have provided.
Using the 'en' wordlist.

Stderr:
notice: presence of a mnemonic passphrase implies a 12-word long Electrum 2.7+ mnemonic
test_yoroi_opencl_brute (__main__.Test10YoroiWalletDecryption) ... ERROR

Stdout:
OpenCL: Auto Selecting Best Platform
test_bip38_bitcoin_opencl_brute (__main__.Test11BIP38WalletDecryption) ... ERROR

Stdout:
OpenCL: Auto Selecting Best Platform
Loading Alternative sCrypt Kernel: sCrypt_Bip38fork.cl

======================================================================
ERROR: test_Electrum28_OpenCL_Brute (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: type object 'Test07WalletDecryption' has no attribute 'test_Electrum28_OpenCL_Brute'

======================================================================
ERROR: test_bip39_mpk_opencl_brute (__main__.Test08BIP39Passwords)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/work/bk/btcrecover/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/work/bk/btcrecover/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/work/bk/btcrecover/btcrecover/test/test_passwords.py", line 1401, in test_bip39_mpk_opencl_brute
    self.bip39_tester_opencl(
  File "/home/work/bk/btcrecover/btcrecover/test/test_passwords.py", line 1394, in bip39_tester_opencl
    (tstr("btcr-wrong-password-1"), tstr("btcr-wrong-password-2"))), (False, 2))
TypeError: 'NoneType' object is not callable

Stdout:
xpub depth:       3
xpub parent fingerprint: b'BE532DE9'
xpub child #:     0'
WARNING: Derivaton path: 4 does not match the xpub you have provided.
Using the 'en' wordlist.
Assuming a 12 word mnemonic. (This can be overridden with --mnemonic-length)
OpenCL: Auto Selecting Best Platform

Stderr:
Exception ignored in: <_io.FileIO name='/home/work/bk/btcrecover/lib/bitcoinlib/config/VERSION' mode='rb' closefd=True>
Traceback (most recent call last):
  File "/home/work/bk/btcrecover/lib/bitcoinlib/config/config.py", line 301, in <module>
    BITCOINLIB_VERSION = Path(BCL_INSTALL_DIR, 'config/VERSION').open().read().strip()
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/work/bk/btcrecover/lib/bitcoinlib/config/VERSION' mode='r' encoding='UTF-8'>

======================================================================
ERROR: test_Electrum2_mpk_opencl_brute (__main__.Test08BIP39Passwords)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/work/bk/btcrecover/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/work/bk/btcrecover/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/work/bk/btcrecover/btcrecover/test/test_passwords.py", line 1409, in test_Electrum2_mpk_opencl_brute
    self.bip39_tester(
  File "/home/work/bk/btcrecover/btcrecover/test/test_passwords.py", line 1423, in bip39_tester
    (tstr("btcr-wrong-password-1"), tstr("btcr-wrong-password-2"))), (False, 2))
TypeError: 'NoneType' object is not callable

Stdout:
xpub depth:       1
xpub parent fingerprint: b'E00F7BFB'
xpub child #:     0'
WARNING: Derivaton path: 1 does not match the xpub you have provided.
Using the 'en' wordlist.

Stderr:
notice: presence of a mnemonic passphrase implies a 12-word long Electrum 2.7+ mnemonic

======================================================================
ERROR: test_yoroi_opencl_brute (__main__.Test10YoroiWalletDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/work/bk/btcrecover/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/work/bk/btcrecover/btcrecover/test/test_passwords.py", line 2178, in test_yoroi_opencl_brute
    correct_pw = tstr("btcr-test-password")
TypeError: 'NoneType' object is not callable

Stdout:
OpenCL: Auto Selecting Best Platform

======================================================================
ERROR: test_bip38_bitcoin_opencl_brute (__main__.Test11BIP38WalletDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/work/bk/btcrecover/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/work/bk/btcrecover/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/work/bk/btcrecover/btcrecover/test/test_passwords.py", line 2214, in test_bip38_bitcoin_opencl_brute
    self.bip38_tester_opencl('6PnM7h9sBC9EMZxLVsKzpafvBN8zjKp8MZj6h9mfvYEQRMkKBTPTyWZHHx')
  File "/home/work/bk/btcrecover/btcrecover/test/test_passwords.py", line 2201, in bip38_tester_opencl
    correct_pw = tstr("btcr-test-password")
TypeError: 'NoneType' object is not callable

Stdout:
OpenCL: Auto Selecting Best Platform
Loading Alternative sCrypt Kernel: sCrypt_Bip38fork.cl

----------------------------------------------------------------------
Ran 8 tests in 14.191s

FAILED (errors=5)

**Comment by 3rdIteration** [comment]
Riteo, well give it a go with Ubuntu 20.04 and the latest drivers and it should work fine, as your errors don't look to be related to opencl compilation errors. Ubuntu 16 is unsupported.

BIP39 passphrase recovery will be about 5x faster on modern GPU than CPU, as per the documentation. I get ~2 kp/s on CPU and ~10kp/s on a 1660ti)

**Comment by CryptoCoinLab** [comment]
So I am finding way to reach 5x speed up on GPU. However,  I don't make it yet.

Laptop : Intel i7-10875H 8 cores  / Nivida 3060 Laptop GPU  / 32G memory / Python 3.9.1 / cuda_11.1  or  cuda_10.0 / pyopencl 2021.1.1 cl12  or  pyopencl 2021.1.1 cl21 or pyopencl 2021.1.5 cl12

Run 

          python -m btcrecover.test.test_passwords -v OpenCL_Tests

D:\CrackWallet\btcrecover>python -m btcrecover.test.test_passwords -v OpenCL_Tests
test_bitcoincore_OpenCL_Brute (__main__.Test08KeyDecryption) ... ok
test_blockchain_main_OpenCL_Brute (__main__.Test08KeyDecryption) ... ok
test_blockchain_second_OpenCL_Brute (__main__.Test07WalletDecryption) ... ok
test_Electrum28_OpenCL_Brute (unittest.loader._FailedTest) ... ERROR
test_bip39_mpk_opencl_brute (__main__.Test08BIP39Passwords) ... ERROR

Stdout:
xpub depth:       3
xpub parent fingerprint: b'BE532DE9'
xpub child #:     0'
WARNING: Derivaton path: 4 does not match the xpub you have provided.
Using the 'en' wordlist.
Assuming a 12 word mnemonic. (This can be overridden with --mnemonic-length)
OpenCL: Auto Selecting Best Platform

Stderr:
Exception ignored in: <_io.FileIO name='D:\\CrackWallet\\btcrecover\\lib\\bitcoinlib\\config\\VERSION' mode='rb' closefd=True>
Traceback (most recent call last):
  File "D:\CrackWallet\btcrecover\lib\bitcoinlib\config\config.py", line 301, in <module>
    BITCOINLIB_VERSION = Path(BCL_INSTALL_DIR, 'config/VERSION').open().read().strip()
ResourceWarning: unclosed file <_io.TextIOWrapper name='D:\\CrackWallet\\btcrecover\\lib\\bitcoinlib\\config\\VERSION' mode='r' encoding='utf8'>
test_Electrum2_mpk_opencl_brute (__main__.Test08BIP39Passwords) ... ERROR

Stdout:
xpub depth:       1
xpub parent fingerprint: b'E00F7BFB'
xpub child #:     0'
WARNING: Derivaton path: 1 does not match the xpub you have provided.
Using the 'en' wordlist.

Stderr:
notice: presence of a mnemonic passphrase implies a 12-word long Electrum 2.7+ mnemonic
test_yoroi_opencl_brute (__main__.Test10YoroiWalletDecryption) ... ERROR

Stdout:
OpenCL: Auto Selecting Best Platform
test_bip38_bitcoin_opencl_brute (__main__.Test11BIP38WalletDecryption) ... ERROR

Stdout:
OpenCL: Auto Selecting Best Platform
Loading Alternative sCrypt Kernel: sCrypt_Bip38fork.cl

======================================================================
ERROR: test_Electrum28_OpenCL_Brute (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: type object 'Test07WalletDecryption' has no attribute 'test_Electrum28_OpenCL_Brute'

======================================================================
ERROR: test_bip39_mpk_opencl_brute (__main__.Test08BIP39Passwords)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\CrackWallet\btcrecover\btcrecover\test\test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "D:\CrackWallet\btcrecover\btcrecover\test\test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "D:\CrackWallet\btcrecover\btcrecover\test\test_passwords.py", line 1401, in test_bip39_mpk_opencl_brute
    self.bip39_tester_opencl(
  File "D:\CrackWallet\btcrecover\btcrecover\test\test_passwords.py", line 1394, in bip39_tester_opencl
    (tstr("btcr-wrong-password-1"), tstr("btcr-wrong-password-2"))), (False, 2))
TypeError: 'NoneType' object is not callable

Stdout:
xpub depth:       3
xpub parent fingerprint: b'BE532DE9'
xpub child #:     0'
WARNING: Derivaton path: 4 does not match the xpub you have provided.
Using the 'en' wordlist.
Assuming a 12 word mnemonic. (This can be overridden with --mnemonic-length)
OpenCL: Auto Selecting Best Platform

Stderr:
Exception ignored in: <_io.FileIO name='D:\\CrackWallet\\btcrecover\\lib\\bitcoinlib\\config\\VERSION' mode='rb' closefd=True>
Traceback (most recent call last):
  File "D:\CrackWallet\btcrecover\lib\bitcoinlib\config\config.py", line 301, in <module>
    BITCOINLIB_VERSION = Path(BCL_INSTALL_DIR, 'config/VERSION').open().read().strip()
ResourceWarning: unclosed file <_io.TextIOWrapper name='D:\\CrackWallet\\btcrecover\\lib\\bitcoinlib\\config\\VERSION' mode='r' encoding='utf8'>

======================================================================
ERROR: test_Electrum2_mpk_opencl_brute (__main__.Test08BIP39Passwords)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\CrackWallet\btcrecover\btcrecover\test\test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "D:\CrackWallet\btcrecover\btcrecover\test\test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "D:\CrackWallet\btcrecover\btcrecover\test\test_passwords.py", line 1409, in test_Electrum2_mpk_opencl_brute
    self.bip39_tester(
  File "D:\CrackWallet\btcrecover\btcrecover\test\test_passwords.py", line 1423, in bip39_tester
    (tstr("btcr-wrong-password-1"), tstr("btcr-wrong-password-2"))), (False, 2))
TypeError: 'NoneType' object is not callable

Stdout:
xpub depth:       1
xpub parent fingerprint: b'E00F7BFB'
xpub child #:     0'
WARNING: Derivaton path: 1 does not match the xpub you have provided.
Using the 'en' wordlist.

Stderr:
notice: presence of a mnemonic passphrase implies a 12-word long Electrum 2.7+ mnemonic

======================================================================
ERROR: test_yoroi_opencl_brute (__main__.Test10YoroiWalletDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\CrackWallet\btcrecover\btcrecover\test\test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "D:\CrackWallet\btcrecover\btcrecover\test\test_passwords.py", line 2178, in test_yoroi_opencl_brute
    correct_pw = tstr("btcr-test-password")
TypeError: 'NoneType' object is not callable

Stdout:
OpenCL: Auto Selecting Best Platform

======================================================================
ERROR: test_bip38_bitcoin_opencl_brute (__main__.Test11BIP38WalletDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\CrackWallet\btcrecover\btcrecover\test\test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "D:\CrackWallet\btcrecover\btcrecover\test\test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "D:\CrackWallet\btcrecover\btcrecover\test\test_passwords.py", line 2214, in test_bip38_bitcoin_opencl_brute
    self.bip38_tester_opencl('6PnM7h9sBC9EMZxLVsKzpafvBN8zjKp8MZj6h9mfvYEQRMkKBTPTyWZHHx')
  File "D:\CrackWallet\btcrecover\btcrecover\test\test_passwords.py", line 2201, in bip38_tester_opencl
    correct_pw = tstr("btcr-test-password")
TypeError: 'NoneType' object is not callable

Stdout:
OpenCL: Auto Selecting Best Platform
Loading Alternative sCrypt Kernel: sCrypt_Bip38fork.cl

----------------------------------------------------------------------
Ran 8 tests in 11.844s

FAILED (errors=5)

**Comment by 3rdIteration** [comment]
Can't reproduce these failures with Python 3.9.3 and Version: 2021.1.4+cl12

**Comment by CryptoCoinLab** [comment]
Did I miss some important things ? I will try the test again under Python 3.9.3 and Version: 2021.1.4+cl12.

As for the result testing of two computers' ,  obviously, I missed something I don't know. 

I  installed the same VGA adapter driver, and the same version pyopencl.

The Lenovo Computer is very old, and I buy the Laptop Computer a months ago. 

I thought the later should run well than the former does.

1. Lenovo Computer: Windows 10 / I5-6400 CPU 2.7GHz 2 Cores / NVIDIA GeForce GTX 950A / 16G Memory / Python 3.8.5 / Cuda 10.0 / pyopencl 2021.1.1  (compiled from source ) 

CPU： 4 threads,  1.50kP/s  ;   GPU:  4 threads ,  5.30kP/s

CPU： 2 threads,  0.80kP/s  ;   GPU:  2 threads ,  4.42kP/s

CPU： 1 threads,  0.42kP/s  ;   GPU:  1 threads ,  2.30kP/s

2. Laptop Computer:  Windows 10 / Intel i7-10875H 8 cores / Nvida RTX 3060 Laptop GPU / 32G memory / Python 3.9.1 / Cuda_10.0 / pyopencl 2021.1.1  (compiled from source ) 

CPU: 16 threads, 1.78kP/s ;    GPU:  16 threads, 1.30kP/s ;

CPU:   8 threads, 1.47kP/s ;    GPU:    8 threads, 1.30kP/s

CPU:   4 threads, 1.47kP/s ;    GPU:    4 threads, 1.43kP/s

CPU:   2 threads, 1.00kP/s ;    GPU:    2 threads, 1.38kP/s

CPU:   1 threads, 0.56kP/s ;    GPU:    1 threads, 1.20kP/s

**Comment by 3rdIteration** [comment]
Your laptop is probably throttling either your CPU or GPU, possibly both... That CPU performance looks extremely low on the laptop...

In terms of the other issues you were having earlier, there  is a driver issues with NVIDIA drivers 465 and above. https://github.com/3rdIteration/btcrecover/issues/176

**Comment by CryptoCoinLab** [comment]
I tried 461.92, 462.31 and 466.27, nothing changed.

**Comment by CryptoCoinLab** [comment]
**Run seedrecover.py on Laptop Computer:** 

It seems the results of seedrecover and btcrecover are very different.

**1.  4 Threads + 1 addr : 17.38 kP/s**
python seedrecover.py --tokenlist mnemonic.txt --no-dupchecks --enable-opencl  --addr-limit 1 --addrs 1XXXbitcoinaddress  --bip32-path m/44'/0'/0'/0 --dsw --wallet-type bip39 --language en --mnemonic-length 12 --no-eta --threads 4

Starting seedrecover 1.9.0-CryptoGuide, btcrecover 1.9.0-Cryptoguide on Python 3.9.1 64-bit, 21-bit unicodes, 64-bit ints
Using the 'en' wordlist.
OpenCL: Auto Selecting Best Platform
2021-05-06 08:47:37 : Phase 1/1: up to 12 mistakes, 12 of which can be an entirely different seed word.

OpenCL: Available Platforms
Platform 0 - Name NVIDIA CUDA, Vendor NVIDIA Corporation
Platform 1 - Name Intel(R) OpenCL HD Graphics, Vendor Intel(R) Corporation
Platform 2 - Name Intel(R) OpenCL, Vendor Intel(R) Corporation

OpenCL: Auto Selecting Best Platform
OpenCL: Using Platform: 0
OpenCL: Using Work Group Size:  51200

2021-05-06 08:47:37 : Using 4 worker threads
/ 1382400  elapsed: 0:01:19  rate:  17.38 kP/s

**2.  4 Threads + addressdb : 15.54 kP/s**

python seedrecover.py --tokenlist mnemonic.txt --no-dupchecks --enable-opencl  --addr-limit 1 --addressdb  btc_2021_2_5.db --bip32-path m/44'/0'/0'/0 --dsw --wallet-type bip39 --language en --mnemonic-length 12 --no-eta --threads 4

Starting seedrecover 1.9.0-CryptoGuide, btcrecover 1.9.0-Cryptoguide on Python 3.9.1 64-bit, 21-bit unicodes, 64-bit ints
Loading address database ...
Loaded 775210200 addresses from database ...
Using the 'en' wordlist.
OpenCL: Auto Selecting Best Platform
2021-05-06 08:51:48 : Phase 1/1: up to 12 mistakes, 12 of which can be an entirely different seed word.

OpenCL: Available Platforms
Platform 0 - Name NVIDIA CUDA, Vendor NVIDIA Corporation
Platform 1 - Name Intel(R) OpenCL HD Graphics, Vendor Intel(R) Corporation
Platform 2 - Name Intel(R) OpenCL, Vendor Intel(R) Corporation

OpenCL: Auto Selecting Best Platform
OpenCL: Using Platform: 0
OpenCL: Using Work Group Size:  51200

2021-05-06 08:51:48 : Using 4 worker threads
| 460800  elapsed: 0:00:29  rate:  15.54 kP/s

**Comment by CryptoCoinLab** [comment]
Run seedrecover on the miner rig with 8 AMD R470 VGA adapters:

2 threads:  10.1kP/s
8 threads:  33.5kP/s

So maybe the bottleknecks are not the GPU or CPU.

As for btcrecover.py,  there is still a lot of room for improvement.

**Comment by CryptoCoinLab** [comment]
Got it.   There is still a mather of AMD R470,  these days I installed AMD Rocm 4.1 driver on miner rig many times.

However,  clinfo in AMD Rocm 4.1 could not see any AMD R470 adapters.

It seems AMD Rocm 4.1 doesn't support AMD R470 ?

**Comment by 3rdIteration** [comment]
That will come down to which version of OpenCL these drivers support and
what version of OpenCL your build of PyOpenCL requires. I don't have any
AMD cards, so can't support or troubleshoot this platform.

**Comment by CryptoCoinLab** [comment]
Thank you very much for your work.   May I buy you a AMD RX470 card from Amazon.com  ?
btcrecover is a very nice tool to recover crypto-currencies wallets.    I hope btcrecover will get better.  
If it is ok, then send your address to my mailbox :   unshadowster#gmail.com.
