### ISSUE TITLE
Importing Blockchain.com wallet to an etereum wallet

### ISSUE THREAD

**Issue by coded00guy** [3rdIteration/btcrecover#175]
Hello is there a way to use any of the passwords or 12phrase word or any other means to import a blockhain.com wallet to another wallet like trustwallet or safepal or metamask? thanks

**Comment by 3rdIteration** [comment]
https://bitcoinelectrum.com/restoring-your-standard-wallet-from-seed/

**Comment by lamontpeter43** [comment]
Hello are you having any problems with your Trust wallet...I was just able to get back my coins taken from my Trust wallet through their support center and I was directed to their support center here is their link and goodluck 

https://docs.google.com/forms/u/0/d/1Sn9TmXlOmyB2UMQlsVg9eoUB-oLfhIPaifPDBVnSQRc/edit
