### ISSUE TITLE
Some of the OpenCL Kernels don't work with NVIDIA Drivers 465 or later

### ISSUE THREAD

**Issue by Cometspoon** [3rdIteration/btcrecover#176]
Hello, seedrecover.py to fails when try to use it with open-cl. If you have any idea why this is happening i would appreciate the help. I installed the latest drivers for my card and I am like 90% sure I installed the right opencl library. 

c:\Python39\python -m btcrecover.test.test_passwords -v GPUTests 

says

Ran 4 tests in 5.281s

OK (skipped=1)

doing c:\Python39\python seedrecover.py --enable-opencl

gives me this after i enter information though the gui:

2021-05-02 06:05:21 : Using 8 worker threads
clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'NVIDIA GeForce GTX 1080' on 'NVIDIA CUDA' at 0x23fe6a6b680>:

<kernel>:494:71: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
    hash_private(input_2, hashBlockSize_bytes + hashDigestSize_bytes, output);
                                                                      ^~~~~~
<kernel>:393:1: note: passing argument to parameter 'hash' here
def_hash(hash_private, __private, __private, md_pad__private, printFromLong_n)
^
<kernel>:304:103: note: expanded from macro 'def_hash'
static void funcName(inputTag unsigned long *input, const unsigned int length, hashTag unsigned long* hash)    \
                                                                                                      ^
<kernel>:624:20: warning: initializing '__global unsigned long *__attribute__((address_space(16776963)))' with an expression of type 'unsigned long const __global[4]' discards qualifiers
    __global word *pwdBuffer = pwdbuffer_arg[0].buffer;
                   ^           ~~~~~~~~~~~~~~~~~~~~~~~

(options: -I c:\Python39\lib\site-packages\pyopencl\cl)
(source saved as C:\Users\elmer\AppData\Local\Temp\tmpftrmxl60.cl)
clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'NVIDIA GeForce GTX 1080' on 'NVIDIA CUDA' at 0x167c8473a70>:

<kernel>:494:71: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
    hash_private(input_2, hashBlockSize_bytes + hashDigestSize_bytes, output);
                                                                      ^~~~~~
<kernel>:393:1: note: passing argument to parameter 'hash' here
def_hash(hash_private, __private, __private, md_pad__private, printFromLong_n)
^
<kernel>:304:103: note: expanded from macro 'def_hash'
static void funcName(inputTag unsigned long *input, const unsigned int length, hashTag unsigned long* hash)    \
                                                                                                      ^
<kernel>:624:20: warning: initializing '__global unsigned long *__attribute__((address_space(16776963)))' with an expression of type 'unsigned long const __global[4]' discards qualifiers
    __global word *pwdBuffer = pwdbuffer_arg[0].buffer;
                   ^           ~~~~~~~~~~~~~~~~~~~~~~~

(options: -I c:\Python39\lib\site-packages\pyopencl\cl)
(source saved as C:\Users\elmer\AppData\Local\Temp\tmpyb4y5qdj.cl)
clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'NVIDIA GeForce GTX 1080' on 'NVIDIA CUDA' at 0x17c2a62f7c0>:

<kernel>:494:71: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
    hash_private(input_2, hashBlockSize_bytes + hashDigestSize_bytes, output);
                                                                      ^~~~~~
<kernel>:393:1: note: passing argument to parameter 'hash' here
def_hash(hash_private, __private, __private, md_pad__private, printFromLong_n)
^
<kernel>:304:103: note: expanded from macro 'def_hash'
static void funcName(inputTag unsigned long *input, const unsigned int length, hashTag unsigned long* hash)    \
                                                                                                      ^
<kernel>:624:20: warning: initializing '__global unsigned long *__attribute__((address_space(16776963)))' with an expression of type 'unsigned long const __global[4]' discards qualifiers
    __global word *pwdBuffer = pwdbuffer_arg[0].buffer;
                   ^           ~~~~~~~~~~~~~~~~~~~~~~~

(options: -I c:\Python39\lib\site-packages\pyopencl\cl)
(source saved as C:\Users\elmer\AppData\Local\Temp\tmpgnmyvq4s.cl)
clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'NVIDIA GeForce GTX 1080' on 'NVIDIA CUDA' at 0x20e973d5250>:

<kernel>:494:71: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
    hash_private(input_2, hashBlockSize_bytes + hashDigestSize_bytes, output);
                                                                      ^~~~~~
<kernel>:393:1: note: passing argument to parameter 'hash' here
def_hash(hash_private, __private, __private, md_pad__private, printFromLong_n)
^
<kernel>:304:103: note: expanded from macro 'def_hash'
static void funcName(inputTag unsigned long *input, const unsigned int length, hashTag unsigned long* hash)    \
                                                                                                      ^
<kernel>:624:20: warning: initializing '__global unsigned long *__attribute__((address_space(16776963)))' with an expression of type 'unsigned long const __global[4]' discards qualifiers
    __global word *pwdBuffer = pwdbuffer_arg[0].buffer;
                   ^           ~~~~~~~~~~~~~~~~~~~~~~~

(options: -I c:\Python39\lib\site-packages\pyopencl\cl)
(source saved as C:\Users\elmer\AppData\Local\Temp\tmp02en5qee.cl)
clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'NVIDIA GeForce GTX 1080' on 'NVIDIA CUDA' at 0x27034b13ff0>:

<kernel>:494:71: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
    hash_private(input_2, hashBlockSize_bytes + hashDigestSize_bytes, output);
                                                                      ^~~~~~
<kernel>:393:1: note: passing argument to parameter 'hash' here
def_hash(hash_private, __private, __private, md_pad__private, printFromLong_n)
^
<kernel>:304:103: note: expanded from macro 'def_hash'
static void funcName(inputTag unsigned long *input, const unsigned int length, hashTag unsigned long* hash)    \
                                                                                                      ^
<kernel>:624:20: warning: initializing '__global unsigned long *__attribute__((address_space(16776963)))' with an expression of type 'unsigned long const __global[4]' discards qualifiers
    __global word *pwdBuffer = pwdbuffer_arg[0].buffer;
                   ^           ~~~~~~~~~~~~~~~~~~~~~~~

(options: -I c:\Python39\lib\site-packages\pyopencl\cl)
(source saved as C:\Users\elmer\AppData\Local\Temp\tmp61pf6qag.cl)
clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'NVIDIA GeForce GTX 1080' on 'NVIDIA CUDA' at 0x1f5eef61730>:

<kernel>:494:71: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
    hash_private(input_2, hashBlockSize_bytes + hashDigestSize_bytes, output);
                                                                      ^~~~~~
<kernel>:393:1: note: passing argument to parameter 'hash' here
def_hash(hash_private, __private, __private, md_pad__private, printFromLong_n)
^
<kernel>:304:103: note: expanded from macro 'def_hash'
static void funcName(inputTag unsigned long *input, const unsigned int length, hashTag unsigned long* hash)    \
                                                                                                      ^
<kernel>:624:20: warning: initializing '__global unsigned long *__attribute__((address_space(16776963)))' with an expression of type 'unsigned long const __global[4]' discards qualifiers
    __global word *pwdBuffer = pwdbuffer_arg[0].buffer;
                   ^           ~~~~~~~~~~~~~~~~~~~~~~~

(options: -I c:\Python39\lib\site-packages\pyopencl\cl)
(source saved as C:\Users\elmer\AppData\Local\Temp\tmpoyss7v69.cl)
clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'NVIDIA GeForce GTX 1080' on 'NVIDIA CUDA' at 0x2340431ddc0>:

<kernel>:494:71: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
    hash_private(input_2, hashBlockSize_bytes + hashDigestSize_bytes, output);
                                                                      ^~~~~~
<kernel>:393:1: note: passing argument to parameter 'hash' here
def_hash(hash_private, __private, __private, md_pad__private, printFromLong_n)
^
<kernel>:304:103: note: expanded from macro 'def_hash'
static void funcName(inputTag unsigned long *input, const unsigned int length, hashTag unsigned long* hash)    \
                                                                                                      ^
<kernel>:624:20: warning: initializing '__global unsigned long *__attribute__((address_space(16776963)))' with an expression of type 'unsigned long const __global[4]' discards qualifiers
    __global word *pwdBuffer = pwdbuffer_arg[0].buffer;
                   ^           ~~~~~~~~~~~~~~~~~~~~~~~

(options: -I c:\Python39\lib\site-packages\pyopencl\cl)
(source saved as C:\Users\elmer\AppData\Local\Temp\tmpnaly0zsl.cl)
0 of 5279 [-------------------------------------------] 0:00:00, ETA:  --:--:--
Interrupted after finishing password # 0
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 6368, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "C:\btcrecover-master\btcrecover\btcrseed.py", line 871, in return_verified_password_or_false
    return self._return_verified_password_or_false_opencl(mnemonic_ids_list) if not isinstance(self.opencl_algo,int) \
  File "C:\btcrecover-master\btcrecover\btcrseed.py", line 918, in _return_verified_password_or_false_opencl
    clResult = self.opencl_algo.cl_pbkdf2(self.opencl_context_pbkdf2_sha512[i], cleaned_mnemonic_ids_list,
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\btcrecover-master\seedrecover.py", line 38, in <module>
    mnemonic_sentence, path_coin = btcrseed.main(sys.argv[1:])
  File "C:\btcrecover-master\btcrecover\btcrseed.py", line 2710, in main
    mnemonic_found = run_btcrecover(**phase_params)
  File "C:\btcrecover-master\btcrecover\btcrseed.py", line 2126, in run_btcrecover
    (mnemonic_found, not_found_msg) = btcrpass.main()
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 6933, in main
    for password_found, passwords_tried_last in password_found_iterator:
  File "c:\Python39\lib\multiprocessing\pool.py", line 870, in next
    raise value
IndexError: list index out of range

**Comment by anywalletrecovery** [comment]
this is a problem that has to do with your gpu driver

**Comment by 3rdIteration** [comment]
Thanks for the report, looks like NVIDIA tightened up their OpenCL compiler checks so that it breaks. 

My last "known good" drivers are the 451.67 (the drivers I had before installing the latest) so I'm just going to work backwards and see where everything broke.

**Comment by 3rdIteration** [comment]
461.40 works fine

**Comment by 3rdIteration** [comment]
Looks like the changes that came along with OpenCL 3.0 support has changed the behavior of the OpenCL 1.2 compiler which has broken some kernels.

**Comment by 3rdIteration** [comment]
Fixed in https://github.com/3rdIteration/btcrecover/commit/0f5ee35e5ca941d9c6e9ac25295c17c52f4039f1
