### ISSUE TITLE
double SHA256 encryption of brainwallet

### ISSUE THREAD

**Issue by aznowak** [3rdIteration/btcrecover#177]
My brainwallet password has been encrypted twice into private key : SHA256(SHA256(brainwallet))
BTC Recover currently does 1 SHA-256 iteration for brainwallet. Can it do 2?

**Comment by anywalletrecovery** [comment]
try doing it through brainflayer

**Comment by 3rdIteration** [comment]
It can with minimal modification, is this something you just did yourself or something that was standard for a particular brainwallet implementation?

**Comment by aznowak** [comment]
Some tools offer multiple SHA hashing of the passphrase and I've used it in the past. I think, I've figured out that one line that must be added to btcrpass.py. Thanks.

**Comment by 3rdIteration** [comment]
If you can find a sample of such a tool (So as to be able to generate a wallet to test against) then let me know and I can add it in.

**Comment by 3rdIteration** [comment]
closed due to inactivity
