### ISSUE TITLE
Can't get GPU acceleration to work

### ISSUE THREAD

**Issue by luckyesquire** [3rdIteration/btcrecover#179]
Trying to get GPU acceleration installed for BTCrecover. I have Radeon 6900XT and two xfx r9 270x. I keep getting the following: "btcrecover.py: error: ambiguous option: --enable could match --enable-gpu, --enable-opencl"
I am a novice. Any help is appreciated.

**Comment by 3rdIteration** [comment]
Just try what the error message says and use either --enable-gpu or --enable-opencl
