### ISSUE TITLE
Implement GPU acceleration for BIP39 wallets

### ISSUE THREAD

**Issue by 3rdIteration** [3rdIteration/btcrecover#18]
Performance is currently about double the performance of CPU testing, if the following tasks are completed, performance will be about 7x based off my testing with seedlist and disabling the verification step. (Still worthwhile)

- [ ]  Create some test-vector passwordlists for benchmarking both BTCRecover and other tools, testing and tuning your setup
- [x]  Modify password generator to perform checksums internally so as to guarantee that chunks of seeds will always completely fill the work group. (This can have a significant impact on performance. If the max work group size is 1024, only filling half (512) or having one over the max (1025) both halve performance. This can be approximated based on the expected error detection rates for different wallet types, but this changes with seed length and wallet type... (Never mind the performance penalty of having to constantly under-fill the work group, to avoid the penalty of overfilling it)
- [ ]  Modify mult-threading behavior of password generation and seed testing... If used with a pre-checksummed password list and the seed checking step is disabled, you can actually max-out GPU usage with as little as 2 threads. (Hits about 7.2 Kp/s) Currently all the threads just run the same task, which is fine for CPU processing, but with OpenCL, it makes more sense to have a few different worker pools. (Some to generate the password chunks and and enqueue them for processing, some to pass data back-foward with OpenCL, some to take the hashed data, derive addresses and check them)

**Comment by 3rdIteration** [comment]
Fixing up GPU acceleration for Bitcoin core gives a 2000x speed boost, very worthwhile.

BIP39 involves far less rounds of hashing (2048 vs 60,000) so may not be as worthwhile, but still likely to be worth exploring. 

Hashcat looks to support the required

**Comment by 3rdIteration** [comment]
Have been playing around with Hashcat and the results are basically that while I tend to get about 20kp/s on an i7 laptop for CPU based processing, using the 1660ti in the laptop produces 154kp/s. So let's call it a 7x performance increase... Not bad... This basically brings my laptop up to the hashing power of a 48 core Linode... (That's pretty good, a single 1080ti or 2080ti would probably be able to manage double this)

It gets better...
For a BIP39 seed, the seed is only hashed after the checksum has been checked:
**For BIP39:** Seeds Hashed:  3323  Seeds Checksum Failed:  50285
**For Electrum:** Seeds Hashed:  411  Seeds Checksum Failed:  52031
(The more robust checksumming is why BTCRecover can hash Electrum seeds faster than BIP39 seeds...)

Depending on overheads, we could estimate that the real passwords/second rate will be about 10x that of the raw hash rate, leading to the GPU based hashing having an effective hash rate of 

Basically what this means is that the passwords-per-second you see isn't a true reflection of the hashrate between BTCRecover and Hashcat. (Hashcat tested every seed, BTCRecover hashed less than 10% of them, simply checksumming the rest)

Essentially that means that the GPU should perform somewhere in the ballpark of 2,250 kp/s. A performance increase of a factor of 100... That's worth while as it brings a "4 missing words" scenario down to something that can be solved within 90 days on my GPU, or within 45 days on a 1080Ti. (Less if you had multiple GPUs or an FPGA) This also means that you could descramble a scrambled BIP39 seed in under a minute...

Certainly worth pursuing further. 

**Output and code below:**

sha512:2048:bW5lbW9uaWM=:oLgKO+95J+tgAAtRBcv0FwbCFxTjA4djISQaqGtebA9DLBx2Yr69mGMySJbkq0S/QztF1af3lp8QLiww9to+HQ==:ocean hidden kidney famous rich season gloom husband spring convince attitude boy

Session..........: hashcat
Status...........: Cracked
Hash.Type........: PBKDF2-HMAC-SHA512
Hash.Target......: sha512:2048:bW5lbW9uaWM=:oLgKO+95J+tgAAtRBcv0FwbCFx...o+HQ==
Time.Started.....: Wed May 27 15:49:32 2020 (1 min, 42 secs)
Time.Estimated...: Wed May 27 15:51:14 2020 (0 secs)
Guess.Base.......: File (C:\Users\steve\Documents\GitHub\btcrecover\seeds.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:   154.1 kH/s (8.49ms) @ Accel:64 Loops:32 Thr:64 Vec:1
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 15817623/15817623 (100.00%)
Rejected.........: 0/15817623 (0.00%)
Restore.Point....: 15728640/15817623 (99.44%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:2016-2047
Candidates.#1....: ocean season rich gloom hidden attitude husband kidney famous spring boy convince -> ocean hidden kidney famous rich season gloom husband spring convince attitude boy
Hardware.Mon.#1..: Temp: 73c Util: 89% Core:1710MHz Mem:6000MHz Bus:16

Started: Wed May 27 15:49:25 2020
Stopped: Wed May 27 15:51:16 2020


Python code to reproduce this:
`
# For a given BIP39 seed produces files in the format (dictionary and hash) to be used in hashcat.
# This target hash file can then be used with a password dictionary of any length for benchmarking and debugging.
# (Hashcat will be the basis for implemeting the same GPU based hashing in to BTCRecover)
# Hashcat Command:
# hashcat64.exe -a 0 -m 12100 password.hash password.dict

import hashlib
import binascii
import base64

password = b"ocean hidden kidney famous rich season gloom husband spring convince attitude boy"
salt = b"mnemonic"
algo = "sha512"
iterations = 2048

print("Password:", password)
print("Salt:",salt)

pwdhash = hashlib.pbkdf2_hmac(algo, password, salt, iterations)

print("PwdHash:", binascii.hexlify(pwdhash))

salt_b64 = base64.b64encode(salt)

hashCatFormat = algo + ":" + str(iterations) + ":"+salt_b64.decode()+":"+base64.b64encode(pwdhash).decode()
f = open("password.hash", "a")
f.write(hashCatFormat+"\n")
f.close()

print("hashCatFormat:", hashCatFormat)

f = open("password.dict", "a")
f.write(password.decode()+"\n")
f.close()
`

**Comment by jonathancross** [comment]
If you need to test your code, this might be a fun way:
https://mobile.twitter.com/alistairmilne/status/1266037520715915267

**Comment by 3rdIteration** [comment]
Yes I saw that one, if I manage to get GPU performance anywhere near hashcat.(perhaps using PyPy to optimise the CPU side too) then you could brute force descramble a 12 word seed in under a minute in a single 1660ti... If you had multiple 1080ti's it would be brute-forced faster than you cold type it in...

**Comment by 3rdIteration** [comment]
After looking at a few different implementations (Hashcat, John the Ripper) I have just gone with opencl_brute, as it's already in Python and easy to work with. (As well as to add OpenCL support to other walelt types) Pushed it to a branch here: https://github.com/3rdIteration/btcrecover/tree/OpenCL-WIP (This branch should be considered alpha and unsupported)

In terms of BIP39 and Electrum, it is currently heavily CPU bound, but at least works for now. (Still gives a 50% performance improvement over my CPU) Will look at some ways to optimise this. (The pyopencl_brute library seems to give about 10x CPU performance, not the 100x of hashcat, but until it is sufficiently non-cpu bound to max out the current kernel, it isn't worth optimising on the opencl side)

BIP39 performance will never really be able to reach hashcat (or wallet file) levels of performance, as they are simply brute-forcing a short string (wallet extract) and looking for a similarly short string as the output. BIP39 brute-forcing is different in that going from seed -> address requires several additioal steps of single hashing, etc, that significantly slows things down. (This can be easily seen if running as one thread)

**Comment by 3rdIteration** [comment]
As an exercise in both benchmarking as well as adding ability to spread over multiple PC's the OpenCL branch now has better options to save checksummed seed lists, broken up across multiple files. The hope was that PyPy would give better performance for the generator step than cPython (as is often the case, with pypy being 5x faster) but surprisingly, pypy performance is actually worse than cypthon, the default python interpreter, negating much of the possible benefit of splitting this up. (The challenge here is that pyOpenCl is only available with cpython) There may be some changes that make the code more JIT friendly and optimizations in the generators generally. The real trick will be to benchmark the raw Python permutations iterator and see what the ceiling actually is in terms of performance. 

The thing that becomes really apparent when you make these files is that the seed generation step is a very, very significant bottlekneck. This is the major reason why the 24 word seeds see a much smaller boost in performance. For reference, my PC topped out at generating (and checksumming) 200,000 seeds per second, even without any hashing or checking. (Unsurprising that the GPU accelerated checking of 24 word seeds tops out a bit below this) On the flip side, feeding pre-checksummed seeds into BTCRecover brings this up to 4-5 times the performance of processing on CPU. (And may still be useful to spread these workloads across multiple devices, or to pre-checksum seeds and do the checking on rented GPU power)

Will be briefly turning attention to using the OpenCL library to add GPU support to blockchain.com wallet recovery for a bit, as this should be very straight foward to add. (And is recovering blockchain.com passwords is a large proportion of BTCRecover users)

**Comment by mtad2002** [comment]
> As an exercise in both benchmarking as well as adding ability to spread over multiple PC's the OpenCL branch now has better options to save checksummed seed lists, broken up across multiple files. The hope was that PyPy would give better performance for the generator step than cPython (as is often the case, with pypy being 5x faster) but surprisingly, pypy performance is actually worse than cypthon, the default python interpreter, negating much of the possible benefit of splitting this up. (The challenge here is that pyOpenCl is only available with cpython) There may be some changes that make the code more JIT friendly and optimizations in the generators generally. The real trick will be to benchmark the raw Python permutations iterator and see what the ceiling actually is in terms of performance.
> 
> The thing that becomes really apparent when you make these files is that the seed generation step is a very, very significant bottlekneck. This is the major reason why the 24 word seeds see a much smaller boost in performance. For reference, my PC topped out at generating (and checksumming) 200,000 seeds per second, even without any hashing or checking. (Unsurprising that the GPU accelerated checking of 24 word seeds tops out a bit below this) On the flip side, feeding pre-checksummed seeds into BTCRecover brings this up to 4-5 times the performance of processing on CPU. (And may still be useful to spread these workloads across multiple devices, or to pre-checksum seeds and do the checking on rented GPU power)
> 
> Will be briefly turning attention to using the OpenCL library to add GPU support to blockchain.com wallet recovery for a bit, as this should be very straight foward to add. (And is recovering blockchain.com passwords is a large proportion of BTCRecover users)

I didn't realize the final solution exactly, is it possible to use GPU power to generate checksummed seed lists and again using GPU power to generate address from that list and compare it to deposit address?

**Comment by avsync** [comment]
I'm getting "Error: Wallet Type: NoneType does not support GPU acceleration" when I try to use the --enable-opencl flag for btcrecover on a bip39 passphrase. Is only seedrecover working with opencl at the moment or have I messed up a flag somewhere?

python3 btcrecover.py --dsw --no-dupchecks --bip39 --passwordlist passwords.txt --addrs bc1qxxxxxxxxxxxxxxxxx --addr-limit 1 --bip32-path "m/84'/0'/0'/0" --enable-opencl

Starting btcrecover 1.2.0-Cryptoguide on Python 3.8.3 64-bit, 21-bit unicodes, 64-bit ints

OpenCL: Available Platforms
Platform 0 - Name NVIDIA CUDA, Vendor NVIDIA Corporation

Error: NoneType does not support GPU acceleration

**Comment by 3rdIteration** [comment]
Ah yes, doesn't work for BIP39 passphrase, only BIP39 seeds. Will fix up the error message accordingly.

**Comment by 3rdIteration** [comment]
> > As an exercise in both benchmarking as well as adding ability to spread over multiple PC's the OpenCL branch now has better options to save checksummed seed lists, broken up across multiple files. The hope was that PyPy would give better performance for the generator step than cPython (as is often the case, with pypy being 5x faster) but surprisingly, pypy performance is actually worse than cypthon, the default python interpreter, negating much of the possible benefit of splitting this up. (The challenge here is that pyOpenCl is only available with cpython) There may be some changes that make the code more JIT friendly and optimizations in the generators generally. The real trick will be to benchmark the raw Python permutations iterator and see what the ceiling actually is in terms of performance.
> > The thing that becomes really apparent when you make these files is that the seed generation step is a very, very significant bottlekneck. This is the major reason why the 24 word seeds see a much smaller boost in performance. For reference, my PC topped out at generating (and checksumming) 200,000 seeds per second, even without any hashing or checking. (Unsurprising that the GPU accelerated checking of 24 word seeds tops out a bit below this) On the flip side, feeding pre-checksummed seeds into BTCRecover brings this up to 4-5 times the performance of processing on CPU. (And may still be useful to spread these workloads across multiple devices, or to pre-checksum seeds and do the checking on rented GPU power)
> > Will be briefly turning attention to using the OpenCL library to add GPU support to blockchain.com wallet recovery for a bit, as this should be very straight foward to add. (And is recovering blockchain.com passwords is a large proportion of BTCRecover users)
> 
> I didn't realize the final solution exactly, is it possible to use GPU power for BIP39 seedrecover.py to generate checksummed seed lists and again using GPU power to generate address from that list and compare it to deposit address?

Someone could do this but it would basically involve starting from scratch and re-writing the entire tool entirely for OpenCL. This would also mean having to re-write lots of functionality from scratch that is currently provided by the built-in python libraries. 

One of the advantages of this tool as it currently exists is that written in Python, so it's cross platform, easy to expand and maintain, while also being fast enough for most simple seed recovery tasks. (Typos, a couple of missing words, etc) The biggest challenge with all of this is that with BIP39 seeds, you are dealing with exponential increases in complexity for every missing word, so even though HashCat might be 10x faster again, it's only barely fast enough to recover 4 missing words, with known location, in a reasonable timespan. (As opposed to the current limit of having 3 missing, with known location) If if someone were to invent an ASIC to do this (As happened with Bitcoin mining) it would still only move the bar for what is brute-force recoverable a relatively small amount.

**Comment by 3rdIteration** [comment]
So this will be handy https://medium.com/@johncantrell97/how-i-checked-over-1-trillion-mnemonics-in-30-hours-to-win-a-bitcoin-635fe051a752

**Comment by johncantrell97** [comment]
FYI -- it can easily be extended to iterate through standard recovery derivation paths so it won't require knowing them in advance.

**Comment by 3rdIteration** [comment]
Just going to close this one for now, as I merged the existing OpenCL stuff. It doesn't give a huge boost for BIP39, but could still be useful as-is. (Particularly for blockchain.com wallet users)

Tasks relating to improving the OpenCL performance will be tracked here: https://github.com/3rdIteration/btcrecover/issues/43
