### ISSUE TITLE
keepkey recovery with change address

### ISSUE THREAD

**Issue by Cometspoon** [3rdIteration/btcrecover#182]
I am trying to recover a keepkey 12 word passphrase.  I had assumed in my initial attempts that change addresses were generated in the same way as receiving addresses, but I have found by testing that I can recover seed phrases with receiving addresses but not change addresses. 

Is there a way to use change addresses in this search? The only address I currently have identified from the wallet is a change address. It is possible I can find a receiving address by messing around in a block explorer, but I am not sure about that.

**Comment by Cometspoon** [comment]
I messed around in a block explorer and I found 3 transactions of which I am pretty sure at least one of them was generated as a receiving address so I am trying my initial searches again with a address database of those 3 addresses. This does seem like weird behavior though so I will leave this open. Feel free to close it if you don't find it interesting.

**Comment by 3rdIteration** [comment]
You can go in to the derivation pathlists file for the crypto and change the last number from a 0 to a 1, this will then look at change addresses.

If you are even slightly unsure of the address, just use an AddressDB instead, there is no performance penalty.

**Comment by Cometspoon** [comment]
I tested using 

--bip32-path m/44'/0'/0'/1

With a change address and it didn't find my slightly mangled test phrase, so I also tried this with an address db containing change and receiving addresses: 

--bip32-path m/44'/0'/0'/0 m/44'/0'/0'/1

Which also didn't work. Just running seedrecover the db containing both and without the path command did find my test phrase. So I must be missing something about how paths work.

**Comment by 3rdIteration** [comment]
Did you try and just edit the derivation path list file for BTC?

Are you trying to recover a legacy address? (based on that derivation path)

**Comment by 3rdIteration** [comment]
Have you read this
https://btcrecover.readthedocs.io/en/latest/bip39-accounts-and-altcoins/

**Comment by Cometspoon** [comment]
I tested it this way:

c:\Python39\python seedrecover.py --bip32-path m/44'/0'/0'/0 m/44'/0'/0'/1 --addressdb testadd.db

I have not read that article. I will do that.

**Comment by Cometspoon** [comment]
Oh i just realized my test addresses start with a 3 and the real addresses I was looking for start with a 1

**Comment by Cometspoon** [comment]
OK, I think I know what's going on. Thanks for the help.
