### ISSUE TITLE
Slow on new GPU?

### ISSUE THREAD

**Issue by MacTheZazou** [3rdIteration/btcrecover#184]
I tried a lot of new GPU with different OpenCL version on vast.ai and it seem's like nothing beat the 2080 TI?

A TFLOPS x2 never equals kps x2 even on single GPU machine, most of the time I only get something between 0.8x to 1.3x with a 2x powerful GPU on a bitcoincore  SHA-512 encrypted Wallet 

Is there a bottleneck somewhere? I tried to tweak the global-ws and local-ws a lot, but it doesn't change anything...

**Comment by shipsource** [comment]
Hey, is 2080 TI performing the best for you? Did you try 2080S?

**Comment by 3rdIteration** [comment]
If you are doing a bitcoin core recovery you should use the JTR kernel via --enable-gpu

The single threaded CPU performance of the system matters a lot too, if it is too slow you will quickly hit CPU bottleknecks.

**Comment by byGits** [comment]
> If you are doing a bitcoin core recovery you should use the JTR kernel via --enable-gpu
> 
> The single threaded CPU performance of the system matters a lot too, if it is too slow you will quickly hit CPU bottleknecks.

Hey, Thanks for the fork and improvements you've done to btcrecover.

Is there any reason for --enable-gpu not supporting extracts from blockchain.com (second pass)? or it is just not supported yet and might be in the future?

**Comment by 3rdIteration** [comment]
Yes, basically the OpenCL kernel that is used in --enable-gpu is designed
around Bitcoin Core wallets.

Just use --enable-opencl for blockchain.com wallets, it uses the more
flexible opencl_brute kernels which give a large performance improvement
over CPU and also lend themselves to scaling better across multiple GPUs
than the current implementation. Works fine for both main pass and second
pass. See here:
https://btcrecover.readthedocs.io/en/latest/Usage_Examples/2020-10-06_Multi-GPU_with_vastai/Example_Multi-GPU_with_vastai/

**Comment by MacTheZazou** [comment]
Thank you for your answer! I think the probem is probably CPU bottleneck, because there is not much difference between a 2080 Ti and a 3090 (1.2x - 1.4x)... I'm using this command: python btcrecover.py --data-extract-string *** --tokenlist *** --global-ws 524288 --local-ws 256 --no-eta

**Comment by bttfw** [comment]
> Thank you for your answer! I think the probem is probably CPU bottleneck, because there is not much difference between a 2080 Ti and a 3090 (1.2x)... I'm using this command: python btcrecover.py --data-extract-string *** --tokenlist *** --global-ws 524288 --local-ws 256 --no-eta

You are not using gpu or open cl

**Comment by MacTheZazou** [comment]
Yes I'am ^^ my command is wrong

**Comment by bttfw** [comment]
> Yes I'am ^^ my command is wrong

Thats what I was saying
