### ISSUE TITLE
When using run-all-tests I get an Assertion error

### ISSUE THREAD

**Issue by bmahaley** [3rdIteration/btcrecover#186]
At the end of the test results in cmd.  It says AssertionError: group argument must be none for now.  Is this an issue and if so what is the fix?

**Comment by 3rdIteration** [comment]
So are what is the test command you are running, is it just something like

`python run-all-test.py`

**Comment by bmahaley** [comment]
I'm using py run-all-tests.py and I'm getting an assertion error.  Is this an issue?  I ran the program using the seedrecover program and adding the seed phrases I have.  The program ran for about 15 hours and at the end everything just vanished.  no indication as to what result was obtained or anything.  While the program was running it said that I had two errors in the seed phrase and that one of them was an entirely different word.
