### ISSUE TITLE
Tryin to get btcrecover to access the database. 

### ISSUE THREAD

**Issue by bmahaley** [3rdIteration/btcrecover#187]
I pulled the litecoin db off the repository. cmd is saying "no block file exists in block directory".

**Comment by 3rdIteration** [comment]
So are you saying that you downloaded the pre-made addressDBs that I provide (including one for LTC) or that you downloaded a bootstrap sort of thing that contains all the block files for a full litecoin node?

**Comment by bmahaley** [comment]
Yes.  Having trouble getting the program to access the database file.  I'm getting an error in cmd.

**Comment by 3rdIteration** [comment]
You didn't answer the question... So have you downloaded a ready made addressDB that is provided in the docco or did you download a bootstrap file or something that contains the raw blocks that you would use with a normal litecoin node?

If you download the pre-made addressDBs that I provide, you don't need to use create-address-db at all...

**Comment by bmahaley** [comment]
What is the correct process to get the program to check through the database?
  
  
  
    
  

  
  
>

**Comment by bmahaley** [comment]
I did use a premade database file.  I thought I was able to use it in the program but received an error message.  how can I get the program to check through the addresses?  Have I done enough to make the program function?

**Comment by 3rdIteration** [comment]
So have you watched this: https://www.youtube.com/watch?v=6vw2x053LW4

It's a bit of an older video now, but the process for using an AddressDB is the same.

**Comment by bmahaley** [comment]
I used the command py seedrecover.py  --no-dupchecks --addr-limit 1 --bip32-path "m/44'/2'/0'/0" --big-typos 1.  I cancelled when it asked me for the public key and it immediately said the following:

notice: address database file 'addresses.db' does not exist in current directory
canceled

**Comment by 3rdIteration** [comment]
The error means what it says, if you are not using the --addressdb argument
to just point it to the addressdb then you will need to rename the premade
addressdb file to that end put it in the BTCRecover folder.

**Comment by bmahaley** [comment]
Okay.  I got the program to run but the result was "no seed found"  I am using a 24 word seed phrase and I am checking Litecoin.  Do I need to change the derivation path?  Is there something else I am missing?

**Comment by bmahaley** [comment]
There were over 64 million addresses. My device only stores 4G.  Could there be a storage issue?

**Comment by bmahaley** [comment]
Mission successful!  Thank you so much for your help and God Bless.

**Comment by 3rdIteration** [comment]
If you managed to recover your funds, feel free to send a tip to any of the
donation addresses :)
