### ISSUE TITLE
SeedRecover Seed Words Missing (2 words or more, possible different order, possible typos, ...) + Passphrase (25th word)

### ISSUE THREAD

**Issue by ChezThomas** [3rdIteration/btcrecover#188]
Hi, 
first of all thanks for this amazing tool! 

I am Still trying to figure out my missing / incorrect seed words from my ETH Trezor address over the last 10days.
I tried the obvious things and replaced my missing 2 words with an X, without success.
So I am trying to go for the next most logical thing, which would be to try:

1. from this list: https://wiki.trezor.io/Commonly_misspelled_recovery_seed_words to create another list to try every similar words from my existing seeds and try to replace them with one of each and do it for every single combination 
(For ex, if one of my words is "able" I would like it to try "cable + table" too, and do the same for any very similar words from my list).

2. Still keeping my 2 missing words with the "x", I am thinking that some of my word position around the missing one may not be at their correct position, for that reason, would there be any way to try every possible position for all words ?
(For ex, if my words are "able, x, beach, base, ..." to try "x, able, beach, base + x, beach, able, base, ... + and so on...)

Hope I am making myself clear enough for someone kind enough to help me on this.
A reward will be sent to everyone who helps contribute once my key is successfully retrieved.

**Comment by 3rdIteration** [comment]
If you are only missing two words then it isn't worth specifying the position at all.

**Comment by ChezThomas** [comment]
Thanks for taking the time answering me ;-)
So as for the two missing words, That’s what I thought but since I tried every possible options in a case of two missing words, and getting the “no seed words found, sorry…” 
I have to conclude that the problem is more complicated and that I probably either typed another word wrongly, or that some word positions could be mis ordered

I also could confirm that the address I am using is the correct one.

What would be the next logical thing to try?

Thanks again for your help!!!

Le 30 mai 2021 à 01:26, 3rd Iteration ***@***.***> a écrit :

﻿
If you are only missing two words then it isn't worth specifying the position at all.

**Comment by coded00guy** [comment]
If you are not 100% that the address is the correct one you can scan on etherscan and confirm the value in relation to the coins you hold. 
After that if you are sure the scrambled phrases you have are also the correct one and you have some errors. You should as requested earlier: 
- type the phrases as seen (with the orders as it is) then specify the "--mnemonic-length 12" command then in this case try including "--big-typos 4" but i think the mnemonic phrase command tests upto 4 big typos so u can increase big typos to 5. 

Hope it helps

**Comment by ChezThomas** [comment]
Thanks for your reply and help.
So in my case it since its for a Trezor / Ethereum wallet, It would be:
"python3 seedrecover.py —mnemonic-length 24 —big-typos 4” ? (I am afraid it will take months with my computer speed)

Also is there any way of anticipating the time it would take to complete based on the computer I am doing it ?
As for exemple, I am still running a “—big-typos 2 —typos 6 —enable-opencl” for the last 2 days, and right now at 150.000.000.000, and no idea when it will end.
Would be great to have some kind of time estimation.

Thanks again !

**Comment by ChezThomas** [comment]
Also, the search is ongoing now but I got an error message when the command was sent:

2021-05-30 23:43:27.989 Python[87569:6309734] Warning: Expected min height of view: (<NSButton: 0x7f960a27db20>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.

Is it something to worry about ? 

Thanks!

**Comment by 3rdIteration** [comment]
Are you absolutely sure that you didn't use a BIP39 passphrase?

**Comment by ChezThomas** [comment]
> Are you absolutely sure that you didn't use a BIP39 passphrase?
> […](#)

Since our last transaction was 3 years ago, I honestly didn't remember much and was convinced I didn't. But using some backup recovery tool, and while going through Trezor website to recover some wallet, I did remember and found a 25th word :-) 
meaning now I have:
- our eth address
- 22 words out of 24
- Passphrase (Trezor additional 25th "word")

I tried creating a common_passwordlist.txt with my passphrase guesses.
and tried inputing as follow:

python3 btcrecover.py --wallet-type ethereum --addrs 0xcXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --addr-limit 5 --passwordlist /Users/XXXX/Desktop/btcrecover-master\ 3rd\ Iteration/common_passwordlist.txt --mnemonic-length 24 “1 X 3 4 5 6 7 8 9 10 X 12 13 14 15 16 17 18 19 20 21 22 23 24”

What am I missing as it doesn't work as it is.

Thanks a bunch in advance for whoever will be able to spare some time helping me!

**Comment by 3rdIteration** [comment]
If you have a passphrase then you should just use seedrecover.py, same as
before, just with a --passphrase argument. (or passphrase-list argument if
it could be one of a few possible guesses)

**Comment by ChezThomas** [comment]
Does it mean that in my case (noob filter on) It should be then:

python3 seedrecover.py --passphrase-list /Users/XXXX/Desktop/btcrecover-master\ 3rd\ Iteration/common_passwordlist.txt

In my .txt it is as follows
Passphraseguess1
Passphraseguess2
Passphraseguess3
…


- then input my eth address when prompted
- input my known seed words (with X when unknown) as follow “1 X 3 4 5 6 7 8 9 10 X 12 13 14 15 16 17 18 19 20 21 22 23 24” or “1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22” ? 

Thanks again !

**Comment by 3rdIteration** [comment]
That's right :)

**Comment by 3rdIteration** [comment]
Closed due to inactivity
