### ISSUE TITLE
pip3 install -r requirements.txt  error

### ISSUE THREAD

**Issue by yichuang-zh** [3rdIteration/btcrecover#189]
***@debian:~/btcrecover-master$ pip3 install -r requirements.txt 
Collecting coincurve~=15.0.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/65/31/9f13921cc7ca27059af4def1a9d1277a6a252dea967b62f9ea05cc2a4115/coincurve-15.0.0.tar.gz (219kB)
    100% |████████████████████████████████| 225kB 315kB/s 
  Installing build dependencies ... done
Collecting green~=3.2.5 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/e9/08/9909f05b593a6cec2b7c23ac4d11c54360e22e78d1dd429e4c4154086f87/green-3.2.6.tar.gz (72kB)
    100% |████████████████████████████████| 81kB 275kB/s 
Collecting pycryptodome~=3.9.9 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/aa/36/f97c4b16619618e169b9e0d687eab78868c7474ff8c1ec6f584a8b10b29b/pycryptodome-3.9.9-cp37-cp37m-manylinux1_x86_64.whl (13.7MB)
    100% |████████████████████████████████| 13.7MB 59kB/s 
Requirement already satisfied: asn1crypto in /usr/lib/python3/dist-packages (from coincurve~=15.0.0->-r requirements.txt (line 1)) (0.24.0)
Collecting cffi>=1.3.0 (from coincurve~=15.0.0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/97/2d/cd29c79f2eb1384577d0662f23c89d29621152f14bef8c6b25747785744b/cffi-1.14.5-cp37-cp37m-manylinux1_x86_64.whl
Collecting colorama (from green~=3.2.5->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Collecting coverage (from green~=3.2.5->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/4e/37/542ba59cd801d82605d94130b3bf5c659d2449bee89556328333bcbdb6e8/coverage-5.5-cp37-cp37m-manylinux1_x86_64.whl (242kB)
    100% |████████████████████████████████| 245kB 117kB/s 
Collecting lxml (from green~=3.2.5->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/cf/4d/6537313bf58fe22b508f08cf3eb86b29b6f9edf68e00454224539421073b/lxml-4.6.3-cp37-cp37m-manylinux1_x86_64.whl (5.5MB)
    100% |████████████████████████████████| 5.5MB 76kB/s 
Collecting unidecode (from green~=3.2.5->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/9e/25/723487ca2a52ebcee88a34d7d1f5a4b80b793f179ee0f62d5371938dfa01/Unidecode-1.2.0-py2.py3-none-any.whl (241kB)
    100% |████████████████████████████████| 245kB 131kB/s 
Collecting pycparser (from cffi>=1.3.0->coincurve~=15.0.0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Building wheels for collected packages: coincurve, green
  Running setup.py bdist_wheel for coincurve ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-iqrydo97/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-h2s7457f --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/coincurve
  copying coincurve/types.py -> build/lib.linux-x86_64-3.7/coincurve
  copying coincurve/flags.py -> build/lib.linux-x86_64-3.7/coincurve
  copying coincurve/__init__.py -> build/lib.linux-x86_64-3.7/coincurve
  copying coincurve/ecdsa.py -> build/lib.linux-x86_64-3.7/coincurve
  copying coincurve/utils.py -> build/lib.linux-x86_64-3.7/coincurve
  copying coincurve/context.py -> build/lib.linux-x86_64-3.7/coincurve
  copying coincurve/_windows_libsecp256k1.py -> build/lib.linux-x86_64-3.7/coincurve
  copying coincurve/keys.py -> build/lib.linux-x86_64-3.7/coincurve
  copying coincurve/py.typed -> build/lib.linux-x86_64-3.7/coincurve
  running build_clib
  /tmp/pip-install-iqrydo97/coincurve/libsecp256k1/autogen.sh: 3: /tmp/pip-install-iqrydo97/coincurve/libsecp256k1/autogen.sh: autoreconf: not found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-iqrydo97/coincurve/setup.py", line 309, in <module>
      **setup_kwargs
    File "/tmp/pip-build-env-9nqdh39p/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-iqrydo97/coincurve/setup.py", line 95, in run
      _bdist_wheel.run(self)
    File "/tmp/pip-build-env-9nqdh39p/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-iqrydo97/coincurve/setup.py", line 152, in run
      subprocess.check_call([autogen], cwd=absolute('libsecp256k1'))
    File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/tmp/pip-install-iqrydo97/coincurve/libsecp256k1/autogen.sh']' returned non-zero exit status 127.
  
  ----------------------------------------
  Failed building wheel for coincurve
  Running setup.py clean for coincurve
  Running setup.py bdist_wheel for green ... done
  Stored in directory: /home/peter/.cache/pip/wheels/d9/6a/13/4285d0236ed359aaf61b520ff244ff44097745879d9156f2b7
Successfully built green
Failed to build coincurve
Installing collected packages: pycparser, cffi, coincurve, colorama, coverage, lxml, unidecode, green, pycryptodome
  Running setup.py install for coincurve ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-iqrydo97/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-upin6lu4/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/coincurve
    copying coincurve/types.py -> build/lib.linux-x86_64-3.7/coincurve
    copying coincurve/flags.py -> build/lib.linux-x86_64-3.7/coincurve
    copying coincurve/__init__.py -> build/lib.linux-x86_64-3.7/coincurve
    copying coincurve/ecdsa.py -> build/lib.linux-x86_64-3.7/coincurve
    copying coincurve/utils.py -> build/lib.linux-x86_64-3.7/coincurve
    copying coincurve/context.py -> build/lib.linux-x86_64-3.7/coincurve
    copying coincurve/_windows_libsecp256k1.py -> build/lib.linux-x86_64-3.7/coincurve
    copying coincurve/keys.py -> build/lib.linux-x86_64-3.7/coincurve
    copying coincurve/py.typed -> build/lib.linux-x86_64-3.7/coincurve
    running build_clib
    /tmp/pip-install-iqrydo97/coincurve/libsecp256k1/autogen.sh: 3: /tmp/pip-install-iqrydo97/coincurve/libsecp256k1/autogen.sh: autoreconf: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-iqrydo97/coincurve/setup.py", line 309, in <module>
        **setup_kwargs
      File "/tmp/pip-build-env-9nqdh39p/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-9nqdh39p/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-iqrydo97/coincurve/setup.py", line 152, in run
        subprocess.check_call([autogen], cwd=absolute('libsecp256k1'))
      File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-install-iqrydo97/coincurve/libsecp256k1/autogen.sh']' returned non-zero exit status 127.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-iqrydo97/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-upin6lu4/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-iqrydo97/coincurve/

---------------------------------
My os:
Debian 10.9 + gnome

**Comment by 3rdIteration** [comment]
Troubleshooting building the coincurve module in Debian is beyond the scope of what I have time to test and support. Your best bet is to ask the coincurve maintainers.
