### ISSUE TITLE
Update extract scripts to python3

### ISSUE THREAD

**Issue by 3rdIteration** [3rdIteration/btcrecover#19]

**Comment by 3rdIteration** [comment]
Blockchain.com wallet extract scripts and functionality now updated and working. 

Added an updated V3 wallet, though it doesn't seem possible to create a wallet with a 2nd password anymore. (Or to add/change a 2nd password to an existing one)

**Comment by 3rdIteration** [comment]
Removed all armory scripts and content

**Comment by 3rdIteration** [comment]
Updated Bitcoin Core scripts

**Comment by 3rdIteration** [comment]
remaining scripts updated

**Comment by solardiz** [comment]
What minimum version of Python 3 are you targeting? It appears that `download-blockchain-wallet.py` now fails with Python 3.4 on this line:

```python
    return json.load(do_request(query, body))
```

with:

```
TypeError: the JSON object must be str, not 'bytes'
```

which apparently means it depends on this Python 3.6 feature: https://docs.python.org/3/whatsnew/3.6.html#json

Would you consider supporting a wider range of Python 3 versions, not just 3.6+?

**Comment by 3rdIteration** [comment]
3.6

**Comment by 3rdIteration** [comment]
Basically 3.5 goes EOL in a few months, so at this point I'm focusing on new features for current versions of python rather than adding support to older versions of Py3. (Especially since debian has been bundling these versions for over a year)

Is there a particular environment you are running on that is stuck on an old python3 environment?

**Comment by 3rdIteration** [comment]
Also should add that I'm happy to merge any PR that makes older versions work as long as the Travis CI checks all pass. (Travis checks python 3.6 to 3.8 on Linux, Mac and Windows)

**Comment by solardiz** [comment]
Thank you for your answers.

> Is there a particular environment you are running on that is stuck on an old python3 environment?

I'm often on various older distros, where installing fresh Python is an extra step. Anyway, turns out [for RHEL/CentOS 7 there's Python 3.6 in Software Collections now](https://developers.redhat.com/blog/2018/08/13/install-python3-rhel/) (IIRC, it was only 3.3 before) - not part of the distro and needing `scl enable rh-python36 bash` for each use, but I can live with that. So I suppose this dependency isn't that bad anymore.

**Comment by solardiz** [comment]
I suggest that you state the Python version assumption in the top-level README, e.g.:

```
The scripts found in this repository are meant to work with Python 3.6 and above. Some _might_ also work with older Python versions, but some others are known not to.
```

I guess this would save people time.

**Comment by jonathancross** [comment]
@solardiz you can submit a PR ;-)

**Comment by solardiz** [comment]
I notice relevant documentation changes are already being made now, thanks! I also found I had totally missed the "Bump required Python version to 3.6" commit from a few days ago, which literally answered my question here.

**Comment by sigkill** [comment]
> Thank you for your answers.
> 
> > Is there a particular environment you are running on that is stuck on an old python3 environment?
> 
> I'm often on various older distros, where installing fresh Python is an extra step. Anyway, turns out [for RHEL/CentOS 7 there's Python 3.6 in Software Collections now](https://developers.redhat.com/blog/2018/08/13/install-python3-rhel/) (IIRC, it was only 3.3 before) - not part of the distro and needing `scl enable rh-python36 bash` for each use, but I can live with that. So I suppose this dependency isn't that bad anymore.

Sorry for replying to an old issue - did you have or notice any issue with Centos / Python 3 not updating the status while running btcrecover?

**Comment by solardiz** [comment]
On Sun, Aug 08, 2021 at 03:40:09PM -0700, sigkill wrote:
> Sorry for replying to an old issue - did you have or notice any issue with Centos / Python 3 not updating the status while running btcrecover?

No, I don't recall seeing such issue.
