### ISSUE TITLE
Potential easy way to figure out OpenCL worker size

### ISSUE THREAD

**Issue by kernkraft235** [3rdIteration/btcrecover#190]
The instructions basically say guess and check, but after some research and testing I discovered

- Several docs say set local worker size to max possible
- I figured global multiplier had to be a meaningful number so i started using different numbers from the technical specs like SM count ROP count, Tensor count
-  My RTX 2070S gets best performance at local=256 (max possible size) x #of Tensor cores (320). This is a massive size, but btcrecover performance test shows 17 kps and I now have 100% GPU utilization ( I didnt before)

In Windows I was getting ~8kps with 10240/256 and in linux with same values I got 13kpa
Changing global to (Tensor cores x max worker size) got me to 17kps

Other people should test, im not sure if its specific to my card, RTX cards, or all nvidia

**Comment by JBoekhout** [comment]
Good to see this, i was working on a iterator closing in on optima. Whatd you say works for expansion to x# gpus?

**Comment by kernkraft88** [comment]
I honestly have no clue. I was just trying to find some correlation to a number. This problem should be solvable. I was thinking of local vs global sizes in the sense that gpus are ultra parallel cpus and the local is 1 "core" and global is "all the cores" so thats why I started plugging in numbers from specs..

Also my initial data was flawed,. i was testing 2 different wallets with 2 different difficulties. There were still gains, but only like 300 passwords/second.

**Comment by JBoekhout** [comment]
the 4gb thing.. Hm
real lack of internet discourse on this topic. Still wondering what to do with SLI gddr allocation related to global ws.


Update: 4 rtx 3090s  digitally rented go 16kp/s  and local-ws doesnt go above 256 soo.. wat right

**Comment by JBoekhout** [comment]
Think I'm gonna take up a math for this & farm some btc donations

**Comment by kernkraft88** [comment]
That's weird, I was thinking that local ws was the channel width. My 2070S has 256 bit bus and that's its max worker size. The 3090 has a 384 bit bus. 
I have no clue how GPU topology works, theres SMs, ROPs, Tensor cores, etc. I don't know if they all go by the 256 but bus or not, and does the topology change between generations with the drivers/CUDA/OpenCL just being the translation layer.

For the sake of comparison we should normalize difficulty/iterations to what hashcat benchmark uses which is ~200K.
My kpws is 8.3 @ 141K so normalized lets say 5.85 kwps. I read that wallet difficulty is a function of CPU power that it's created on for bitcoin core

**Comment by JBoekhout** [comment]
The 256 local-ws limit is held by btcrecover when doing btc core hashing, (jtr-kernel or so, the first one covered in gpu docs.). Some openCL set compute limit I dig. A stackoverflow from 2011 sets the opencl parameter standard at near randomly performing ok, not attesting to any maximization just getting at dye geometries working out for certain kernel ops, which has me return to a performance benchmark iteration.

Now to hook into the woods of this library, my ~first coding at scale ;]

**Comment by JBoekhout** [comment]
stackoverflow thread: https://stackoverflow.com/questions/15912668/ideal-global-local-work-group-sizes-opencl *2013
