### ISSUE TITLE
Using Address database for Ethereum wallets. 

### ISSUE THREAD

**Issue by coded00guy** [3rdIteration/btcrecover#191]
I tried recovering a wallet without its eth address. A BIP39 wallet to be precise. I used the premade list for eth wallets but it seems the list isn't up-to-date. Is there a way i can get an updated list or a way i can create one by myself? For strictly ETH addresses. 

Also. Since a trustwallet or safepal wallet usually comes with coins like BTC, will it be valid if i test the phrases against a btc address list instead? 

Thanks

**Comment by coded00guy** [comment]
Okay i got your solution from one of the closed issues. Now i have a .txt eth address how can i make it into a .db file?

**Comment by 3rdIteration** [comment]
The address DB for Eth is only about three weeks old, are all your transactions newer than this?

The addressDB will only match if your wallet has at least one transaction on whatever blockchain you are using the addressDB for. (So simply having a BTC address that you never sent funds to won't help)

The queries you want on BigQuery are here: https://btcrecover.readthedocs.io/en/latest/Creating_and_Using_AddressDB/#generating-address-lists-from-google-bigquery

You can just use create-address-db.py , the arguments you want are:
--inputlistfile INPUTLISTFILE
                        The file that contains a list of addresses that will be used to create the addressDB file
  --multifileinputlist  Whether to try and load multiple sequential input list files (incrementing the last 4 letters
                        of file name from 0 to 9998)

Creating a video that walks through this is on my TODO list so it might get done in the next month or so.

**Comment by coded00guy** [comment]
I downloaded the address from  bigQuery as a txt file. 
My major problem is making it a .db file. Am i going to attempt it as i did below? If not. Can you specify pls ![IMG_20210601_231539.jpg](https://user-images.githubusercontent.com/58042898/120397077-907e2f00-c32f-11eb-98a9-a92228d8482a.jpg)

**Comment by 3rdIteration** [comment]
Basically I have always exported it to cloud storage in the CSV format which breaks it up in to a bunch of files that are a few hundred MB each.

If the file you are using in that command has one address per line it should work fine. You can also set the DBLength to 28 for a smaller file.

**Comment by 3rdIteration** [comment]
I also notice you are running 1.6, I suggest you use the main repo master rather than that release.
