### ISSUE TITLE
`seedrecover.py` doesn't run on Linux due to line-endings

### ISSUE THREAD

**Issue by ctrlcctrlv** [3rdIteration/btcrecover#194]
```
[fred@laptop btcrecover]$ ./seedrecover.py --wallet-type electrum2 --mnemonic …… --addrs …… --bip32-path "m/0'/0"
/usr/bin/env: ‘python\r’: No such file or directory
```

I ran `dos2unix` on the file to get this to work, and will PR the fix. It shouldn't affect Windows runs while allowing Linux runs.

**Comment by 3rdIteration** [comment]
Which environment are you in? I have never seen this cause issues any of the major Ubuntu releases for the last few years.

**Comment by ctrlcctrlv** [comment]
Bash, Arch Linux
