### ISSUE TITLE
Command error : python run-all-tests.py -vv 

### ISSUE THREAD

**Issue by yichuang-zh** [3rdIteration/btcrecover#196]
The terminal keeps no action after that, below is the screenshot:

![2021-06-08_09-24](https://user-images.githubusercontent.com/44933638/121108118-bf1e6d00-c83b-11eb-9d3e-96e9900d8b9c.png)

os: ubuntu 20.04

**Comment by 3rdIteration** [comment]
How many cores/threads does your system have?

**Comment by yichuang-zh** [comment]
It's in a virtual machine, with 2 cpus.
There are 4cores/8threads on the host.

**Comment by 3rdIteration** [comment]
And what software environment are you using?

**Comment by yichuang-zh** [comment]
Software environment?

Do you mean python or python3? My environment is python3.

Virt-manager create a vm, install ubuntu 20.04, then install btcrecover. There is no other software installed.

**Comment by 3rdIteration** [comment]
I can't reproduce this error at all, even with a fresh install of Ubuntu. Are you able to compress the entire VM and send it so I can have a look at what is going on?
