### ISSUE TITLE
possiblepassword.log

### ISSUE THREAD

**Issue by GSinatra** [3rdIteration/btcrecover#201]
The password I remember was found in the possiblepassword.log, but it doesn't open the wallet.

**Comment by 3rdIteration** [comment]
So if you look in the possible passwords file, what string of text does it match on? (Is it all human readable text?)

**Comment by GSinatra** [comment]
It is look like "Possible Password ==>My Password<== in Decrypted Block ==>Sings go block<==".

**Comment by 3rdIteration** [comment]
So the decrypted block text is : Sings of block

That's exactly what is says, character for character? (That doesn't sound
right)

**Comment by GSinatra** [comment]
No) is unreadable mix of signs.

**Comment by 3rdIteration** [comment]
Then it isn't the password. (A proper match will look something like the
examples given at the top of the possible passwords file)

**Comment by GSinatra** [comment]
You probably misunderstood me. In file passiblepassword.log I get a string "Possible Password ==>HERE PASSWORD SAME AS I REMEMBER<== in Decrypted Block ==>HERE unreadable mix of signs(some letters, numbers and signs)<==". Can give two different passwords same hash?

**Comment by 3rdIteration** [comment]
Nope, if you are getting unreadable symbols then it's not the correct
password.

**Comment by GSinatra** [comment]
It is look like " 7"86bac59'm "

**Comment by GSinatra** [comment]
It look like ==> {c'?g62N@ppiCJ <==

**Comment by 3rdIteration** [comment]
Yep..  random garbage... That isn't a match.

**Comment by GSinatra** [comment]
1 more question! Can it be a part off pass or near?

**Comment by 3rdIteration** [comment]
No... Re-read my previous reply... There is no such thing as "near" for
this type of decryption, the only time you get any information other than
"it's completely wrong" is when you get the password that is fully correct.

**Comment by GSinatra** [comment]
Thank you!
