### ISSUE TITLE
XRP passphrase Trezor

### ISSUE THREAD

**Issue by BountyHAHC** [3rdIteration/btcrecover#202]
Hello i read this comment - If you are trying to do a recovery for a coin/wallet that isn't listed above, feel free to contact me as it may be possible for you to sponsor the addition of that crypto as part of an assisted recovery fee.

I need assistance with my passphrase on my Trezor.

**Comment by 3rdIteration** [comment]
BTCRecover already supports passphrase recovery using XRP addresses for BIP39 wallets. 

See here: https://btcrecover.readthedocs.io/en/latest/Usage_Examples/basic_password_recoveries/#bip39-passphrase-protected-wallets-electrum-extra-words

**Comment by BountyHAHC** [comment]
Thank you
