### ISSUE TITLE
Cant  launch GUI for Questions 

### ISSUE THREAD

**Issue by farazkhan78654321** [3rdIteration/btcrecover#203]
You can disable this message by running this tool with the --dsw argument

* * * * * * * * * * * * * * * * * * * *
*          Security: Warning          *
* * * * * * * * * * * * * * * * * * * *

Warning: Unable to load TK, no gui available, you will need to set some recovery arguments manually
No wallet file or type specified... Exiting...
Press Enter to exit ...Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/Desktop/btcrecover-master-2/btcrecover/btcrseed.py", line 2465, in <lambda>
    input("Press Enter to exit ..."))
ValueError: I/O operation on closed file.

**Comment by 3rdIteration** [comment]
That's odd, it looks like you installed Python3 without installing the TK/TCL feature. 

The solution is to install TK (just select modify install in Windows and you can add it) or to use the command line and specify all arguments, as per the error message.

**Comment by datacommand** [comment]
On mac: brew install python-tk 

Solved it for me...
