### ISSUE TITLE
hashcat / john / policygenerator.py mask support

### ISSUE THREAD

**Issue by sigkill** [3rdIteration/btcrecover#205]
I'm not sure if it's already something that has been considered, but I was wondering if there is any chance the token-list file could get an option to use standard masks like what hashcat and other utilities use?

Tools like policy generator would be way easier to use with this token-list text if there were a switch to enable hashcat like mask support.

https://github.com/iphelix/pack

**Comment by 3rdIteration** [comment]
No really, feel free to bring a PR to implement it.

**Comment by sigkill** [comment]
Have been working on it, ever so slowly. Will submit a PR when I get it working.

**Comment by 3rdIteration** [comment]
Closed as stale issue
