### ISSUE TITLE
WARNING: Derivaton path: 4 does not match the xpub you have provided.

### ISSUE THREAD

**Issue by AntonioRossi** [3rdIteration/btcrecover#207]
Trying to recover a passphrase entered in ledger for configuring an additional account.

### step 1
I run the following command:
```
python3 btcrecover.py --bip39 --tokenlist tlist.txt --mpk ’mpk’ --mnemonic ‘the ‘mnemonic here’ --enable-opencl
```

the `tlist.txt` file is as follows:
```
#--autosave ../../stecca/tlist.sav --pause --max-tokens 1 --typos-replace %P --typos-insert %P --typos-case --typos-repeat --typos-swap --typos-repeat --typos-delete --typos 2

passwd1
passwd2
passwd3
passwd4
```

### step 2

When executing I get the following warning:
```
xpub depth:       3
xpub parent fingerprint: b'3364B270'
xpub child #:     0'
WARNING: Derivaton path: 4 does not match the xpub you have provided.
```

### step 3
Undel `ledger live inside `Edit Account -> Advanced` I get this info for the account:
```json
{
  "xpub": “mpk”,
  "index": 0,
  "freshAddressPath": "84'/0'/0'/0/1",
  "id": "libcore:1:bitcoin:’mpk’:native_segwit",
  "blockHeight": 659595
}
```

Questions
1. The `xpub depth` value of `3` sounds strange to me, shouldn't it be `0`? (step 2)
2. Why I receive the warning message? (step 2)
3.  If I run with these settings do I could find the passphrase anyway?
4.  I also have a receiving address for which a transaction was made, should I use that instead of the mpk?

**Comment by 3rdIteration** [comment]
Because the 4th derivation path in the default pathlist includes one for BRD wallet.

See here: https://btcrecover.readthedocs.io/en/latest/bip39-accounts-and-altcoins/
