### ISSUE TITLE
who can crack blockchain wallet , I will pay with bitcoin 

### ISSUE THREAD

**Issue by rfakit** [3rdIteration/btcrecover#209]
email me if you can
rfak.it@gmail.com

**Comment by 3rdIteration** [comment]
What does this even mean, is it your own wallet? Do you have any idea what your password is? (You are going to have scammers contact you by posting your email like that)

**Comment by rfakit** [comment]
can you help me with this

yeah this my own account
i forgot its password. i contact blockchain support but no luck
i have wallet.aes.json and access to email

**Comment by 3rdIteration** [comment]
Blockchain support can't help you.

Have you tried the process in the documentation here? Do you have any idea
what the password might be?

**Comment by 3rdIteration** [comment]
I'm away for the next week but if you wanted to go the private session or
trusted recovery route I could have a crack at it. (Price, process, terms
and request form here
https://cryptoguide.tips/recovery-services-consultations/)

Just be aware that it isn't magic, it all comes down to how close your
guess of the password is.
