### ISSUE TITLE
DLL load failed while importing _cl

### ISSUE THREAD

**Issue by kipilk0** [3rdIteration/btcrecover#21]
_C:\btcrecover>python btcrecover.py --list-gpus_

Starting btcrecover 1.2.0-Cryptoguide on Python 3.8.2 32-bit, 21-bit unicodes, 32-bit ints
btcrecover.py: warning: DLL load failed while importing _cl:
btcrecover.py: error: no supported GPUs found

**Comment by 3rdIteration** [comment]
GPU support still yet to be fixed for Py3 branch, see here https://github.com/3rdIteration/btcrecover/issues/17

**Comment by 3rdIteration** [comment]
Documentation has now been updated to work with the latest Python3 branch. It should all work now if you follow that. (You will need to download the 32bit module, not the 64bit one.

Added in: https://github.com/3rdIteration/btcrecover/commit/daad8755c6a46d1337114e3c29e7a8444d30c356
