### ISSUE TITLE
After Installation as per guide, when i run seedrecover.py received this error

### ISSUE THREAD

**Issue by SaSam5666** [3rdIteration/btcrecover#210]
###  attached screen shot for your ref.
![error while run seedrecover](https://user-images.githubusercontent.com/87407892/125562609-49d2afca-1ca4-4a9d-bafc-fb8e41d2e53e.jpg)

**Comment by 3rdIteration** [comment]
This looks like an issue with coincurve and it looks like you are running Windows 7, so this means that python 3.9+ won't work. Try again with a supported operating system and it will probably work fine, you could also try python 3.8 and you might get lucky.

**Comment by SaSam5666** [comment]
Hi, 
Thanks, I tried python 3.8, It working now.
