### ISSUE TITLE
Add support for multiple BIP39 seeds when running btcrecover.py

### ISSUE THREAD

**Issue by 3rdIteration** [3rdIteration/btcrecover#211]
Similar to the ability that is in seedrecover.py to do a seed recovery with multiple possible passphrases.

**Comment by rickyars** [comment]
@3rdIteration is it possible to do any seedrecovery with a passphrase (BIP39)? i can't find an example or get this to work on my own.

**Comment by 3rdIteration** [comment]
Closed as stale issue
