### ISSUE TITLE
Support for metamask

### ISSUE THREAD

**Issue by echelonblue** [3rdIteration/btcrecover#213]
Hi,

I would like to request support for  metamask.  
I do have the bip39 12 words seed, but  the order is lost. 
So I'll hope that this tool can help me out. 

Please help.

**Comment by 3rdIteration** [comment]
This exact recovery is already fully supported. 

https://btcrecover.readthedocs.io/en/latest/Usage_Examples/2020-05-02_Descrambling_a_12_word_seed/Example_Descrambling_a_12_word_seed/
