### ISSUE TITLE
OpenCL

### ISSUE THREAD

**Issue by GSinatra** [3rdIteration/btcrecover#214]
First time when I write --enable-gpu in result cmd show me ERROR in code, then it say "try --enable-OpenCL", I try it. Now when I write "--enable-OpenCL" cmd tell me "wrong argument --enSable-OpenCL". Can you help?

**Comment by 3rdIteration** [comment]
It looks like you have mis-typed --enable-opencl

**Comment by GSinatra** [comment]
I write "python3 btcrecover.py --enable-OpenCL --typos-map typos.txt". Btcrecover answer me this:
![image](https://user-images.githubusercontent.com/43311340/127193958-cace71ee-2cd8-4601-972f-d26e24fc8876.jpeg)
![image](https://user-images.githubusercontent.com/43311340/127194031-43b9802b-e261-4824-bd1f-cc7487cb2e5a.jpeg)
![image](https://user-images.githubusercontent.com/43311340/127194068-1f8b4f08-9944-4ece-9215-bb05d23b0978.jpeg)

**Comment by 3rdIteration** [comment]
You will get this error if you are running an older version of BTCRecover with the latest Nvidia drivers. Are you running the latest master code from the repository?

If you are running the latest code, which version of the NVidia drivers are you running?

**Comment by GSinatra** [comment]
Date 12.07.21
Version 30.0.14.7141

**Comment by 3rdIteration** [comment]
Riteo, I'll try with the most recent driver. Best bet is to use a pre-465
driver for now. (It's possible that Nvidia broke it again in the latest
driver)

See https://github.com/3rdIteration/btcrecover/issues/176

**Comment by GSinatra** [comment]
Thank you so much!

**Comment by 3rdIteration** [comment]
Just tested with 471.41 and the latest code from the Github master and it all works fine. 

When you run the unit tests to test your config, does everything pass?

**Comment by GSinatra** [comment]
All tests show good work.

**Comment by 3rdIteration** [comment]
So all the tests passed but running seed recover on its own fails? (Or are
you running newer code, or older drivers now)

**Comment by GSinatra** [comment]
Yes. But I uninstalled all drivers 471 and install 461. All work.

**Comment by 3rdIteration** [comment]
If you could try again with the 471 drivers and latest code, it should work
fine.

**Comment by GSinatra** [comment]
Thank you! 461 fine.
