### ISSUE TITLE
How much is the possible_passw0rd.log near to real password?

### ISSUE THREAD

**Issue by rfakit** [3rdIteration/btcrecover#215]
hi bros 

How much is the possible_passw0rd.log near to real password?

**Comment by 3rdIteration** [comment]
There is no such thing as a password being "nearly correct" as far as the content of that file goes. All that file indicates is whether your particular wallet file could probably have decrypted but not been correctly detected as such.

There is no way to know whether any given incorrect password is and "more correct" than any other incorrect password...
