### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by GSinatra** [3rdIteration/btcrecover#217]
Why i can brute Rus letters on Mac and on Win no?

**Comment by 3rdIteration** [comment]
Are you asking whether BTCRecover supports both languages on both platforms? If so then it should work fine.

**Comment by GSinatra** [comment]
No! Sorry my Eng) I askin, why is work on Mac but show error on Win?

**Comment by GSinatra** [comment]
BTCRecover show this:
![image](https://user-images.githubusercontent.com/43311340/127606224-d3914ed8-fb2f-4d02-97e5-d5e8af15a742.jpeg)

**Comment by 3rdIteration** [comment]
Looks like you have some invalid unicode in your tokenlist.

**Comment by GSinatra** [comment]
😂if you wanna make unbrutable pass call me 🤙 
How I can understand what sign is Unicode? Weird! The Mac is working, but too slow. On Win BRec work only with Latin alphabet.

**Comment by GSinatra** [comment]
"0xdf in position 27" how I can understand what letter is? Why it work on Mac?

**Comment by 3rdIteration** [comment]
It should work, so you mind sharing a tokenlist file with the characters
that are causing issues?

Which version of Windows are you running?

**Comment by GSinatra** [comment]
The problem has been solved! I write lil script and it take part of token from 1 list an part from list 2. When he take Cyrillica from .txt(utf-8) in python it seems like abra kadabra. So I turned lists to "ANSI" and it help for python, but he save auto-token in "ANSI". Then I add encoding=utf8 and all start work! Thank you man. You do really good job! If don't get my money back maybe I will become junior on python😂

**Comment by 3rdIteration** [comment]
So just clarifying did you edit BTCRecover for this or make changes in your tokenlist file encoding?

**Comment by GSinatra** [comment]
No) I'm not so cool programmer as you!.. yet) I just make
code which take token from different lists and put it in token-auto, than it start BTCrecover. Because typos too slow. Maybe it good if you have one long word with features, but I make difficult pass with many parts and all they have some features. If I ask typos taking into account all the probabilities, it takes two or three hours. That's why I make fractional token Files to speed up the process.
