### ISSUE TITLE
possible_passwords.log

### ISSUE THREAD

**Issue by TheWhiteHat007** [3rdIteration/btcrecover#223]
If the password works and was not correctly found, or your wallet detects a false positive, please report the decrypted block data at https://github.com/3rdIteration/btcrecover/issues/

2021-08-04 21:08:56 Possible Password ==>Anilmishar@123<== in Decrypted Block ==>{ "0~
MZ<==
2021-08-04 21:08:56 Possible Password ==>@Anilmishar@1231980<== in Decrypted Block ==>{" &2k5p=l%<==

My wallet.aes.json file is only 1 kb and i recover i got this msz but when login it says wrong password what can i do....????

**Comment by 3rdIteration** [comment]
These aren't false positives, just random characters.

You need to try with a different tokenlist
