### ISSUE TITLE
possible_passwords.log

### ISSUE THREAD

**Issue by TheWhiteHat007** [3rdIteration/btcrecover#225]
2021-08-06 17:58:40 New Recovery Started...
This file contains passwords and blocks from passwords which `may` not exactly match those that BTCRecover searches for by default. 

Examples of successfully decrypted blocks will not just be random characters, some examples of what correctly decryped blocks logs look like are:

Possible Password ==>btcr-test-password<== in Decrypted Block ==>{
"guid" : "9bb<==
Possible Password ==>testblockchain<== in Decrypted Block ==>{"address_book":<==
Possible Password ==>btcr-test-password<== in Decrypted Block ==>{"tx_notes":{},"
Possible Password ==>Testing123!<== in Decrypted Block ==>{"double_encrypt<==

Note: The markers ==> and <== are not part of either your password or the decrypted block...

If the password works and was not correctly found, or your wallet detects a false positive, please report the decrypted block data at https://github.com/3rdIteration/btcrecover/issues/

2021-08-06 17:58:42 Possible Password ==>@snirmal1231980<== in Decrypted Block ==>{" &2k5p=l%<==
2021-08-06 17:58:42 Possible Password ==>2100211994#44444<== in Decrypted Block ==>{ "0~
MZ<==

what is the meaning of this log file, Kindly confirm ASAP.

**Comment by 3rdIteration** [comment]
It means what it says...

Examples of successfully decrypted blocks will not just be random characters, some examples of what correctly decryped blocks logs look like are:

Possible Password ==>btcr-test-password<== in Decrypted Block ==>{
"guid" : "9bb<==
Possible Password ==>testblockchain<== in Decrypted Block ==>{"address_book":<==
Possible Password ==>btcr-test-password<== in Decrypted Block ==>{"tx_notes":{},"
Possible Password ==>Testing123!<== in Decrypted Block ==>{"double_encrypt<==

The two examples you have are just random characters, so it has not found the password.

**Comment by TheWhiteHat007** [comment]
jrPBPFupdcOWTcuw9rQQQtSy2/F966QaPf2VsCjNszecjLsHPvbaxke1t2rY/JwRGWujd/CDt4FBCNTtBYgiSh1zReYLuoL9PYUeKnFT16b29fWp/eE6YfO0OD4ZhmgAmJVKg3b7htcQl31J/HyEYYOEYI6Cx0FQ8K4eOVmiPEVXuUGZG6v5xANcGPeAo8ZDmqNjzQy6ilfYA5cRa2uG4P1HbAGGCsJJ4LqXbAg6/L8nFQx6XZEkBreO4U1wEWgMESGWpf06Kus7NoMJ3CytOJzvwoU5P1StijUIgoWND62leVTZQmUyyJErYHjGPjHC73WIDzfrtrCAf6CEbhhcazhJv6j+HKO47L1jMGfwNLiH6oIJVjRH4GF0SwRGPwzZgnNYvZ+pXYfHTcFrl495wseAWgxIv4BEraD3O/aeYYmuxyJUbarI/8bSFPCqE9szR77PYmIo1mBvlyVHhb0+tPEJYRkcz9dWixvFy/KJ7Q4buKepBJuLbDJp1IDYHrORcTbXzL1a2DzQ1UdGM+VaxZsX1aUbCnBNex6OkiJOUMI/bZLQUDyW9qv7Mkfeqx0M21oImYmmad68lKH7rQEB5nBicmq+g8/C3ZBQdUNvmTID8akyK+18RNECaugKq0MC9yXCYK8olyru5D2Yc6UXx5T124dcBS9sleWVDtXdVgJsPOQNntAofaUZs03WtThh




please for me ones you check this wallet.aes.json file........

**Comment by 3rdIteration** [comment]
Don't just post your wallet on Github in the public for everyone to see... I have deleted your previous comment...

If you want a private session or trusted recovery the price, process, terms and request form is here: https://cryptoguide.tips/recovery-services-consultations/
