### ISSUE TITLE
Support for compressed password lists in popular formats rar, gz, bzip2, xz, zip

### ISSUE THREAD

**Issue by sigkill** [3rdIteration/btcrecover#226]
Hello,

I was curious how challenging it would be to add support for compressed password lists, like jtr has support for. I've been working on a pretty interesting build where the password lists are multi-gigabyte in size when uncompressed, but have a need to just read in place instead.

I looked into setting up a function to do so, but so far everything has been a failure.

Still looking into my other request re supporting hashcat / john mask format as well, have not had a chance to create a PR though, as I haven't got it working quite right yet.

**Comment by 3rdIteration** [comment]
Added gzip support in https://github.com/3rdIteration/btcrecover/commit/c0f61dfe219f3677db1b26901523d2205bf46185
