### ISSUE TITLE
Intel OpenCL pyopencl loads, kind of works but causes a reboot. Checking settings for more info now.

### ISSUE THREAD

**Issue by sigkill** [3rdIteration/btcrecover#229]
![image](https://user-images.githubusercontent.com/634740/129132446-4b08ff2b-144a-4741-8466-d45fcc0be9c2.png)

Cool this actually works. 
`--no-eta --enable-opencl  --opencl-platform 0   --opencl-workgroup-size 8 --threads=480`

_Originally posted by @sigkill in https://github.com/3rdIteration/btcrecover/issues/228#issuecomment-897312886_

**Comment by 3rdIteration** [comment]
This would likely be related to an issue with your drivers. What sort of hardware are you running?

**Comment by sigkill** [comment]
Intel Xeon Phi with the older Intel OpenCL drivers, they work for john and mostly work for hashcat, it was an absolute trip to see it kind of working on btcrecover the other night.

Found a weird situation where people say these are slow, I think the real problem is that the handling of the process to core / thread is weird natively, but when you run via the coi offloading driver on the host system running with a "normal" processor, the jobs get handled and passed much more efficiently, and actually end up using the extra cores.

BitCrack runs well too, though the statistics are kind of messed up, as the Intel OpenCL driver is a bit off too.

System is down right now, but I will play with it again next weekend and see what I can figure out as far as driver / python multithreading. I had to compile almost the entire system by hand, if I was using the Intel compiler it might be a different story as far as speed etc, but they've redone their website yet again and it's nearly impossible to find the compiler for this 7 year old card.

**Comment by sigkill** [comment]
Took another pass at it today - it's certainly something funky with drivers or mounting NFS root. I did also bump the workgroup size down to 6 and it's more stable, but the threading is absolutely broken. Has to be an Intel issue and not a BTC / Python issue.
