### ISSUE TITLE
Total brute force for short passwords

### ISSUE THREAD

**Issue by quelibrio** [3rdIteration/btcrecover#231]
Hello Crypto enthusiasts,
I am doing a recovery of a password for an old bitcoin core .dat file with few hundred bucks in there.
I remember the password there was in the likes of 5 Latin letters and 1 or 2 digits but no real idea what was it. (I used lame passwords back then)
Can I run the tool to test all possible alphanumeric combinations for that short of a range ? I don't want to provide a token/password list because it doesn't really make sense in my case.
Regards Quel

**Comment by 3rdIteration** [comment]
If it's that short then just create a tokenlist with wildcard of length 5.

**Comment by sigkill** [comment]
And you can test with the tokenlist and --listpass flags, as I found out recently!
