### ISSUE TITLE
Generation 12 seed in different order and passphrase .

### ISSUE THREAD

**Issue by eLinkroad** [3rdIteration/btcrecover#233]
seedrecover.py does not select 12 seeds if a passphrase was entered when registering an Electrum wallet.

Hi, thanks for the youtube responses. I am using the --passphrase argument for seedrecover.py but the combination is not calculated. Here is the code used to generate it:

`python seedrecover.py --passphrase --no-dupchecks --mnemonic-length 12 --language EN --dsw --addr-limit 1 --addrs bc1qjq3lzfw43rtuafdughczrhr24td7lwtkxqchn4 --tokenlist ./btcrecover/test/test-listfiles/seed.txt --wallet-type electrum2` 

In seed.txt 11 and 12 phrases are replaced by places
![image](https://user-images.githubusercontent.com/81689813/130641088-e9a1ad61-de5e-4df1-bfd5-9ab48e7d71cd.png)
Passphrase request
![image](https://user-images.githubusercontent.com/81689813/130640469-1b69fa9e-0af9-4035-8a9b-97959241933e.png)
Passphrase confirmation
![image](https://user-images.githubusercontent.com/81689813/130640596-9bff4443-6c36-4c2d-98c6-26811732db38.png)
Tokenlist handling
![image](https://user-images.githubusercontent.com/81689813/130640662-0d7639a4-844f-46d5-94b8-d2c1f1f77a1f.png)

**Comment by 3rdIteration** [comment]
So why are you using a tokenlist for this? (Why not just enter the 10 words you have)

Can you share a passphrase that you are using to test with so I can see if I can reproduce this behavior.

**Comment by eLinkroad** [comment]
seeed: discover frame earth reopen matrix snake cream candy drop useful pigeon consider
passphrase: qwerty

**Comment by eLinkroad** [comment]
Increased --addr-limit to 20 and it worked

**Comment by 3rdIteration** [comment]
Hadn't had a chance to look at it but setting address generation limit too low will certainly cause this behaviour
