### ISSUE TITLE
Reading 2 missing words from list in text file

### ISSUE THREAD

**Issue by NewCoNam** [3rdIteration/btcrecover#237]
Hi, I have noticed that this program is faster when possible combination of words is done outside (don in another program). Is it possible to have the 2 missing words function read from a listfile.txt containing all possible combinations. Instead of putting only one line, having to read from a text file just like SeedTokenList.txt.  How can I do that in btcrecover?

**Comment by 3rdIteration** [comment]
This can be achieved with a tokenlist with some grouped tokens as per here https://btcrecover.readthedocs.io/en/latest/Usage_Examples/2022-04-02_Seed_Tokenlist_TokenBlocks/example_seed_tokenlist_tokenblocks/

You would basically just group the tokens that you have and add both positional and required tokens. You would then just add two more lines which have all 2048 BIP39 words.

At the end of the day, this will give you no performance gain as opposed to simply using a standard seed recovery and putting a placeholder in the location of each missing word.
