### ISSUE TITLE
Am I doing this right?

### ISSUE THREAD

**Issue by Cometspoon** [3rdIteration/btcrecover#240]
I have exhausted the low hanging fruit on my recovery attempt and am about to start much larger searches so I figured I should check and make sure I am doing this right. 

I am trying to recover a 12 word seed from a keepkey that for reasons I have 19 words to search from. I went into a block explorer and found what I believe are the first 18 change addresses and one address that might be the first receiving address and added them to an address database. These addresses were generated in late 2016 and begin with a 1.  I have then been running the following script.

c:\Python39\python seedrecover.py --no-dupchecks --mnemonic-length 12 --language EN --dsw --wallet-type BIP39 --addr-limit 20 --addressdb addmore.db --tokenlist token.txt --threads 60 --bip32-path m/44'/0'/0'/0 m/44'/0'/0'/1 --no-eta 

Am I doing this right?

**Comment by 3rdIteration** [comment]
Honestly you might as well just use a full Address DB and an addr-limit of 1, it will work even if you don't know any of the addresses as long as you have the right derivation path.

**Comment by Cometspoon** [comment]
In order to do that I will have to find an old version of the chrome extension for the keepkey. Sounds like fun.

Thanks for the help.

**Comment by 3rdIteration** [comment]
Nar, keepkey just uses all the standard BTC derivation paths, the ones blindled with BTCRecover by default are fine and you can just disable everything other than the legacy derivation path.

**Comment by Cometspoon** [comment]
My understanding is that keepkey uses m/44'/0'/0'/0 for receiving addresses and m/44'/0'/0'/1 for change addresses. I am sort of vaguely worried that it might have been possible to request another receiving address without using the first one so I was thinking about using m/44'/0'/0'/1 since presumably the software wouldn't skip change addresses. 

Does that sound like a good idea?

**Comment by 3rdIteration** [comment]
Just leave it all as the defaults and use it with an AddressDB, their wallet will not have let you skip the first few addresses in the wallet.

**Comment by Cometspoon** [comment]
Ok, thank you very much for the help.
