### ISSUE TITLE
Syntax Error when trying to run seedrecover.py

### ISSUE THREAD

**Issue by lamacawile** [3rdIteration/btcrecover#241]
I've followed all steps in the documentation and I still run into this error

![image](https://user-images.githubusercontent.com/84063824/131557022-6d19d95a-94c4-4ca5-9031-bcabf02d5fcb.png)

**Comment by 3rdIteration** [comment]
This has been fixed as of today (just download the latest repo and it will work), it relates to some python 3.8+ code in one of the modules.
