### ISSUE TITLE
download-dogechain-wallet.py - page not found download error

### ISSUE THREAD

**Issue by digitalhussar** [3rdIteration/btcrecover#244]
I tried the latest script but .json file contains the following

<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dogechain - Page not found</title>

**Comment by 3rdIteration** [comment]
Looks like they have changed something on their login page. You will need to download the wallet.aes.json file manually through the development tools screen in your browser. (Just try to log in, use any password and you will find it in the network tab as a response)

**Comment by 3rdIteration** [comment]
Documentation updated in https://github.com/3rdIteration/btcrecover/commit/95fd9779eb88917ee95ca2bba14dc63b9ed9c6b6

Updated docco at https://btcrecover.readthedocs.io/en/latest/Extract_Scripts/#usage-for-dogechaininfo
