### ISSUE TITLE
How to recover a Solana wallet

### ISSUE THREAD

**Issue by coded00guy** [3rdIteration/btcrecover#245]
Is there a code amongst the recovery that specify how to recover a sollet wallet with scrambled words

**Comment by 3rdIteration** [comment]
BTCRecover doesn't currently support Solana, but if you wanted to sponsor this either directly, or as a trusted recovery, it could likely be added.

**Comment by 3rdIteration** [comment]
So I'm looking at Solana functionality with another trusted recovery that I am doing. 

How long is your Solana seed? (Is it a 12 word seed or 24?)
