### ISSUE TITLE
need help,

### ISSUE THREAD

**Issue by dextronomous** [3rdIteration/btcrecover#247]
how can i get this one right guys, 9character end is 99 and how to put a token file for this one, it s really not 
a recover me guide around here, so way to difficult read trough all pages still need this help..

9 character
end is 99
with or without --no-eta --skip-dupchecks 
%n%n%n%n%n%n%n%n  so seven for before 99 and 99 always end. but the seven all english layout maybe special characters.

**Comment by 3rdIteration** [comment]
I don't understand what you asking.

Are you asking about using a positional anchor so that "99" is always at the end of the password?

**Comment by dextronomous** [comment]
yes please, that'll be all, could you help out and it is in total 9 characters including the (99 at the end)
thanks so much

**Comment by 3rdIteration** [comment]
You could just use a passwordlist and have it process the wildcards in there. Basically it would just be something like %7n99

Just be aware that this will have about 80 billion passwords, so depending on which kind of wallets you are trying to recover then this might be impractical.
