### ISSUE TITLE
Non-standard derivation path

### ISSUE THREAD

**Issue by eLinkroad** [3rdIteration/btcrecover#249]
When using a derivation path and a passphrase, it does not find the correct order of seed phrases. Maybe I did not correctly compose the code to generate it.

--bip32-path `"m/74149'/5500'/14300'"`

passphrase `48testoviy52`

seed phrases: 
`^1^hurry
^2^blouse
^3^wise
^4^prize
^5^grant
^6^bronze
^7^audit
^8^pupil
^9^genre
^10^bring
service
arm`

Here is the code used to generate it: `python seedrecover.py --passphrase --no-dupchecks --mnemonic-length 12 --language EN --dsw --addr-limit 50 --addrs 3EDkQdYajkn1kxH3LENbUbHQa74gvaCLGF --tokenlist ./btcrecover/test/test-listfiles/seed.txt --wallet-type BIP39 --bip32-path "m/74149'/5500'/14300'" --enable-opencl`

**Comment by 3rdIteration** [comment]
You will need to add a trailing /0 if you are looking for main account addresses, /1 for change addresses.

**Comment by eLinkroad** [comment]
![image](https://user-images.githubusercontent.com/81689813/132878089-8fa2ef83-e84b-4384-bd0f-760011184573.png)
![image](https://user-images.githubusercontent.com/81689813/132878172-43cd12e2-a7dd-4259-8be4-e9a7a72987cf.png)

**Comment by 3rdIteration** [comment]
You will also need to use the force-p2sh argument if you are using p2sh on a non-standard derivation path.

If you want me to be able to try and reproduce this you also need to post the test seed.

**Comment by eLinkroad** [comment]
> Вам также потребуется использовать аргумент force-p2sh, если вы используете p2sh по нестандартному пути деривации.
> 
> Если вы хотите, чтобы я смог попытаться воспроизвести это, вам также необходимо опубликовать тестовое семя.

I tried to use --force-p2sh but that also didn't work for me, here is the seed.txt file details:

^1^hurry
^2^blouse
^3^wise
^4^prize
^5^grant
^6^bronze
^7^audit
^8^pupil
^9^genre
^10^bring
service
arm

**Comment by 3rdIteration** [comment]
I don't want the seedlist file, just something that I can put in to Ian Coleman's BIP39 tool and verify things like the address, etc. ("hurry blouse wise prize grant bronze audit pupil genre bring service arm" is an invalid mnemonic)

**Comment by eLinkroad** [comment]
Addresses: 3EDkQdYajkn1kxH3LENbUbHQa74gvaCLGF
passphrase: 48testoviy52
seed: hurry blouse wise prize grant bronze audit pupil genre bring service arm
p2sh-p2wpkh: m/74149'/5500'/14300'

![image](https://user-images.githubusercontent.com/81689813/132885207-acadd9af-9d17-4a0c-8459-52785d0d9db5.png)
![image](https://user-images.githubusercontent.com/81689813/132885232-9d49e6d9-38bb-444d-aef2-554bba9a0d58.png)
![image](https://user-images.githubusercontent.com/81689813/132885458-6b53fd69-531e-446e-8377-33d37178492c.png)
![image](https://user-images.githubusercontent.com/81689813/132885524-a86c01a6-84ac-4c4c-9f80-45ee442b9d51.png)
![image](https://user-images.githubusercontent.com/81689813/132886450-d19d3457-c90a-4744-bc0b-e4f2f423f18d.png)
![image](https://user-images.githubusercontent.com/81689813/132886544-eb962fe6-5b2d-46f3-a1d6-9e0e1933e188.png)

**Comment by 3rdIteration** [comment]
That checksum is invalid, you can see it right there in Electrum. This is why the seed isn't being checked.

Are you saying that you deliberately used a seed with an invalid checksum and are trying to do a recovery like this?

**Comment by eLinkroad** [comment]
It turns out that if you use a number with an invalid checksum, then without knowing the correct order of the words, it will not be possible to recognize them in the correct order in the future?

**Comment by 3rdIteration** [comment]
You can disable the checksum checking in the arguments if you want to use a non-standard mnemonic, but this will slow the checking down. The vast majority of wallets will not allow you to use a non-standard checksum...

**Comment by eLinkroad** [comment]
How can I disable checksum checking in arguments?

**Comment by eLinkroad** [comment]
I generated a BIP39 seed on the iancoleman, but the restoration of the seed phrase still does not work.

Addresses: 327P2fpzn2nHCq3w9SmbRiqjQVmrCQkDQ1
passphrase: qwerty
seed: wine cash grant will wise west small relax occur rural matter wagon
p2sh-p2wpkh: m/123'/345'/6545645'

`python seedrecover.py --passphrase --no-dupchecks --mnemonic-length 12 --language EN --dsw --addr-limit 50 --addrs 327P2fpzn2nHCq3w9SmbRiqjQVmrCQkDQ1 --tokenlist ./btcrecover/test/test-listfiles/seed.txt --wallet-type BIP39 --bip32-path "m/123'/345'/6545645'/0" --enable-opencl`

`python seedrecover.py --passphrase --no-dupchecks --mnemonic-length 12 --language EN --dsw --addr-limit 50 --addrs 327P2fpzn2nHCq3w9SmbRiqjQVmrCQkDQ1 --tokenlist ./btcrecover/test/test-listfiles/seed.txt --wallet-type BIP39 --bip32-path "m/123'/345'/6545645'/1" --enable-opencl`

**Comment by 3rdIteration** [comment]
You left the trailing zero off the derivation path, add it and it all works...

**Comment by 3rdIteration** [comment]
Can't reproduce... Code below works fine.

`python seedrecover.py --dsw --addr-limit 10 --wallet-type bip39 --addrs 327P2fpzn2nHCq3w9SmbRiqjQVmrCQkDQ1 --force-p2sh --passphrase --bip32-path "m/123'/345'/6545645'/0" --tokenlist testseed.txt --language en --mnemonic-length 12`

with the tokenlist:
```
^1^wine
^2^cash
^3^grant
^4^will
^5^wise
^6^west
^7^small
^8^relax
^9^occur
^10^rural
^11^matter 
^12^wagon

```

**Comment by eLinkroad** [comment]
> Невозможно воспроизвести ... Код ниже работает нормально.
> 
> `python seedrecover.py --dsw --addr-limit 10 --wallet-type bip39 --addrs 327P2fpzn2nHCq3w9SmbRiqjQVmrCQkDQ1 --force-p2sh --passphrase --bip32-path "m/123'/345'/6545645'/0" --tokenlist testseed.txt --language en --mnemonic-length 12`
> 
> со списком токенов:
> 
> ```
> ^1^wine
> ^2^cash
> ^3^grant
> ^4^will
> ^5^wise
> ^6^west
> ^7^small
> ^8^relax
> ^9^occur
> ^10^rural
> ^11^matter 
> ^12^wagon
> ```
Thanks this works great. You said that you can turn off checksum checking in arguments for non-standard mnemonics, you can show it with an example.

**Comment by 3rdIteration** [comment]
Just add  --skip-worker-checksum and it should work... If you run with --no-eta you will notice it immediately runs 16x slower

**Comment by eLinkroad** [comment]
Yes, with --skip-worker-checksum everything works fine, I will send thanks to the wallet
