### ISSUE TITLE
Counting passwords killed

### ISSUE THREAD

**Issue by osoluche** [3rdIteration/btcrecover#250]
I've tried with 100gb passwords file, then die ...

$ python btcrecover.py --wallet wallet.dat  --passwordlist pwd_2021.txt --max-eta 999999
....
Counting passwords ...
  1,442,100,000  ETA: 20.1 days and counting   Killed

**Comment by 3rdIteration** [comment]
You will need no-dupchecks enabled unless you have more ram than the size of the passwordlist.
