### ISSUE TITLE
What do I have to use..

### ISSUE THREAD

**Issue by Djurrez** [3rdIteration/btcrecover#251]
Hey..

A friend of mine had a wallet in 2018. He doesn't know that much anymore. Only things he has got are 11 words of the seed phrase, written on a paper. Any chance we'll get this dead wallet alive with a AddressDB? There has been a moment that the money has been put onto a address, so there must be a transaction made around february 2018.

Thanks in advance :)

**Comment by 3rdIteration** [comment]
11/12 words, just using all the defaults and the latest Bitcoin address db could find a result in a few minutes. (You could try both BIP 39 and Electrum wallet types)
