### ISSUE TITLE
OpenCL Issue on seedrecover.py

### ISSUE THREAD

**Issue by Djurrez** [3rdIteration/btcrecover#252]
Getting this one:

C:\Users\**\AppData\Local\Programs\Python\Python39\lib\site-packages\pyopencl\__init__.py:266: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  warn("Non-empty compiler output encountered. Set the "

This error keeps spamming including some black screens.

At the end i'm recieving this one

C:\Users\**\PycharmProjects\RecoveryProject>C:\Users\**\AppData\Local\Programs\Python\Python39\lib\site-packages\pyopencl\__init__.py:266: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist.

Running a up-to-date 6900XT

**Comment by 3rdIteration** [comment]
Does it pass all the tests? No-empty compiler issue isn't always actually a problem.

**Comment by anywalletrecovery** [comment]
you can find lost word without enabling opencl

**Comment by anywalletrecovery** [comment]
you can easily find lost word without enabling opencl

**Comment by Djurrez** [comment]
I've used it without OpenCL, and it finally worked and got seedphrase back.
Since I did this for someone else, we found out that the account got scammed and lost 2,2 btc :(
Thx!

**Comment by 3rdIteration** [comment]
Bummer, sorry to hear that. Good job with the recovery though.
