### ISSUE TITLE
Issue with Dogechain.info

### ISSUE THREAD

**Issue by DrogonTheDragon** [3rdIteration/btcrecover#254]
I was trying to recover my dogecoin wallet from dogechain.info but it doesn't support --enable-GPU and gives me an error to try --enable-OpenCL. Do you plan to enable support for GPU? If not is there any way this hash can be taken to hashcat? I have tried every mode in hashcat and so far they all failed.

**Comment by 3rdIteration** [comment]
Unless someone sponsors it, GPU support won't be added for this dogechain.info (Most of the functionality is there, so it wouldn't be a large job, so wouldn't be a large expense)

**Comment by 3rdIteration** [comment]
added in https://github.com/3rdIteration/btcrecover/commit/71d0f0cbe58407d35172bb775ec887b823c441b9
