### ISSUE TITLE
coinomi password bruteforcing 

### ISSUE THREAD

**Issue by isieditors** [3rdIteration/btcrecover#257]
hi 
is there a way to use btcrecover in order to brutefoce coinomi password in android devices?

**Comment by 3rdIteration** [comment]
https://btcrecover.readthedocs.io/en/latest/TUTORIAL/#finding-coinomi-wallet-files

**Comment by isieditors** [comment]
thanks for all your help
i found it
I appreciate your kindness in helping me

**Comment by isieditors** [comment]
yes of course I will tip you when I get my fund out of coinomi. 
as I told you I was only successful in testing coinomi wallet

**Comment by anywalletrecovery** [comment]
we have found the wallet file. but bruteforcing is so slow and it doesn't support gpu or opencl acceleration. and cpu has rate of 80p/s
