### ISSUE TITLE
BIP 38 no used cpu. 

### ISSUE THREAD

**Issue by Noname400** [3rdIteration/btcrecover#259]
hi. 
I'm trying to run.
but my processors are not loaded.
what am I doing wrong ?

python btcrecover.py --bip38-enc-privkey 6PnM7h9sBC9EMZxLVsKzpafvBN8zjKp8MZj6h9mfvYEQRMkKBTPTyWZHHx --passwordlist  /media/user/SSD/777.txt --threads 128

Wallet Type: btcrpass.WalletBIP38
Wallet difficulty: sCrypt N=14, r=8, p=8
2021-10-07 12:59:02 : Using 128 worker threads
Notice: Loading File:  /media/user/SSD/777.txt                                  

MY CPU:
%Cpu(s):  0,1 us

**Comment by 3rdIteration** [comment]
So if you run 

`python btcrecover.py --bip38-enc-privkey 6PnM7h9sBC9EMZxLVsKzpafvBN8zjKp8MZj6h9mfvYEQRMkKBTPTyWZHHx --performance `

what happens? (On my system every logical processor goes to 100% usage and I get about 38 passwords per second. (i7 10700K)

**Comment by Noname400** [comment]
> why did you post your bip38 prv in public

This test key

**Comment by Noname400** [comment]
> So if you run
> 
> `python btcrecover.py --bip38-enc-privkey 6PnM7h9sBC9EMZxLVsKzpafvBN8zjKp8MZj6h9mfvYEQRMkKBTPTyWZHHx --performance `
> 
> what happens? (On my system every logical processor goes to 100% usage and I get about 38 passwords per second. (i7 10700K)

100 core speed 58 key sec
