### ISSUE TITLE
Add Support for Bitaddress Style Brainwallets

### ISSUE THREAD

**Issue by 3rdIteration** [3rdIteration/btcrecover#26]
These: https://www.bitaddress.org/bitaddress.org-v3.3.0-SHA256-dec17c07685e1870960903d8f58090475b25af946fe95a734f88408cef4aa194.html

Similar concept already done here: https://github.com/ryancdotorg/brainflayer

**Comment by 3rdIteration** [comment]
I actually have working code for this now for sha256(passphrase) brainwallets. (The most common type) 

Just want to double check that this capability doesn't make it easier to rob a bunch of previously safe brainwallets before pushing the code publically. (Though I figure that brainflayer has been in the public domain now for long enough for this not to be an issue)

**Comment by giantmonster** [comment]
That's great to hear! Do you have it working with a checksum? Brainflayer does not allow for a checksum. I've been piping btcrecover.py output to brainflayer and that is what I lack.

**Comment by 3rdIteration** [comment]
Do you have a checksum to check against? At the moment it's just checking
against addresses (or an address database) like with BIP 39 wallets. (So
you can just search for an addedssdb of funded addresses to avoid false
positives)

Do you have a link to reference wallet that implements this checksum
feature for your situation?

**Comment by giantmonster** [comment]
I think I may be wrong about this. Trying to remember events from 10 years ago. I have the list of words however I think what I stated as a checksum was actually encrypting the wallet.

**Comment by 3rdIteration** [comment]
sCrypt wallets that were available from around the end of 2013 had the
ability to add salt, the wallets from before this were generally just
sha256(passphrase) (And things like bitaddress still are...)

**Comment by 3rdIteration** [comment]
I should add that support is also there for these warpwallets, it is just much slower to test each password due to the presence of sCrypt.

**Comment by 3rdIteration** [comment]
@giantmonster I pushed the code to the repo, so feel free to give it a go. Just be aware that sCrypt is quite slow for the warpwallet type wallets. If you don't know your address, then your best bet is to use it with an AddressDB made up of addresses with balance. (I will have some docco that looks at how to make them coming out over the weekend)

**Comment by 3rdIteration** [comment]
Added with documentation as at https://github.com/3rdIteration/btcrecover/commit/661b3c8bb3469268f9910754df363262ff427b97
