### ISSUE TITLE
btcrecover wont run after xrp address is entered.

### ISSUE THREAD

**Issue by Jakevi** [3rdIteration/btcrecover#260]
![BTCRecover immediately after entering keepkey xrp address upon prompt](https://user-images.githubusercontent.com/34827039/136645738-46bbfd30-b142-463b-8dba-290f7d018ddf.png)

**Comment by 3rdIteration** [comment]
Can't reproduce, even without groestlecoin_hash installed.

Try with the following info:
Seed: vintage brass clump say vendor gas short orient mushroom version uniform pistol always punch leg
Address: rnFE7waRnxvkXdb9zeYyMKtF3y9KMV7M88

Does it work on your system?

**Comment by Jakevi** [comment]
Yea it sure did! But none of the addresses yielded the XRP address used! Does that mean anything?
![IMG_20211010_130325_895](https://user-images.githubusercontent.com/34827039/136683168-9ee38a8b-16e2-40c6-a380-e676e32bbabb.jpg)

**Comment by 3rdIteration** [comment]
When you get the error in your initial post, are you actually using an
address that looks like the one I posted...

**Comment by 3rdIteration** [comment]
I am asking exactly what address you entered to lead to the error message that you posted in the first screen...

**Comment by 3rdIteration** [comment]
That address is invalid... The software is working as expected...
