### ISSUE TITLE
Possible Password ==>....password......<== in Decrypted Block ==>{ "Z{Q xxxxxxxx<==

### ISSUE THREAD

**Issue by Sinhe1** [3rdIteration/btcrecover#263]
I used BTCrecover
password and block content I changed in this post.
password was found but when i login blockchain.com is not correct. What's wrong with my account?
account created in 2016 (blockchain.infor)
please help me!

Possible Password ==>....password......<== in Decrypted Block ==>{ "Z{Q xxxxxxxx<==

**Comment by Sinhe1** [comment]
> That is just random garbage, not the actual password.
Thanks!!
It has a word in it that I remember when I set the password. But it shows me the password up 32 characters, any hint from that random garbage or is it meaningless?

**Comment by 3rdIteration** [comment]
It's meaningless, random garbage... There is no such thing as a "close"
password or anything that would give you a hint that it's partially right.
