### ISSUE TITLE
Blockchain Wallet 2017

### ISSUE THREAD

**Issue by GSinatra** [3rdIteration/btcrecover#266]
Hi! I have a wallet for Blockchain.info 2017. It hasn't been used for a long time. Does this mean to recover my password? And another question, if the password is found, is it necessarily uploaded to the "possible password" file or can simply appear in the terminal when a certain amount of file is reached?

**Comment by 3rdIteration** [comment]
This will work on a 2017 wallet. The correct password will appear in both locations.
