### ISSUE TITLE
seedrecover boost suggestion

### ISSUE THREAD

**Issue by cryptoprogramer** [3rdIteration/btcrecover#267]
i have come across with some programs which are used to hunt for lost bitcoins.
these programs generate random 12 or 24 words and check if they have balance.
but these programs generate seeds much faster than seedrecover does.
one of the reasons is that use h160 instead of public address of btc and that reduces some tasks of the program and leads to faster performance. however, in seedrecover we are promoted to enter a public key or it load the public key from database.
i think changing public address to h160 may double its speed in generating seeds.

**Comment by 3rdIteration** [comment]
BTCRecover already uses hash160 for the checks, not the address.
