### ISSUE TITLE
Cannot save automatically after finding the password？

### ISSUE THREAD

**Issue by zhanshen360** [3rdIteration/btcrecover#270]
When btcrecover finds the password, it will not be automatically saved to the file
Will only print on the screen
Request to add the related function of automatically saving the password to the file

**Comment by vishalkumar2806** [comment]
I fixed that issue it gonna send password and updates to telegram bot

**Comment by vishalkumar2806** [comment]
check this repo https://github.com/vishalkumar2806/btcrecover

**Comment by zhanshen360** [comment]
I mean save it locally

**Comment by zhanshen360** [comment]
I mean save it locally

**Comment by zhanshen360** [comment]
Sending over the network will reveal password information

**Comment by 3rdIteration** [comment]
Closed as stale issue
