### ISSUE TITLE
Electrum 4.1.5 btcrecover.py not recognising wallet

### ISSUE THREAD

**Issue by ChadleyManhorse** [3rdIteration/btcrecover#283]
I've followed all the instructions but every time I run the final script I get  IOError: [Errno 2] No such file or directory: 'wallet.file' with everything else seeming fine. It is there & is the right one as described in the guide

I'm a complete noob, borderline boomer at this stuff but I can usually muddle through with clear enough guidance, have I missed some bit that says it won't work for my version? because it looks like I'm doing everything I'm told.

I got sidelined between transferring some GBP to BTC & doing the transaction & somehow managed to forget the new password & not write down the seed & though it's less than £100 worth of crypto I could do with the money but it's not enough to pay someone to do it for me, I've got this far & don't know where to go from here but am not giving up yet.

Does anyone know what's wrong or if there's another way to do this as I'm stumped

**Comment by 3rdIteration** [comment]
I can't reproduce this, just tested with an Electrum 4.1.5 wallet file and it worked fine.

You should be able to just paste the following command in your BTCRecover folder:
python btcrecover.py --wallet ./btcrecover/test/test-wallets/electrum41-wallet --passwordlist ./docs/Usage_Examples/common_passwordlist.txt

Basically this will test against a wallet file and passwordlst that is bundled with BTCRecover

You can then just edit the command from there.
