### ISSUE TITLE
btcrecover blockchain-github-v1-1 blockchain-github-v1-2 blockchain-github-v1-3

### ISSUE THREAD

**Issue by shoutmarble** [3rdIteration/btcrecover#284]
How do I verify the passwords to these blockchain wallets

btcrecover.py doesn't recover these test wallets with these settings.

Below is my attempt at recovering the following wallets
1. **[blockchain-github-v1-1](https://github.com/3rdIteration/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-github-v1-1 "blockchain-github-v1-1")**
2. **[blockchain-github-v1-2](https://github.com/3rdIteration/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-github-v1-2 "blockchain-github-v1-2")**
3. **[blockchain-github-v1-3](https://github.com/3rdIteration/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-github-v1-3 "blockchain-github-v1-3")**

> Password : 'btcr-test-password'???

------------

### Recovery Attempt on blockchain-github-v1-1 WALLET

> https://github.com/3rdIteration/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-github-v1-1

Running btcrecover.py on blockchain-github-v1-1

    $ python btcrecover.py --wallet btcrecover/test/test-wallets/blockchain-github-v1-1 --typos-capslock --tokenlist ./docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/tokenListTest.txt

Output
> **All possible passwords (as specified in your tokenlist or passwordlist) have been checked and none are correct for this wallet. You could consider trying again with a different password list or expanded tokenlist...

### Recovery Attempt on blockchain-github-v1-2 WALLET

> https://github.com/3rdIteration/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-github-v1-2

Running btcrecover.py on blockchain-github-v1-2

    $ python btcrecover.py --wallet btcrecover/test/test-wallets/blockchain-github-v1-2 --typos-capslock --tokenlist ./docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/tokenListTest.txt

Output:

> **All possible passwords (as specified in your tokenlist or passwordlist) have been checked and none are correct for this wallet. You could consider trying again with a different password list or expanded tokenlist...

------------

### Recovery Attempt on blockchain-github-v1-3 WALLET

> https://github.com/3rdIteration/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-github-v1-3

    $ python btcrecover.py --wallet btcrecover/test/test-wallets/blockchain-github-v1-3 --typos-capslock --tokenlist ./docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/tokenListTest.txt

Output:

> **All possible passwords (as specified in your tokenlist or passwordlist) have been checked and none are correct for this wallet. You could consider trying again with a different password list or expanded tokenlist...

------------

### SUCCESSFUL btcrecovery on blockchain-v0.0-wallet.aes.json WALLET

[https://github.com/3rdIteration/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-v0.0-wallet.aes.json](https://github.com/3rdIteration/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-v0.0-wallet.aes.json "https://github.com/3rdIteration/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-v0.0-wallet.aes.json")

    $ python btcrecover.py --wallet btcrecover/test/test-wallets/blockchain-v0.0-wallet.aes.json --typos-capslock --tokenlist ./docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/tokenListTest.txt

> Password found: 'btcr-test-password'

Recovery with Hashcat
Get Hash

    $ python2 blockchain2john.py --base64 btcrecover/test/test-wallets/blockchain-v0.0-wallet.aes.json

Run hashcat with hashcode

    hashcat -w 3 -S --session HCSession -m 12700 -o password.txt -a 3 BCV0.HASH INCR_MASK.hcmask

Password: 'btcr-test-password'

------------

### SUCCESSFUL btcrecovery on blockchain-v2.0-wallet.aes.json WALLET

[https://github.com/3rdIteration/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json](https://github.com/3rdIteration/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json "https://github.com/3rdIteration/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json")

    $ python btcrecover.py --wallet btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json --typos-capslock --tokenlist ./docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/tokenListTest.txt

> Password found: 'btcr-test-password'

    $ python2 blockchain2john.py --json btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json

Hashcat

    hashcat -w 3 -S --session HCSession -m 15200 -o password.txt -a 3 BCV2.HASH INCR_MASK.hcmask

> Password: 'btcr-test-password'

**Comment by shoutmarble** [comment]
I found this that works


[blockchain-github-v1-1](https://github.com/3rdIteration/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-github-v1-1 "blockchain-github-v1-1")


    $ python btcrecover.py --wallet ./btcrecover/test/test-wallets/blockchain-github-v1-1 --dump-wallet blockchain-github-v1-1_main_dump.txt --correct-wallet-password mypassword

> blockchain-github-v1-1_main_dump.txt

**Comment by shoutmarble** [comment]
I verified that blockchain2john.py makes a correct hash for blockchain-github-v1-1

    $ python2 blockchain2john.py --base64 blockchain-github-v1-1

Hashcat works with "mypassword"

    hashcat -w 3 -S --session HCSession -m 12700 -o password.txt -a 3 bcgv11.hash INCR_MASK.hcmask

**Comment by 3rdIteration** [comment]
They are all just in test-passwords.py and are automatically tested when you run all tests
