### ISSUE TITLE
Running into error in seed recovery

### ISSUE THREAD

**Issue by Kaytay1229** [3rdIteration/btcrecover#285]
Hey there!

After selecting my wallet type in the seed recovery process, the next step is to be asked for my master public key. Instead of this step, I'm getting a FileNotFoundError: Errno 2 No such file or directory: './derivationpath-lists/BTC.txt' message in Terminal.

I do see this file in the derivationpath-lists folder so not sure why I'm receiving this message and unable to proceed?

Any help is much appreciated.

**Comment by anywalletrecovery** [comment]
this can be an error due to the commands you have included in command line

**Comment by 3rdIteration** [comment]
Make sure you run the BTCRecover command from within the BTCRecover folder or a number of relative file locations will break.
