### ISSUE TITLE
invalid seed with known passphrase

### ISSUE THREAD

**Issue by dderder** [3rdIteration/btcrecover#286]
Thank you for maintaining this excellent tool!

I can't wrap my head around the issue I'm having:

This all happened today. I wrote down this 24 word seed that is invalid even though I triple checked it and all the words are in the BIP39 word list. The checksum doesn't match. I also checked the order so that can't be the issue.

I've tried Seed Savior to look for other words (with the ?) to make the checksum match in all 24 positions and none of the options resemble the words that I have, so a typo is also not the issue.
The only address that I have here holds Stellar XLM and that get rejected by the tool as it's probably not supported.

Part 2:
With the same seed I had also added a (25th word) passphrase. This I have written down in front of me so I don't need to look for that.
I transferred some BTC (luckily not a lot) to the legacy segwit address derived from that and that is the second and last address that I have. So both are in different trees (with and without passphrase)

Finally I decided to simulate losing the wallet and (stupidly) deleted all traces as I was 100% certain that the word list was good...

So now I'm trying to get the tool to find out what is wrong with the 24 words but I can't get it to work.
Is there a way to give the tool the invalid seed, the valid passphrase and the valid BTC address and have it find out what's wrong with the seed word list?

Thank you!

**Comment by nopd11** [comment]
I can help you
Telegram @seniorq1

**Comment by 3rdIteration** [comment]
Yep, just use seedrecover.py with the --passphrase argument

Stellar support could also be added quite easily if you want to either have a crack at doing it or sponsor it.

**Comment by coded00guy** [comment]
> Yep, just use seedrecover.py with the --passphrase argument
> 
> Stellar support could also be added quite easily if you want to either have a crack at doing it or sponsor it.

Sir is algo wallet support yet?

**Comment by 3rdIteration** [comment]
No, but it can be added if you want to sponsor it

**Comment by 3rdIteration** [comment]
> > Yep, just use seedrecover.py with the --passphrase argument
> > Stellar support could also be added quite easily if you want to either have a crack at doing it or sponsor it.
> 
> Sir is algo wallet support yet?

No but it can be added if you want to sponsor it

**Comment by dderder** [comment]
> Yep, just use seedrecover.py with the --passphrase argument
> 
> Stellar support could also be added quite easily if you want to either have a crack at doing it or sponsor it.

Thanks so much for your help.
The --passphrase argument works great but unfortunately the program can't find the seed.

I've already spent way too much time on this as there are just two test amounts of 10 dollars each on that wallet but I find it hard to let it go. Like a spy mystery novel, I really want to know what happened. 

How can I write down 24 words, check them and then discover that there is an error, while all 24 are in the bip39 wordlist? and the program can't find anything... I know that noone can answer that question and it must be user error, but I just can't imagine how.

Also I want to learn from this and understand what went wrong.

I have some coding background and should be able to adapt the code for Stellar and do the recovery without the passphrase but there are so many files to start digging through. I don't have the experience in this language to quickly find the hierarchy.  Could you point me in the right direction please? I already found the path for Stellar in my wallet: "44'/148'/0'"

Alternatively or if I have to give up in the end, would it be ok if I post my seed phrase here? That way you or someone else can do the challenge and get the small amount of money in there. I only want to know what happened. :-)

**Comment by 3rdIteration** [comment]
This will just be user error for the BTC wallet. Are you just leaving all the other arguments as the defaults? (None should be required other than the passphrase argument) 

You could post the test seed and command you are trying here, or email them to be directly (steve@cryptoguide.tips) as it's likely to be a straightforward mistake.

For Stella, it's part of the py_crypto_hd_wallet module, so adding support is straightforward, basically the same as the Cosmos PR that I haven't yet merged. (Just need to add the CI tests, docco, etc)

**Comment by dderder** [comment]
Problem solved! I made a pull request for the Stellar code and sent you an email about it. Thanks!

**Comment by 3rdIteration** [comment]
I saw that, thanks for the PR. :)

I'll review the stuff you mentioned and also add the example accounts as
usage examples.

The py_crypto_hd_wallet actually supports a very wide range of coins. It's
great that it finally has a stable release, it will take a few months to go
through and add in all the supported coins, but it's good that it's simple
enough for folk to work out "on demand" as well.
