### ISSUE TITLE
Trezor T passphrase

### ISSUE THREAD

**Issue by python-force** [3rdIteration/btcrecover#287]
Does btcrecover support Shamir (SLIP39) mnemonic?

**Comment by 3rdIteration** [comment]
Not currently. A few folks have asked about it, but no-one has gone ahead and sponsored it yet.

**Comment by python-force** [comment]
@3rdIteration Thank you for info, I found interface issue (not bug) in Exodus when you using Trezor T and you can lock your wallet without knowing it - fortunately I know how to code so took me 2 days to recover but I know people will have issue with it and I have reported it to Exodus, in the meantime I have tested the btcrecover and seedrecover scripts - awesome work played with it the whole day, SLIP39 would great to have.

**Comment by 3rdIteration** [comment]
There are Python SLIP39 implementations that already exist, so it wouldn't be difficult to implement if you want to bring a PR.

**Comment by python-force** [comment]
I'll leave to more professional people who work with crypto everyday - but can always try and test it when I would have time - awesome there is python SLIP39 nice
