### ISSUE TITLE
Add Bitcoin Taproot address support

### ISSUE THREAD

**Issue by 3rdIteration** [3rdIteration/btcrecover#288]
As per https://github.com/bitcoin/bips/blob/master/bip-0086.mediawiki

**Comment by kaiwolfram** [comment]
It does not look like someone is working on it. Do you know of a btcrecover fork which supports taproot? I sinked some sats on a wallet with mistyped passphrase 😬

**Comment by 3rdIteration** [comment]
Not done yet. If you are in a hurry, you could just add it in the same way that wallets from py-crypto-hd-wallet are supported

**Comment by Stonk8** [comment]
+1

**Comment by 3rdIteration** [comment]
Added in https://github.com/3rdIteration/btcrecover/commit/3ece6da157c43e185f349a4f9b3362b16f617230
