### ISSUE TITLE
Unable to Recover solana wallet

### ISSUE THREAD

**Issue by coded00guy** [3rdIteration/btcrecover#292]
I tried to do seedrecovery for a solana wallet and was prompt to install py_crypto_hd_wallet_  the code gave the error below. i have Microsoft visual studio installed. kindly help with a f
![Screenshot (274)](https://user-images.githubusercontent.com/58042898/143725845-7c384f38-915f-495e-9e61-e704eb18e1bb.png)
ix

**Comment by 3rdIteration** [comment]
You need to do what it says.... Install the build tools... (Not just visual studio)
