### ISSUE TITLE
cannot run seedrecover.py for solana wallet

### ISSUE THREAD

**Issue by coded00guy** [3rdIteration/btcrecover#296]
when i tried running seedrecover.py for my solana wallet I get a prompt to install py_crypto_hd_wallet when I attempt to do that I get this error. can someone assist in telling me what exactly  to do and how to do it
![Screenshot (276)](https://user-images.githubusercontent.com/58042898/144939312-b1a81f1c-9b43-4579-9986-80b065741bc6.png)
?

**Comment by 3rdIteration** [comment]
You need to install all the Microsoft visual c++ resources, just all the defaults are fine, it's about 6gb.

**Comment by coded00guy** [comment]
![image](https://user-images.githubusercontent.com/58042898/146328553-b6f9dafd-7b1a-49f9-8605-7e5b1274b2b1.png)
 installing this will solve the problem?

**Comment by 3rdIteration** [comment]
That's the right installer, but you need the c++ stuff selected, not .net

**Comment by coded00guy** [comment]
Thank you so much. all done
