### ISSUE TITLE
I only know first 11 of 12 seed words from my BIP39

### ISSUE THREAD

**Issue by magic0x00** [3rdIteration/btcrecover#297]
My hard drive failed where my wallet was stored and I only had 11 of 12 words saved from my Exodus wallet. Just my luck.

I don't even remember my addresses and searched blockchain.info but there's too many wallets with similar amounts of BTC I had out there, so I think I'm shit out of luck.

Because it's only 1 word can't I create a token file that tries every possible word for BIP39 for the 12th place? Every time I --listpass it only shows 1 combination with 11 words, not 12.

**Comment by 3rdIteration** [comment]
Just use the Bitcoin address database with the 11 words your have and leave everything else as the defaults, it will find the correct seed in a few seconds.

**Comment by johnjames333** [comment]
@magic0x00 
I just read your problem with your BIP39 recovery phrase. in the past I have recovered BIP39 words.
and if you still has problem I can help. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333
