### ISSUE TITLE
database problem

### ISSUE THREAD

**Issue by ramin1234** [3rdIteration/btcrecover#298]
I want to see all addresses of ethereum  .I downloaded this file but I can't open it with sqlite .
https://cryptoguide.tips/btcrecover-addressdbs/
how can i see all the addresses? is there any software to see rows
thanks alot

**Comment by 3rdIteration** [comment]
It's not an Sqlite file, nor does it store the actual addresses themselves... If you want a list of addresses, just follow the documentation and get it directly from Google Bigquery...
