### ISSUE TITLE
I just listed 21 out of 24 seedphrase of my Trezor

### ISSUE THREAD

**Issue by Policarpz** [3rdIteration/btcrecover#299]

**Comment by Policarpz** [comment]
I do not know what happened I am not aware at first that the default seephrase for Trezor One is 24 words and somehow I listed only 21.

**Comment by 3rdIteration** [comment]
You are missing three words, basically unless you can work out which words are missing you won't be able to recover. Best bet is to just assume it is the first or last three...

**Comment by johnjames333** [comment]
@Policarpz 
I just read your problem with your BIP39 recovery phrase. in the past I have recovered BIP39 words.
and if you still has problem I can help. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333
