### ISSUE TITLE
Helium With 12 Words Well Known Positions and letters

### ISSUE THREAD

**Issue by jeanmouawad** [3rdIteration/btcrecover#302]
Helium With 12 Words Well Known Positions ( 4 fully known words and 8 i have first two letters )

**Comment by 3rdIteration** [comment]
Yep, just use a tokenlist...

**Comment by jeanmouawad** [comment]
Can you help me more !

**Comment by 3rdIteration** [comment]
Not here...

If you want free support then just ask in the comments section of my YouTube channel, if you want one-on-one help then you can request a paid session. Price, process, terms and request form are here: https://cryptoguide.tips/recovery-services-consultations/

**Comment by johnjames333** [comment]
@jeanmouawad 
I just read your problem with your BIP39 recovery phrase. in the past I have recovered BIP39 words.
and if you still has problem I can help. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by jeanmouawad** [comment]
Hello i have two wallets with 12 words and can t make it to find the wrong
words can you assist me ?
I tried contacting on telegram no one there
Jean Mouawad
Engineer
+96176523441
| +9611681715
| ***@***.***
Sabtieh, El Maten, Lebanon
<https://maps.google.com/?q=Sabtieh,%20El%20Maten,%20Lebanon>
Linkedin: https://www.linkedin.com/in/jean-mouawad/

**Comment by 3rdIteration** [comment]
Telegram isn't checked unless it is being specifically used for a recovery.

If you want a consult then complete the webform here
https://cryptoguide.tips/recovery-services-consultations/
