### ISSUE TITLE
Algorand wallets

### ISSUE THREAD

**Issue by coded00guy** [3rdIteration/btcrecover#305]
Kindly add algorand wallet implemtntations

**Comment by 3rdIteration** [comment]
There is a script that can do this in the repo, otherwise it can be added either as a direct sponsorship or trusted recovery.

**Comment by coded00guy** [comment]
Pls can you put me through on how to use that script and where to find it

**Comment by 3rdIteration** [comment]
https://github.com/3rdIteration/btcrecover/blob/master/utilities/algorand_recovery.py

**Comment by 3rdIteration** [comment]
If you need something more functional then you will need to sponsor it
