### ISSUE TITLE
--possible-password-file parameter

### ISSUE THREAD

**Issue by aliriahy** [3rdIteration/btcrecover#311]
Hi Good day
I have a question about the parameter --possible-passwords-file and how it works
Thank you for your explanation
Does this parameter work for Bitcoincore wallet (wallet.dat)?
And the values that are logged can be close passwords?
Where can I find a complete document about this parameter?

**Comment by aliriahy** [comment]
Thank you for your help

**Comment by 3rdIteration** [comment]
That file is only relevant for wallets that rely on looking for a specific text string I'm the decrypted wallet data. (Blockchain.com, Metamask, dogechain) The only function it serves for these wallets is making it easier to support these types of wallets when vendors change things, or if someone has an older, non -standard wallet file, they can still both find the password and submit the string that was produced. (Without needing to share any private data from their wallet)

It isn't relevant to Bitcoin Core.
