### ISSUE TITLE
Can't seem to make it work using portable electrum 4.1.5 wallet file, I am probably doing something wrong.

### ISSUE THREAD

**Issue by Pandalism** [3rdIteration/btcrecover#312]
Hi apologies if i am fundamentally misunderstanding something but I have a test wallet created in portable electrum which doesnt seem to want to unlock even when I explicitly give it the right password.

Created using Portable Electrum 4.1.5, Standard Wallet, Create New Seed, wallet file is encrypted with a dummy password (test12345)

I check and it unlocks just fine using portable electrum.

Create a token file
```
test
1
2
3
4
5
```

Create a passwordlist file
```
test12345
```

I tested with both:
`python btcrecover.py --wallet test415wallet --passwordlist pass415.txt`
and
`python btcrecover.py --wallet test415wallet --tokenlist token415.txt`

To no avail. Am I doing something wrong?

[pass415.txt](https://github.com/3rdIteration/btcrecover/files/7840360/pass415.txt)
[token415.txt](https://github.com/3rdIteration/btcrecover/files/7840361/token415.txt)
[test415wallet.txt](https://github.com/3rdIteration/btcrecover/files/7840366/test415wallet.txt) (Remove the '.txt.')

**Comment by 3rdIteration** [comment]
Should work fine, have you tried with any of the Electrum wallets bundled with the repo? 

Also be sure to run the latest code from the master branch, not the latest release

**Comment by Pandalism** [comment]
Apologies, Issue was I was using last Tagged version not master branch.

Thank you!
