### ISSUE TITLE
pip3 install py_crypto_hd_wallet doesn't working

### ISSUE THREAD

**Issue by ValyDCV** [3rdIteration/btcrecover#313]
i cant install this to recover my solana wallet on phantom. It says "Command errored out with exit status 1"
any help please 
![Screenshot (2)](https://user-images.githubusercontent.com/97633064/149230060-2edf4a44-a00b-4504-bec6-52f8d47f7fc5.png)
?

**Comment by 3rdIteration** [comment]
The instructions for how to fix this are in the error message
