### ISSUE TITLE
ADDRESSDB SEARCH with pyopencl

### ISSUE THREAD

**Issue by vishalkumar2806** [3rdIteration/btcrecover#314]
I have some address and i want to search them on database on blockchain. Can you please tell me how can i do that

**Comment by 3rdIteration** [comment]
Both of these functions work independently of one another and can be used together just fine. Have a read of the documentation and the videos on my YouTube channel that run through them.

See the playlist that includes all of them here:
https://www.youtube.com/playlist?list=PL7rfJxwogDzmd1IanPrmlTg3ewAIq-BZJ
