### ISSUE TITLE
Electrum 24 word seed recovery.

### ISSUE THREAD

**Issue by Riccardo-Moroni** [3rdIteration/btcrecover#315]
Hi, and thanks in advance for spending your time reading this.

How can I make seedecover.py work with a 24 word seed for an Electrum 2.x wallet ?
When creating an Electrum wallet there's an option which let you add as many words as you want to (from the bip39 file) to the 12 words of the seed he automatically generate, allowing you to create a 24 word seed.
I know 22 words of it in their exact order, so it shouldn't take too much time right?
The seed's words are from bip39, which has 2048 words, it should try them all in the 2 exact positions leaving the 22 others where they are (more or less 4M possibilities).

I made another Electrum wallet, with a 12 word seed, and, replacing 2 words with "?" it managed to recover those 2 words I omitted. So I guess that at least the setup is done right.

I dont' have the public key but I have the address of this wallet, it's a native segwit one.

For Electrum 2.x the command `--mnemonic-length 24`  make it returns `maximum mnemonic length for Electrum2 is 13 words.`.

Is there any way to do so?

Thanks,
Riccardo

**Comment by 3rdIteration** [comment]
This is a 12 word seed with a long passphrase "extra words". Whether it is simple or not will depend on where the missing words are from. (The seed or passphrase)
