### ISSUE TITLE
NEW FEATURES IDEAS

### ISSUE THREAD

**Issue by cezarlacatus** [3rdIteration/btcrecover#32]
Hello, I have some sugestions to make:

First of all one feature that would come in handy would be to somehow store the seed combinations in a file while they are generating.Letme tell you my use case: Let's say I want to bruteforce 1,000,000,000 seed combinations,but my computer is slow.I would let my computer to generate the file contaning those 1,000,000,000 combinations and I would upload the software + the file that I need to be bruteforced to a high end vps (that I have to pay/hour).

In this way I don't need to generate 1,000,000,000 combinations on the vps and pay several hours for a task that my computer can do in the same time.

The other suggestion that I have is not so important, but it would help crypto-puzzle hunters a lot in bruteforcing.It would be to implement some special filters while bruteforcing with an unknown word like:
- The final seed won't exceed X letters
- The final seed would contain X time the letter "A" or "B"
- Etc....

Personally, the first ideea would be the most helpfull......but I don't know if it can be done....

**Comment by jonathancross** [comment]
In your VPS example, I suspect that reading seed combos from a file will probably be the same speed or slower than changing the order as the software runs.

**Comment by cezarlacatus** [comment]
@jonathancross Ok than I have another ideea for this.I think this is a good one and I think this will add the posibility to scale seedrecover and btcrecover almot to infinite.
Here is my scenario: I try to bruteforce a 12 word seeds where I know the order but I don't know 3 seed words.Well, let's say I have a verry slow computer, but I may rent some Vps.Right now with this version of seedrecover.py I can only run 1 instance of let's say 48 core linda node.It would take maybe a day or 2 to crack 8,589,934,592 seed keys.Well, maybe that's ok, but let's see if we can do things different:

What if there is an update that will allow to run a server on my pc and some slaves on the VPS like this:
`python3 seedrecover.py --no-dupchecks --mnemonic-length 12 --language EN --dsw --wallet-type BIP39 --addr-limit 6 --addrs 3HX5tttedDehKWTTGpxaPAbo157fnjn89s --tokenlist test.txt --listen 9999 --use-this-computer false --number-slaves 3`


Output: 

```
2020-06-05 16:06:54 : Starting server...
2020-06-05 16:06:54 : Please run the following command on the other machines: python3 seedrecover.py --connect IP:9999
2020-06-05 16:06:54 : Seed Generator will start after 3 machines are connected
```

Then after we run python3 seedrecover.py --connect IP:9999 on the 3 VPS(Note that we have specified there the nr of slaves aka VPS Machines required to start this), the server will start generating combinations and distribute seeds combinations equally to their slaves in form of chunks.


ADVANTAGES:

1)Imagine the use of  Gpu Miners as wallet crackers and also as seed crackers.With this you can extend the btcrecover module as much as the hardware permit.THIS IS THE MAIN USE OF THIS FEATURE.People can use their old laptops and other computers in their house and in total gain several cpu power(and also gpu).
2)MEMORY ISSUES Solved: Yeah, right, your computer may only have 4 Gb of ram, it sucks.Now, if you run the server, the memory won't get overloaded as there is no need to store the seeds on the master server.However you may consider doing --use-this-computer true while you set up the server.In this case the server won't get loaded with the combinations that were sended to the slaves.It will load only the seeds needed only on the server.
3)Output: In the current version you will manually need to configure btcrecover on multiple machines.Moreover you will always need to check the response on multiple windows.With this feature you can have all the statistics displayed on the server console.Everything from performance ,eta status/machine, and many other including the correct seed phrase

FUTURE UPDATES:
Le's see how far can we go:
1)You can update this with a feature that will benchmark each individual slave and the server will distribute the number of combination based to the computer performance.In this way you can add your old 4 cpu laptop and also a 48 core processor machine.The server will distribute the combination based to their performance(In this case the 48 core will take most of the words).
2)Another nice update would be to connect the slaves AFTER the combination list is finished.Let's say it may take 4-5 hours to make a combination list.If we plan to crack on 48 core Linda nodes, it may be costly as you would need to wait 4-5 hour just to generate the list(5$/node).So this can work in the following way: 
-Server Generates the List
-Server Finish Generating The List: OUTPUT: X Total Seed Combinations.Waiting to connect the 3 slaves now(number specified by --number-slaves 3)
-User now will start each VPS then it will run the connection command
-The server will separate the seedlist into chunks then it will start sending them to the slaves


You are the only one maintaining btcrecover for now.This feature will make the best bruteforcer tool ever made.I don't think is hard to implement as the cracker script is exponentialy harder than a simple client-server script....

I cannot wait to hear your answer
