### ISSUE TITLE
test_metamask_chrome_leveldb_OpenCL_Brute

### ISSUE THREAD

**Issue by xlameee** [3rdIteration/btcrecover#320]
I am using Python 3.9
pyopencl-2021.2.9+cl12-cp39-cp39-win_amd64.whl
AMD Firepro W8000
Windows 10 Ver.1709

I was running python run-all-tests.py -vv

When it gets to "test_metamask_chrome_leveldb_OpenCL_Brute"

I received Python stopped working. Close the program

Before I install pyopencl-2021.2.9+cl12-cp39-cp39-win_amd64.whl all test OK except OPENCL

any idea.

EDIT: but when I brute-force my Bitcoin core wallet with  --enable-gpu argument I have no problem it is working
but I am not sure that it is working with its full potential.

**Comment by 3rdIteration** [comment]
The OpenCL and GPU kernels are different and Bitcoin core works best with the one that is used through --enable-gpu

**Comment by xlameee** [comment]
OK, but why Python stopped working. Close the program. my gpu supports OPENCL 1.2 ?

**Comment by 3rdIteration** [comment]
Just try running a recovery on one of the Metamask wallet with OpenCL enabled and you might get something more useful.
