### ISSUE TITLE
Spaces inside $[...] wildcard not correctly processed

### ISSUE THREAD

**Issue by jandr** [3rdIteration/btcrecover#321]
According to the documentation, any character inside `$[ ]` would be used as-is, including spaces:

> %[chars] - exactly 1 of the characters between [ and ] (e.g. either a c, h, a, r, or s) Note: All characters in this wildcard are used as-is, even if that character would normally have its own wildcard if used as a token, like space, $, % or ^

However, having in a token list the following tokens, so either a space or a period ("."), or either a space or a "T" is used, result in errors:

```
$[ .]
$[T ]
```

The error looks like the following one:

`Error: on line 2: invalid wildcard (%) syntax (use %% to escape a %)`

Cloud this be reviewed in the code if it is a bug, or clarified in the documentation if the space is not treated as such within the `$[ ]` ? 

>

**Comment by 3rdIteration** [comment]
Thanks for the report, have checked and replicated this

**Comment by 3rdIteration** [comment]
Fixed in https://github.com/3rdIteration/btcrecover/commit/08fc2c0a277f17e7777c5355c027c87efb8e0c13
