### ISSUE TITLE
ccl_chrome_indexeddb library

### ISSUE THREAD

**Issue by RickDeckcard** [3rdIteration/btcrecover#323]
Good day, and congratulations, a good tool.

I am trying to recover a metamask wallet but appear the next error (in differents wallets).

In the folder datos_wallet is all the Metamask files

python3 "C:\Users\MyUser\Desktop\BTCRECOVER\btcrecover-master2\btcrecover-master\extract-scripts\extract-metamask-vaults.py" ./datos_wallet

Traceback (most recent call last):
  File "C:\Users\MyUser\Desktop\BTCRECOVER\btcrecover-master2\btcrecover-master\extract-scripts\extract-metamask-vaults.py", line 27, in <module>
    from lib.ccl_chrome_indexeddb import ccl_leveldb
ModuleNotFoundError: No module named 'lib'

I have tried to install a ccl_chrome_indexeddb library but isn´t in pypi. I have found in github but i dont undertand how install it.

**Comment by RickDeckcard** [comment]
Ok, all ok now. I answer myself. The problem was with pip and pip3. I unistall all dependencies and python 3.9, install again and all ok now.

**Comment by 3rdIteration** [comment]
Good job getting it sorted
