### ISSUE TITLE
Error again with Microsoft Visual C++

### ISSUE THREAD

**Issue by RickDeckcard** [3rdIteration/btcrecover#327]
Well, the software work very good, but some extra-scripts dont work. I am trying install requirements-full.txt but some packages have the next error:

error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

I have installed, unistalled and reinstalled the Microsoft Visual Studio with standard options and with all options. I have trying install the Redistribuible C++ too, but dont repair the problem.

Well, any idea?
Thanks.

**Comment by 3rdIteration** [comment]
You didn't install it correctly, you will need to try again. All the defaults should be fine, it's about 6gb.

Alternatively you can just boot Ubuntu, it's a simpler process.
