### ISSUE TITLE
Scrambled 12 seed phrase Solana

### ISSUE THREAD

**Issue by Nesfruita** [3rdIteration/btcrecover#331]
I have the 12 words for the wallet’s seed phrase unfortunately its all scrambled up. Should I do seedrecovery.py —big-typos 12 ?

**Comment by isieditors** [comment]
@Nesfruita 
for your short and unclear question, you expect a thorough answer?

**Comment by Nesfruita** [comment]
> 

ohh sorry will make it clear

**Comment by 3rdIteration** [comment]
Follow the example here https://btcrecover.readthedocs.io/en/latest/Usage_Examples/2020-05-02_Descrambling_a_12_word_seed/Example_Descrambling_a_12_word_seed/
