### ISSUE TITLE
160.03 kP/s is it good speed ?

### ISSUE THREAD

**Issue by senatorr3za** [3rdIteration/btcrecover#335]
PS D:\000> python seedrecover.py --enable-opencl --no-dupchecks --language EN --dsw --big-typo 24 --wallet-type ethereum  --mnemonic-length 12 --addr-limit 1 --bip32-path "m/44'/60'/0'/0" --no-eta --addressdb ./addresses.db

Starting seedrecover 1.11.0-CryptoGuide, btcrecover 1.11.0-Cryptoguide on Python 3.9.10 64-bit, 21-bit unicodes, 64-bit ints
Loading address database ...
Loaded 6856253 addresses from database ...
Using the 'en' wordlist.
Seed sentence was too long, deleting 12 words from each guess.
OpenCL: Auto Selecting Best Platform
Initial seed guess has a valid checksum (6.2% chance).
2022-03-26 21:17:01 : Phase 1/1: up to 24 mistakes, 24 of which can be an entirely different seed word.

OpenCL: Available Platforms
Platform 0 - Name NVIDIA CUDA, Vendor NVIDIA Corporation
Platform 1 - Name Intel(R) OpenCL HD Graphics, Vendor Intel(R) Corporation

OpenCL: Auto Selecting Best Platform
OpenCL: Using Platform: 0
OpenCL: Using Work Group Size:  51200

Wallet Type: btcrseed.WalletEthereum
2022-03-26 21:17:01 : Using 12 worker threads
| 1390028800  elapsed: 2:24:46  rate: 160.03 kP/s

**Comment by 3rdIteration** [comment]
Yes
