### ISSUE TITLE
Create Eth Address DB Directly from Full Node Data (For Eth and BSC)

### ISSUE THREAD

**Issue by kipilk0** [3rdIteration/btcrecover#341]
How to create addressdb-ETH from GETH full node ? is it possible? also looking for BSC addresses db

**Comment by 3rdIteration** [comment]
There is currently no way to do this, as Eth address DBs are currently based on the Google BigQuery data. (You could try creating your own dataset for a BSC node with https://github.com/blockchain-etl/ethereum-etl)

**Comment by 3rdIteration** [comment]
Process to do this with Ethereum-ETL is now in the documentation.
