### ISSUE TITLE
Token List

### ISSUE THREAD

**Issue by coded00guy** [3rdIteration/btcrecover#345]
Assume i have a token list that is like this
1. OverTheBar
2. Overthebar
3. OverThebar
4. overTheBAR
 how can I make a single token list where I can put an instruction to capitalize certain words like; capitalize the third letter only.
without using --typos-case which will capitalize each word in each iteration (which takes more time)

**Comment by 3rdIteration** [comment]
There is currently no way to peg capitalisation to a specific character or position. (Other than using rwgex to filter out potential passwords that don't meet the requirements)
