### ISSUE TITLE
REQUEST: I want to crack multiple wallet using same wordlist so that I dont have to put them again and again

### ISSUE THREAD

**Issue by vishalkumar2806** [3rdIteration/btcrecover#350]
BRO PLEASE UPDATE THE  CRACKER SO THAT I CAN PUT MULTIPLE WALLET IN A SINGLE WORDLIST

**Comment by 3rdIteration** [comment]
I don't see the point, but if you want to bring a PR then I am happy to merge it.

**Comment by vishalkumar2806** [comment]
bro imean I have multiple wallets like two three wallets and i want to recover them with a single wordlist if i try the normal process i have to put my computational power three times to crack three wallet for a single wordlist. I want that i can put multiple wallets as input and run the process only one times

**Comment by vishalkumar2806** [comment]
> I don't see the point, but if you want to bring a PR then I am happy to merge it.
bro imean I have multiple wallets like two three wallets and i want to recover them with a single wordlist if i try the normal process i have to put my computational power three times to crack three wallet for a single wordlist. I want that I can put multiple wallets as input and run the process only one times. I'm not a crypto Graphic programmer So its totally out of my domain

**Comment by 3rdIteration** [comment]
Yea if you want to bring a PR that implements this then please do, but I won't be expending any time on it as it mostly isn't relevant for people recovering their own wallet.

**Comment by vishalkumar2806** [comment]
PR what you mean? Bro you can do this you can just improve it one more feature I will donate you btc for sure just add multiple wallets also like I have bitcoin core two wallets wallet1 and wallet2 I just want to recover both you can just add a argument like --wallets wallet1 wallet2 thats it

**Comment by 3rdIteration** [comment]
PR means you implement it and submit the code.

**Comment by vishalkumar2806** [comment]
bro I cant implement I'm not a coder please please please bro
