### ISSUE TITLE
Stellar Wallet in Scopuly

### ISSUE THREAD

**Issue by Royalcellular** [3rdIteration/btcrecover#351]
Do you have a btcrecover program for a stellar wallet in Scopuly?

**Comment by 3rdIteration** [comment]
BTCRecover already supports Stella lumens for seed recovery.

**Comment by Royalcellular** [comment]
Great, thank you so much

**Comment by Royalcellular** [comment]
What instructions do I use for the stellar wallet on btcrecover?

**Comment by 3rdIteration** [comment]
This isn't a support channel, ask in the YouTube comments section https://youtu.be/0LMUf0R9Pi4
