### ISSUE TITLE
Error: argument --tokenlist or --passwordlist is required (or file btcrecover-tokens-auto.txt must be present)

### ISSUE THREAD

**Issue by Vepcz0069** [3rdIteration/btcrecover#352]
![image](https://user-images.githubusercontent.com/79285964/166071044-bdec2f0b-793f-43fd-9d2a-3ff129f23ebb.png)
this is what I get when running it. How do I fix this?

**Comment by 3rdIteration** [comment]
The error means what it says... Follow the documentation https://btcrecover.readthedocs.io/
