### ISSUE TITLE
Dogechain.info 2FA access lost

### ISSUE THREAD

**Issue by coded00guy** [3rdIteration/btcrecover#353]
Is there any support for wallets with no dogechain.info 2fa Acces but with correct password>??

**Comment by doge2021** [comment]
if you still access to the email linked to the wallet, there is a chance to disable it. [Btc2doge](https://twitter.com/Btc2doge) on twitter may could help you. good luck

**Comment by coded00guy** [comment]
If i have access to my gmail attached to the account, how can i reset the 2Fa auth?

**Comment by 3rdIteration** [comment]
2fa can only be reset through contacting dogechain support
