### ISSUE TITLE
Know order of some missing words

### ISSUE THREAD

**Issue by coded00guy** [3rdIteration/btcrecover#354]
Assuming theres a 12 phrase words with 8 know phrases at place order of  (2,4,5,7,8, 9,10,12) and the rest words and unknown. How do you write your code with --big-typos 5 such that seedrecover.py knows the places of the known seed words and know where to insert new seed words to be tested. 

Kindly help out

**Comment by 3rdIteration** [comment]
5 missing words is too many to recover.
