### ISSUE TITLE
argument --rawprivatekey I get this error

### ISSUE THREAD

**Issue by Arukui** [3rdIteration/btcrecover#362]
How can I fix this?
![unkonw](https://user-images.githubusercontent.com/105894475/171996375-604597e5-a1c6-4b74-adbf-72f1154f77ac.png)

**Comment by Arukui** [comment]
I executed the instruction of this page
https://btcrecover.readthedocs.io/en/latest/Usage_Examples/basic_password_recoveries/#raw-eth-private-keys

**Comment by 3rdIteration** [comment]
Fixed in https://github.com/3rdIteration/btcrecover/commit/8dcd652f9789e014e68a63027af3f33f3a5cba59
