### ISSUE TITLE
In seedrecover.py using the -tokenlist file for bip39 words, how do you say try all words for a given spot?

### ISSUE THREAD

**Issue by sthuntnews** [3rdIteration/btcrecover#37]

**Comment by cezarlacatus** [comment]
Yeah, that's a good question.If you have a known order for a seed (you use positional anchors), how will you test the whole bip39 dictionary on a spot or multiple spots.I personally had pasted the whole  dictionary for a specific word

**Comment by 3rdIteration** [comment]
Basically the way that lines in text files work in tokenlists is that BTCRecover can pick any one item from that line. (But only one) Each element on that like can have its own positional anchors.

Example: 

The tokenlist:

The command:
python3 btcrecover.py --tokenlist ./benchmark-lists/tokenlist_multi_positional.txt --no-eta --dsw --listpass

Starting btcrecover 1.2.0-Cryptoguide on Python 3.8.3 64-bit, 21-bit unicodes, 64-bit ints
any
ONE
ONEany
anyTWO
4 password combinations

**Comment by mtad2002** [comment]
I need token sample file to recover 24 seed with one big-typo and one missplaced word that I don't know their places, can you help me with this?

**Comment by 3rdIteration** [comment]
So is the big typo a situation where you introduced/replaced one of the words with another valid BIP39 word and the misplaced one a situation where you swapped two? (And forgot which 2)

**Comment by sthuntnews** [comment]
@3rdIteration I appreciate the example, but it was for passwords not seed lists.  Think that is where the confusion is coming from.

@cezarlacatus I ended up doing something similar.  Lets say 12 seed words.  I know order of 6 of them.  I know 3 others, but not their order.  And I don't know the rest.

# 6 know seed words with order
^1^seeda
^2^seedb
^3^seedc
^4^seedd
^5^seede
^6^seedf
# 3 seed words, don't know order
# need all combos of seeds in this format
^7^seedg ^8^seedh ^9^seedi
.....
^7^seedi ^8^seedh ^9^seedg
# last 3 seed words we don't know
# list rest of 2048 words, one per line, minus any words found above

I was hoping for a simple tag that like <seed:all> or <seed:all:nodups> that could be used vs. pasting all 2048 into the tokenfile.

**Comment by 3rdIteration** [comment]
This is going to be extremely slow to do this way with a tokenlist generator, the standard one is actually much faster.

My suggestion is that you actually manually re-arrange the thee words (Keep track in excel or something) and just do the standard seed recovery process 8 times to cover it all. (If you have a decent GPU, you can solve a BIP39, 12 word seed with 3 missing words in about half a day, so about 4 days of total work. The tokenlist generator will be much slower. (See comparisons here: https://github.com/3rdIteration/btcrecover/blob/master/docs/GPU_Acceleration.md)

**Comment by sthuntnews** [comment]
@3rdIteration through documentation and testing it seems like --seedlist only does permutation, not positional statement.

How would you rewrite the --tokenfile example above for --seedlist ?

**Comment by 3rdIteration** [comment]
The positional stuff is assumed when it asks for you best guess if you pad it with invalid words.

See here: https://www.youtube.com/watch?v=Rp9n53XM3RI&list=PL7rfJxwogDzmd1IanPrmlTg3ewAIq-BZJ&index=12&t=0s
