### ISSUE TITLE
zcash?

### ISSUE THREAD

**Issue by TT1988** [3rdIteration/btcrecover#371]
Can zcash wallet be recovered I forgot the order of the 12 mnemonic words. I modified the path "wallet type bip39, bip32 path" m/44'/133'/0'/0 ", but could not find it.

**Comment by 3rdIteration** [comment]
Zcaah addresses aren't currently supported, but this could be added if you wanted to either directly sponsor it or go the trusted recovery route.

**Comment by 3rdIteration** [comment]
A standard feature sponsorship like this is $500 USD. (Or if it's a worthwhile trusted recovery, it can just be covered that way)

Other functionality would be a separate thing, but could also be possible. What did you have in mj d specifically?

**Comment by TT1988** [comment]
I want to randomly collide mnemonics to see if I can win the prize Little change Import a mnemonic word list, and then hit BTC or eth according to 12 mnemonic words in each line of the list (479001600 combinations need to be generated and verified) And save the generated address

**Comment by TT1988** [comment]
It's like buying lottery tickets.How much sponsorship is needed to customize such a function thank you.

**Comment by TT1988** [comment]
At present, these functions can be realized manually, but I want to be more automated If you are offended, please delete my request

**Comment by 3rdIteration** [comment]
Yea I'm not really interested in implementing things that aren't useful for
actual, real-world recoveries... Especially if it's already do-able with
existing features. But you can feel free to implement it yourself and bring
a PR.

Anyway, if you want to sponsor Zcash support then that is fine, you already
have the info for that.
