### ISSUE TITLE
GPU finds seed phrase, CPU does not (correct seed in 'savevalidseeds' file)

### ISSUE THREAD

**Issue by LW10583** [3rdIteration/btcrecover#375]
I was testing my setup and found that CPU mode returns seed not found although the correct 12 word phrase could be found in the --savevalidseeds file. GPU correctly found the 12 word phrase.

Computer is running Ubuntu 20.04 with Ryzen 5 CPU and 2 x GTX1050 Super GPUs. Seed phrase being searched came from Exodus wallet. The tokenlist contained valid BIP39 words (which were replaced for this bug report). Tokenlist:
.+ ^1^first   (NO leading period in tokenlist file, I had to insert here so editor doesn't substitute it for a bullet)
.+ ^2^second
.+ ^3^third
.+ ^4^fourth
.+ ^5^fifth
.+ ^6^sixth
.+ ^7^seventh
.+ ^8^eigth
.+ ^9^ninth
.+ ^10^tenth
1fake
2fake
eleventh
3fake
4fake
5fake
6fake
7fake
8fake
9fake
10fake
11fake
12fake
13fake
14fake
15fake
16fake
17fake
18fake
19fake
20fake
21fake
22fake
twelfth
23fake
24fake
25fake
26fake
27fake
28fake
29fake
30fake
31fake
32fake
33fake
34fake
35fake

1. CLI Command for GPU
python3 seedrecover.py --no-dupchecks --mnemonic-length 12 --no-gui --language EN --dsw --wallet-type BIP39 --addr-limit 4 --addressdb addresses_20170101_20220710.db --tokenlist ./tokenlist/myex.txt --enable-opencl --savevalidseeds winner.txt

Seed found: xxx xxx xxx...

2. CLI Command for CPU (same as GPU without --enable-opencl)
python3 seedrecover.py --no-dupchecks --mnemonic-length 12 --no-gui --language EN --dsw --wallet-type BIP39 --addr-limit 4 --addressdb addresses_20170101_20220710.db --tokenlist ./tokenlist/myex.txt --savevalidseeds winner.txt

Starting seedrecover 1.11.0-CryptoGuide, btcrecover 1.11.0-Cryptoguide on Python 3.8.10 64-bit, 21-bit unicodes, 64-bit ints
Loading address database ...
Loaded 780521724 addresses from database ...
warning: addresses are ignored when an mpk or addressdb is provided
Using the 'en' wordlist.
NOTICE: No Seed file size specified, Setting Seed Filesize to 10 million seeds per file
2022-07-12 11:54:27 : Phase 1/1: up to 12 mistakes, 12 of which can be an entirely different seed word.
Wallet Type: btcrseed.WalletBIP39
2022-07-12 11:54:27 : Using 12 worker threads
| 1406  elapsed: 0:00:00  rate:  77.83 kP/s
2022-07-12 11:54:27 : Search Complete
 Seed not found, sorry...
Save List Writer Finished

**Comment by 3rdIteration** [comment]
If you can generate a full test seed, tokenlist and address that can reproduce this, that would be great.

**Comment by LW10583** [comment]
Looks to be caused by the  '--savevalidseeds' option (which doesn't seem to work consistently). Not sure why the behavior is different on the original bug report but both these seed phrases have reproducible results.

TOKEN FILE (ignore period at beginning - added so this editor doesn't swap a bullet-point in):
.+ ^1^vivid
.+ ^2^social
.+ ^3^fatigue
.+ ^4^lens
.+ ^5^ankle
.+ ^6^color
.+ ^7^glimpse
.+ ^8^sword
.+ ^9^sauce
.+ ^10^onion
.slow
.# 11th seed word
.result
.avoid
.# 12th seed word
.novel

***********************************************************
RUN 1 - SEED FOUND - GPU enabled, no 'savevalidseeds'
user@Ryzen-1:~/btcrecover$ python3 seedrecover.py --no-dupchecks --mnemonic-length 12 --language EN --dsw --addr-limit 1 --addrs bc1qjp47quyukc9ajw603h5q2za777zpfxn00pscfg --tokenlist ./tokenlist/myex.txt --no-eta --wallet-type BIP39 --enable-opencl

Starting seedrecover 1.11.0-CryptoGuide, btcrecover 1.11.0-Cryptoguide on Python 3.8.10 64-bit, 21-bit unicodes, 64-bit ints
Using the 'en' wordlist.
OpenCL: Auto Selecting Best Platform
2022-07-12 17:46:48 : Phase 1/1: up to 12 mistakes, 12 of which can be an entirely different seed word.

OpenCL: Available Platforms
Platform 0 - Name NVIDIA CUDA, Vendor NVIDIA Corporation

OpenCL: Auto Selecting Best Platform
OpenCL: Using Platform: 0
OpenCL: Using Work Group Size:  51200

Wallet Type: btcrseed.WalletBIP39
2022-07-12 17:46:48 : Using 12 worker threads
2022-07-12 17:46:53 : ***MATCHING SEED FOUND***, Matched on Address at derivation path: m/84'/0'/0'/0/0
/ 9  elapsed: 0:00:00  rate:  86.68  P/s
2022-07-12 17:46:53 : Search Complete

If this tool helped you to recover funds, please consider donating 1% of what you recovered, in your crypto of choice to:
BTC: 37N7B7sdHahCXTcMJgEnHz7YmiR4bEqCrS
BCH: qpvjee5vwwsv78xc28kwgd3m9mnn5adargxd94kmrt
LTC: M966MQte7agAzdCZe5ssHo7g9VriwXgyqM
ETH: 0x72343f2806428dbbc2C11a83A1844912184b4243

Find me on Reddit @ https://www.reddit.com/user/Crypto-Guide

You may also consider donating to Gurnec, who created and maintained this tool until late 2017 @ 3Au8ZodNHPei7MQiSVAWb7NB2yqsb48GW4

Seed found: vivid social fatigue lens ankle color glimpse sword sauce onion result novel

*****************************************************************
RUN 2 - SEED NOT FOUND - GPU enabled, Use 'savevalidseeds'
user@Ryzen-1:~/btcrecover$ python3 seedrecover.py --no-dupchecks --mnemonic-length 12 --language EN --dsw --addr-limit 1 --addrs bc1qjp47quyukc9ajw603h5q2za777zpfxn00pscfg --tokenlist ./tokenlist/myex.txt --no-eta --wallet-type BIP39 --enable-opencl --savevalidseeds winner.txt

Starting seedrecover 1.11.0-CryptoGuide, btcrecover 1.11.0-Cryptoguide on Python 3.8.10 64-bit, 21-bit unicodes, 64-bit ints
Using the 'en' wordlist.
NOTICE: No Seed file size specified, Setting Seed Filesize to 10 million seeds per file
OpenCL: Auto Selecting Best Platform
2022-07-12 17:49:04 : Phase 1/1: up to 12 mistakes, 12 of which can be an entirely different seed word.

OpenCL: Available Platforms
Platform 0 - Name NVIDIA CUDA, Vendor NVIDIA Corporation

OpenCL: Auto Selecting Best Platform
OpenCL: Using Platform: 0
OpenCL: Using Work Group Size:  51200

Wallet Type: btcrseed.WalletBIP39
2022-07-12 17:49:04 : Using 12 worker threads
| 12  elapsed: 0:00:00  rate: 153.43  P/s
2022-07-12 17:49:11 : Search Complete
 Seed not found, sorry...

***********************************************************
RUN 3 - SEED FOUND - CPU, no 'savevalidseeds'
user@Ryzen-1:~/btcrecover$ python3 seedrecover.py --no-dupchecks --mnemonic-length 12 --language EN --dsw --addr-limit 1 --addrs bc1qjp47quyukc9ajw603h5q2za777zpfxn00pscfg --tokenlist ./tokenlist/myex.txt --no-eta --wallet-type BIP39

Starting seedrecover 1.11.0-CryptoGuide, btcrecover 1.11.0-Cryptoguide on Python 3.8.10 64-bit, 21-bit unicodes, 64-bit ints
Using the 'en' wordlist.
2022-07-12 17:51:27 : Phase 1/1: up to 12 mistakes, 12 of which can be an entirely different seed word.
Wallet Type: btcrseed.WalletBIP39
2022-07-12 17:51:27 : Using 12 worker threads
2022-07-12 17:51:27 : ***MATCHING SEED FOUND***, Matched on Address at derivation path: m/84'/0'/0'/0/0
/ 9  elapsed: 0:00:00  rate:   1.95 kP/s
2022-07-12 17:51:27 : Search Complete

If this tool helped you to recover funds, please consider donating 1% of what you recovered, in your crypto of choice to:
BTC: 37N7B7sdHahCXTcMJgEnHz7YmiR4bEqCrS
BCH: qpvjee5vwwsv78xc28kwgd3m9mnn5adargxd94kmrt
LTC: M966MQte7agAzdCZe5ssHo7g9VriwXgyqM
ETH: 0x72343f2806428dbbc2C11a83A1844912184b4243

Find me on Reddit @ https://www.reddit.com/user/Crypto-Guide

You may also consider donating to Gurnec, who created and maintained this tool until late 2017 @ 3Au8ZodNHPei7MQiSVAWb7NB2yqsb48GW4

Seed found: vivid social fatigue lens ankle color glimpse sword sauce onion result novel

********************************************************
RUN 4 - SEED NOT FOUND - CPU, Use 'savevalidseeds'
user@Ryzen-1:~/btcrecover$ python3 seedrecover.py --no-dupchecks --mnemonic-length 12 --language EN --dsw --addr-limit 1 --addrs bc1qjp47quyukc9ajw603h5q2za777zpfxn00pscfg --tokenlist ./tokenlist/myex.txt --no-eta --wallet-type BIP39 --savevalidseeds winner.txt

Starting seedrecover 1.11.0-CryptoGuide, btcrecover 1.11.0-Cryptoguide on Python 3.8.10 64-bit, 21-bit unicodes, 64-bit ints
Using the 'en' wordlist.
NOTICE: No Seed file size specified, Setting Seed Filesize to 10 million seeds per file
2022-07-12 17:52:21 : Phase 1/1: up to 12 mistakes, 12 of which can be an entirely different seed word.
Wallet Type: btcrseed.WalletBIP39
2022-07-12 17:52:22 : Using 12 worker threads
| 12  elapsed: 0:00:00  rate:  19.33 kP/s
2022-07-12 17:52:22 : Search Complete
 Seed not found, sorry...

**Comment by 3rdIteration** [comment]
Basically this is a documentation issue. SaveValidSeeds was mostly used for testing when OpenCL was first being added. Simply put it does nothing when GPU acceleration is used. (Doesn't save a list) and when it is used with CPU acceleration, it doesn't actually check any of the seeds, but rather saves all those with a valid checksum.

**Comment by 3rdIteration** [comment]
Addressed in https://github.com/3rdIteration/btcrecover/commit/3c16d10e2e4b9890125ee88417c546806a7a3161
