### ISSUE TITLE
Ordering of phrases

### ISSUE THREAD

**Issue by coded00guy** [3rdIteration/btcrecover#378]
If i know the first and other 9 phrases (4-12) how do i put the phrase in the entry, making it know tat i dont know the 2nd and 3rd phrase?

**Comment by 3rdIteration** [comment]
If you are only missing two words then just put the 10 words you have in order. (You could use a placeholder for the missing ones, but this isn't required for only two missing words)

This isn't a support channel, so ask any further questions in the YouTube comments.
