### ISSUE TITLE
Error: "Skipped all 0 passwords, exiting"

### ISSUE THREAD

**Issue by levintofu** [3rdIteration/btcrecover#381]
Been using BTCRecover for a few years now whiteout issue. Just today when I went to do a normal simple update to the token file (i.e.  %d$ ->  %2d$) I'm now getting the error  "Skipped all 0 passwords, exiting". I tired reinstalling and updating Python, BTCRecover, restarting windows, renaming token files, etc. No matter what I do BTCRecover now skips all token lists passwords. And all tests come back nominal so I'm not sure what the issue is. 

Also, as an aside, what is the syntax to integrate GPU acceleration into a known token list? I tired to append "--enable-gpu" to a standard "btcrecover.py --wallet wallet.dat --tokenlist tokens.txt" and it doesn't seem to work.  It works if I brute force the wallet file but I can't get it to integrate a know passwords token list. 

EDIT: I was able to sort out the "Skip all 0 passwords, exiting" issue.  I had (2) beginning Anchors with the same Anchor numbers (e.g. ^4 in line 4 and ^4 in line 6 of the Tokens file.). I'm keeping the issue open for now since I still need an explanation to the "--enable-gpu" in Tokens file searches.

**Comment by 3rdIteration** [comment]
Gpu and opencl will both work with token list for supported wallet types. (Gpu argument for Bitcoin core and clones, opencl argument for other wallet types)
