### ISSUE TITLE
adding "extra word" / passphrase to seedrecover.py for 12+1 words ETH wallets

### ISSUE THREAD

**Issue by phikappasan** [3rdIteration/btcrecover#382]
the seedrecover.py doesn't seem to support the extra word for unscrambling ETH seed phrases. I've tried adding my extra word as ^13^ in the txt file passed as tokenlist but no dice. Would it be possible to implement it? I can also have a crack at it myself, as afaik the extra word is just an extra layer for generating hash out of words. Would just need some broad indication as to where in the code I can add a hardcoded 13th word in the generation of the private key from a scrambled seed word list.

**Comment by 3rdIteration** [comment]
"Extra word" is just a poor way of describing a BIP39 passphrase which leads to misunderstanding and issues exactly like this.

You need to use the 12 words you have in the same way as any other descramble and add the BIP39 passphrase via the arguments.
