### ISSUE TITLE
seedrecover.py opencl degraded performance when using ^?^ anchors

### ISSUE THREAD

**Issue by okanisis** [3rdIteration/btcrecover#384]
Seed:  `glad slender axis cake gasp genuine save vacuum exist nurse half swamp`
Address: `0xd66afbf38e26116941bde0ba1f37008437e0278b`
Token List: https://raw.githubusercontent.com/bitcoin/bips/master/bip-0039/english.txt
with the following inserted as the rules,
```
+ ^1^glad
+ ^2^slender
+ ^3^axis
+ ^4^cake
+ ^5^gasp
+ ^6^genuine
+ ^7^save
+ ^8^vacuum
+ ^9^exist
+ ^10^nurse
+ ^11^half
+ ^12^swamp
```
will find it instantly of course.

But if we remove the last 3 words: `nurse, half, swamp` then performance takes a huge hit especially with --enable-opencl where it slowly loses kP/s over time.

Command:
`python seedrecover.py --tokenlist english.txt --language EN --addr-limit 1 --addrs 0xD66afbF38E26116941bdE0ba1f37008437e0278b --wallet-type ethereum --mnemonic-length 12 --dsw --bip32-path "m/44'/60'/0'" "m/44'/60'/0'/0" "m/44'/60'/0'/0/0" "m/44'/60'/1'/0/0" --no-eta --no-dupchecks --no-dupchecks --no-dupchecks --no-dupchecks --enable-opencl`

The average kP/s after a few hours clugs it down to less than 10kP/s but when you remove all the positional anchors ^^ and just leave the + performance increases to expected +200kP/s.

**Comment by 3rdIteration** [comment]
This is normal due to the way that seeds are generated and checked when using tokenlists.

**Comment by okanisis** [comment]
It seems like it should be an easier check when the position of a word is known and it has to generate permutations and combinations based on a small sample size of 2 or 3 words instead of all 12.

Performance seems like something is definitely wrong. I tested with itertools and it does permutations fine with the same conditions.

**Comment by 3rdIteration** [comment]
Well yea the issue is that you are using the tokenlist in an odd way for the recovery that you seem to be attempting.

**Comment by okanisis** [comment]
> Well yea the issue is that you are using the tokenlist in an odd/inefficient way for the recovery that you seem to be attempting.

Im not sure how else to structure a token list when its known the first x words and their order. ie only missing last 2 or 3 words. i must be missing something in the docs.

**Comment by 3rdIteration** [comment]
This isn't a general support channel, so you can either ask in the comments section on YouTube or fix it up in a paid private session.
