### ISSUE TITLE
download-blockchain-wallet.py  is not working 

### ISSUE THREAD

**Issue by TheWhiteHat007** [3rdIteration/btcrecover#385]
Dear sir,

download-blockchain-wallet.py  is not working since last 10 days.

kindly check ASAP.

**Comment by TheWhiteHat007** [comment]
# @3rdIteration

**Comment by 3rdIteration** [comment]
Looks to be broken with a recent update on their end, just use the browser method for now, it's basically the same as with the dogechain.info wallet.

**Comment by TheWhiteHat007** [comment]
i think getting through browser is best & permanent option

**Comment by 3rdIteration** [comment]
https://github.com/3rdIteration/btcrecover/commit/66121eab54380dc7dd3b27c14d0d32e3a3ccbd14

**Comment by dalmatele** [comment]
If ok, I think we can revise this function by integrating selenium to download.
