### ISSUE TITLE
How to connect 12 videocards to recover process

### ISSUE THREAD

**Issue by GSinatra** [3rdIteration/btcrecover#387]
Happy new year 🥳 
I have 12 3060 and much more. How to make them work in one process?

**Comment by 3rdIteration** [comment]
https://btcrecover.readthedocs.io/en/latest/GPU_Acceleration/

**Comment by GSinatra** [comment]
I was able to connect only three cards. Using the -gpu-names command. For some reason, he doesn't see the rest of the cards with identical names (NVIDIA GeForce RTX). Can you tell me how to connect the rest?

![image](https://user-images.githubusercontent.com/43311340/211156340-e5fe9753-735d-423a-b6d4-d882e0e3b5be.jpeg)

--enable-opencl showing me this

![image](https://user-images.githubusercontent.com/43311340/211157314-d6fd3099-7018-4476-87ca-a1e7f64d31ea.jpeg)

**Comment by 3rdIteration** [comment]
The multi-card functionality is working fine, but it looks like you have some other issue with your system. (So no bug, so nothing to fix here in the issues section)

**Comment by 3rdIteration** [comment]
Looks like the --enable-gpu is working fine. In terms of the --enable-opencl issue, does your system pass all the tests that are part of the installation documentation?

**Comment by GSinatra** [comment]
No. Just GPU Test.
OpenCL tests all ERROR

**Comment by GSinatra** [comment]
![image](https://github.com/3rdIteration/btcrecover/assets/43311340/28df6548-c39a-47ce-9464-d5c0d28f6aca)

**Comment by GSinatra** [comment]
![image](https://github.com/3rdIteration/btcrecover/assets/43311340/55911e5d-529e-47ee-b154-91524df6fba2)
