### ISSUE TITLE
seedrecover.py stuck at | 0  elapsed: 0:00:00  rate:   0.00  P/s

### ISSUE THREAD

**Issue by porcupinepostwar** [3rdIteration/btcrecover#392]
Attempting to recover the last four missing seed words from a 12-word Breadwallet mnemonic with known passphrase. Mnemonic input in gui in the form: word1 word2 word3 word4 word5 word6 word7 word8 X X X X

This problem occurs in various combinations of setups I've tried, including Python 3.8, 3.9, 3.10, and 3.11 (with corresponding PyOpenCL wheels), with or without OpenCL, eta or dupchecks, and other command line arguments, and on Windows 10 or Debian WSL. Requirements-full installed, elevated terminal, Python in PATH.

All tests OK, and --performance flag does produce a successful result (running at ~100 kP/s).

i5-4570
RTX 2060 Super (528.24)
16GB RAM

Example:

-----
`python seedrecover.py --mnemonic-length 12 --language en --enable-opencl --dsw --addressdb addresses.db --addr-limit 1 --wallet-type bitcoinj --big-typos 4 --no-eta --no-dupchecks --passphrase`

Starting seedrecover 1.11.0-CryptoGuide, btcrecover 1.11.0-Cryptoguide on Python 3.9.13 64-bit, 21-bit unicodes, 64-bit ints
Loading address database ...
Loaded 804797813 addresses from database ...
Using the 'en' wordlist.
'x' was in your seed, but there is no similar seed word.
'x' was in your seed, but there is no similar seed word.
'x' was in your seed, but there is no similar seed word.
'x' was in your seed, but there is no similar seed word.
OpenCL: Auto Selecting Best Platform
2023-01-28 11:13:44 : Phase 1/1: up to 4 mistakes, 4 of which can be an entirely different seed word.

OpenCL: Available Platforms
Platform 0 - Name NVIDIA CUDA, Vendor NVIDIA Corporation

OpenCL: Auto Selecting Best Platform
OpenCL: Using Platform: 0
OpenCL: Using Work Group Size:  51200

Wallet Type: btcrseed.WalletBitcoinj
2023-01-28 11:13:44 : Using 4 worker threads
| 0  elapsed: 0:00:00  rate:   0.00  P/s

`^C`

Interrupted after finishing password # 0

-----

Starting seedrecover.py, RAM usage will rise to and stay at ~80% throughout. CPU usage will rise to ~75% for ~5 minutes when the search begins, and then range between ~30-50% indefinitely. I've left it running for 3+ days with no change before manually closing.

**Comment by 3rdIteration** [comment]
Four missing words isn't practical at this time, it will take years... (And the slow startup phase is only really an issue for this many missing words)
