### ISSUE TITLE
possible_passwords.log

### ISSUE THREAD

**Issue by Hosseinsh99** [3rdIteration/btcrecover#393]
hey so i was wondering how does possible_passwords.log exactly work. i am using btcrecover for quite a while and was not making any progress finding my blockchain.com wallet password. but recently i noticed a change in possible_passwords log, it's says there is a possible password in a specific block and it happened 2 times with 2 same passwords.so i was wondering how could i know which parts of my tokenlist were correct that the program thought that these passwords are possible and more importantly how does the program even know im close to the password without actually knowing the password.Your response will be really appreciated. tnx

**Comment by 3rdIteration** [comment]
All the documentation is in the file itself... Basically unless you are seeing that it decrypts something that looks like valid JSON (like the examples it includes) then it's doesn't mean anything.

It's mostly there to make it easy to add support if the blockchain wallet format changes
