### ISSUE TITLE
Tokenlist Recovery fails to find a seed if every possible word has a positional anchor.

### ISSUE THREAD

**Issue by graemeblackwood** [3rdIteration/btcrecover#40]
When using `--bip32-path` with `--tokenlist`, I always get "Seed not found", even though the seed is definitely correct in the tokenlist file.

Removing `--tokenlist` triggers the popup, and then pasting the seed in works fine.

I'm confident my tokenlist file is correctly formatted. Is this a known issue?

**Comment by 3rdIteration** [comment]
Could you try running the Litecoin example at the bottom here: https://github.com/3rdIteration/btcrecover/blob/master/docs/Usage_Examples/2020-05-02_Descrambling_a_12_word_seed/Example.md

It has both the elements you are describing and works fine, so curious to see if that fails to find the seed on your PC too...  The above example should find the seed in under 30 seconds.

**Comment by graemeblackwood** [comment]
Yes, it works with that example (btw it's missing double quotes around the derivation path)

But it doesn't work with this:

**Address at m/49'/0'/0'/0**
34RAzyaTCMtHFZz4k4TNMLF1KBkd18Qb1R

**Seed**
elbow text print census battle push oyster team home april travel barrel

**Super simple tokenlist.txt – maybe I am doing something wrong here?**
```
^1^elbow
^2^text
^3^print
^4^census
^5^battle
^6^push
^7^oyster
^8^team
^9^home
^10^april
^11^travel
^12^barrel
```

**Command**
```
python3 seedrecover.py --no-dupchecks --mnemonic-length 12 --language EN --dsw --wallet-type BIP39 --addr-limit 1 --addrs 34RAzyaTCMtHFZz4k4TNMLF1KBkd18Qb1R --tokenlist ./tokenlist.txt --bip32-path "m/49'/0'/0'/0"
```

**Comment by 3rdIteration** [comment]
The commands that are int he example should work exactly as-is, without needing double slashes. If not, I'm curious to know which platform you are running on that needs them. (MacOS?)

So the interesting find is that I had a play around with your list and everything works if you remove a single positional marker from any of the words. Adding/removing the derivation path makes no difference.

So for example: 
`python3 seedrecover.py --mnemonic-length 12 --language en --addr-limit 1 --addrs 34RAzyaTCMtHFZz4k4TNMLF1KBkd18Qb1R --tokenlist issue.txt --bip32-path "m/49'/0'/0'/0" --wallet-type bip39 --dsw --no-eta`

will give seed not found when used with your above list, but if you remove the positional anchor from any one of the words, then it will find it fine.

If this is what you are seeing, I can rename the issue and have a dig as to why the generator doesn't spit out the single result in this situation. (Though it's certainly an edge-case in terms of use, as you can just enter the fill seed as-is already using the mnemonic prompt, so it's a fairly low priority fix)

**Comment by graemeblackwood** [comment]
You're correct about the double quotes – not sure what the issue was before but the path works without.

I had to also remove `--no-dupchecks`, and one of the positional anchors. Then it worked.

You can fill in the seed as-is in the prompt. Can you include positional anchors in the prompt though?

Thanks for your help.

**Comment by 3rdIteration** [comment]
So if you use the command I pasted above, with your tokenlist you posted above as issues.txt, does it work if you drop a single anchor from the file?

**Comment by graemeblackwood** [comment]
Yes it does.

**Comment by 3rdIteration** [comment]
Great, will rename the issue and fix up this edge case :)

**Comment by mtad2002** [comment]
i have the same issue but with --mnemonic-length 24 , 

the example command works fine with example tokenlist but when i change --mnemonic-length 12 to --mnemonic-length 24 it fails

command i used :
python3 seedrecover.py --no-dupchecks --mnemonic-length 24 --language EN --dsw --wallet-type BIP39 --addr-limit 1 --addrs 17GR7xWtWrfYm6y3xoZy8cXioVqBbSYcpU --tokenlist ./docs/Usage_Examples/2020-05-02_Descrambling_a_12_word_seed/firstcombination_bip39.txt

**Comment by 3rdIteration** [comment]
Have you edited the

**Comment by 3rdIteration** [comment]
Have you also edited the example tokenlist file so that there are actually 24 words in it?

**Comment by mtad2002** [comment]
> Have you also edited the example tokenlist file so that there are actually 24 words in it?

Yes i put 23 anchored words and one wrong word in last without anchor or plus against my test wallet address, 
I will double check it later

**Comment by 3rdIteration** [comment]
> > Have you also edited the example tokenlist file so that there are actually 24 words in it?
> 
> Yes i put 23 anchored words and one wrong word in last without anchor or plus against my test wallet address,
> I will double check it later

I'm inclined to think you made a mistake somewhere, as I just tested it and the length of the tokenlist/seed made no difference to this behavior.

I just expanded the above example out to a list of 24 words
[issue-24.txt](https://github.com/3rdIteration/btcrecover/files/4805170/issue-24.txt)

Used the command: 
`python3 seedrecover.py --mnemonic-length 24 --language en --addr-limit 1 --addrs 39JX61fdreGiukh7JYYxXYj3gcAUimP818 --tokenlist issue-24.txt --wallet-type bip39 --dsw --no-eta`

and it found the result no problem at all. (As long as at last one token didn't have a positional anchor)

**Comment by mtad2002** [comment]
> > > Have you also edited the example tokenlist file so that there are actually 24 words in it?
> > 
> > 
> > Yes i put 23 anchored words and one wrong word in last without anchor or plus against my test wallet address,
> > I will double check it later
> 
> I'm inclined to think you made a mistake somewhere, as I just tested it and the length of the tokenlist/seed made no difference to this behavior.
> 
> I just expanded the above example out to a list of 24 words
> [issue-24.txt](https://github.com/3rdIteration/btcrecover/files/4805170/issue-24.txt)
> 
> Used the command:
> `python3 seedrecover.py --mnemonic-length 24 --language en --addr-limit 1 --addrs 39JX61fdreGiukh7JYYxXYj3gcAUimP818 --tokenlist issue-24.txt --wallet-type bip39 --dsw --no-eta`
> 
> and it found the result no problem at all. (As long as at last one token didn't have a positional anchor)

You're right I was missing a word, it is worked when add another.

**Comment by 3rdIteration** [comment]
This has been fixed in the OpenCL branch here: https://github.com/3rdIteration/btcrecover/commit/260f29505a70feaf393825f7faec29a577499b1b

Will get merged back in to master with all the OpenCL stuff once I have added the docco, but if you need it for your usage scenario, just use the OpenCL-WIP branch for now.
Will leave this issue open until this is merged back in to master.

**Comment by 3rdIteration** [comment]
Merged into master with https://github.com/3rdIteration/btcrecover/commit/743d9d5f55c46a6e0681dba2647892159d4a02b3
