### ISSUE TITLE
Ledger passphrase

### ISSUE THREAD

**Issue by carlhoogstoel** [3rdIteration/btcrecover#403]
First of all, may thanks for the efforts you are putting in this tool. As a developer myself I can appreciate it even more :)

Now the question:

I have a Ledger BTC wallet where I lost the passphrase from. The seed I am 100% sure of. Now, when I run the tool to find the password, I came up empty even when I was pretty sure I knew what the password would be. I know what you are thinking, "so does everyone":)

As I came up empty, I thought, what if I just made a new account with a new seed and with a new passphrase just to check if my command line was correct. That way I would be sure that I wasn't doing anything wrong. As you can guess already, I couldn’t find the passphrase. So my question is, what is wrong with this command line. The seed and the passphrase are 100% correct because I can access it with my ledger key. I just cannot get a positive hit on the passphrase with the tool. My best guess is that it is linked to an incorrect derivation path but I checked the details of the wallet and it states: **"freshAddressPath": "84'/0'/0'/0/1"**

First I tried to see if I could validate the seed. This is the command line I tried on a wallet without a passphrase:

**python3 seedrecover.py –no-dupchecks  --mnemonic-length 24 –language EN –dsw –wallet-type BIP39 –addr-limit 2 –addrs 1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfN1 –mnemonic “24 word seed”** -> Positive hit

This is the command line I tried on a wallet with a passphrase but with the same seed:

**python3 seedrecover.py –no-dupchecks  --mnemonic-length 24 –language EN –dsw –wallet-type BIP39 –addr-limit 2 –addrs 1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfN2 –mnemonic “24 word seed”** -> Negative hit

Please note that I can access the wallets fine with the Ledger key.

Question 1: Is this because the seed is actually the seed + the passphrase? In that case I understand that it gives a negative result.
Question 2: What is the command line to verify the seed on a wallet with a passphrase? You can’t just add the 25th word because that is not accepted. Or should it just give a positive result  with the correct seed but without adding the passphrase?

The command to retrieve the password:

**python3 btcrecover.py –no-dupchecks –passwordlist ./passwordlist.txt –addr-limit 1 –typos-capslock –typos-swap –typos-repeat –typos-delete –typos-case –typos 3 –bip32-path “m/84’/0’/0’” –addrs 1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfN2 –mnemonic “24 word seed”** -> Negative hit

Please note that the passwordlist is an empty text file with just the correct passphrase in it.

Question 3: The BTC address I am using is the receive address of the first transaction on that account in Ledger. I know that the address changes every time you receive coins, but this is only in the context of a single account correct? Because I have several BTC accounts in my Ledger.

**Comment by 3rdIteration** [comment]
This isn't a support channel, only for bugs.

Free support happens in the YouTube comments on my channel and info about paid private support can be found here https://cryptoguide.tips/recovery-services-consultations/
