### ISSUE TITLE
Sponsored Feature: Password Recovery for Imtoken keystore

### ISSUE THREAD

**Issue by zeng1978** [3rdIteration/btcrecover#404]
I forgot the imtoken transaction password. Can I use btcrecover to recover it.

**Comment by zeng1978** [comment]
I forgot my password on both phones. How much sponsorship is required for Android and OSI. Thank you very much.

**Comment by 3rdIteration** [comment]
So are you saying that you have the wallet on both Android and iOS and, that you forgot the *wallet password* on both? (Or are you unable to unlock the phone?)

**Comment by zeng1978** [comment]
I can log in to the wallet software, but I forgot my transaction password. Can I recover using btcrecover. Please help me. thank you.

**Comment by zeng1978** [comment]
https://github.com/consenlabs/token-core/tree/dev/tcx-chain/src/keystore，This is the open source code URL and the location where the file is saved. Can you obtain the encrypted hash value. thank you

**Comment by zeng1978** [comment]
This is the open source code for imtoken

**Comment by zeng1978** [comment]
ok.

**Comment by 3rdIteration** [comment]
Added in https://github.com/3rdIteration/btcrecover/commit/5fbb58b8a1a9311b8dffdc1748df4f3e474beb68

How to find your wallet file:
https://btcrecover.readthedocs.io/en/latest/TUTORIAL/#finding-imtoken-wallet-files

Usage example for imToken:
https://btcrecover.readthedocs.io/en/latest/Usage_Examples/basic_password_recoveries/#imtoken-wallet-keystores
