### ISSUE TITLE
Program working but.......

### ISSUE THREAD

**Issue by screwthegov13** [3rdIteration/btcrecover#409]
Program seems to be working (btcrecover) (btcrpass) passes all tests, starts out calculating passwords, and time it will take. It does that then closes. Doesn't check any passwords.... Windows 10 cmd line. Trying to get passphrase from Trezor one. Have seed and wallet addr.

Thanks

**Comment by 3rdIteration** [comment]
Sounds like you are running out of memory or something, perhaps try somehing like no-dupchecks. (Or listpass if you want to get an idea of what passwords are being generated)

The feature works fine and this isn't a bug, so ask any support related questions you have on my YouTube channel in the comments.
