### ISSUE TITLE
Need calculate probabilities of seedrecover!

### ISSUE THREAD

**Issue by mtad2002** [3rdIteration/btcrecover#41]
I had run seedrecover on my pc with options
--no-dupchecks --mnemonic-lenght 24 --typo 3 --big-typs 3 --addr-limit 2

Can someone please tell me how many probabilities is going to be counted ?

It's already counted 52.7 billion so far, and i think my case's fan already died on this(it's not spinning amy more) 😞, i want to know how much its suppose to count? And is it reasonable to let it go further or should I turn it off now?

**Comment by 3rdIteration** [comment]
If it is three big typos where you don't know their location at all, there will be a few trillion possibilities.

**Comment by mtad2002** [comment]
Somehow calculated it, it is around 17.5 trillion 🤦

I think the best shot i have is to use multiple GPUs of multiple mining rigs that work together.

The problem is seedrecover not support gpu yet.

**Comment by cezarlacatus** [comment]
@mtad2002 Try the OpenCl Branch for Gpu support

**Comment by 3rdIteration** [comment]
Yea for that sort of recovery, you will need to either narrow down your search field or use something that does the entire process in GPU and can distribute the work over dozens and dozens of GPUs.

Your best bet is something like this: https://medium.com/@johncantrell97/how-i-checked-over-1-trillion-mnemonics-in-30-hours-to-win-a-bitcoin-635fe051a752

**Comment by 3rdIteration** [comment]
Your best bet with this one is to follow this issue here: https://github.com/3rdIteration/btcrecover/issues/43

As it is the most likely place to come up with a solution for your situation.

**Comment by mtad2002** [comment]
> @mtad2002 Try the OpenCl Branch for Gpu support

I think opencl branch is work for btcrecover.py when you have wallet file, i just have 24 words and deposit address, i think i have to work with seedrecover.py
