### ISSUE TITLE
Request GPU support for Blockchain V1 Wallet.

### ISSUE THREAD

**Issue by Drax4545** [3rdIteration/btcrecover#410]
Request GPU support for Blockchain V1 Wallet. Blockchain Wallet V1 Wallets has more than 1 iteration.  Please see attached file.
[wallet.zip](https://github.com/3rdIteration/btcrecover/files/11410418/wallet.zip)

**Comment by 3rdIteration** [comment]
Just fixed it for the entropy check, so thanks for the sample.

There is no point, 10 sha iterations won't give a meaninful performance gain with this implementation.

**Comment by Drax4545** [comment]
Why hashcat is much faster than btcrecover?

**Comment by 3rdIteration** [comment]
It's basically pure opencl, this is also why it can't do anywhere near as much feature wise
