### ISSUE TITLE
request tor address db

### ISSUE THREAD

**Issue by themonkhinekie** [3rdIteration/btcrecover#412]
Hi, can you make a database containing eth and bsc at the same time. I mean join them because it can be easier to look for in another category for eth and bsc wallets. I tried but theres a password for the database. Im happy if you can join them. Thanks a lot

**Comment by 3rdIteration** [comment]
You can just follow the documentation and produce this yourself. (I won't be doing so unless someone sponsors it or a trusted recovery for this comes up)
