### ISSUE TITLE
Can't use --enable-opencl

### ISSUE THREAD

**Issue by GSinatra** [3rdIteration/btcrecover#414]
Hello! 
I wanna use 9 video cards but opencl still doesn't work.

![image](https://github.com/3rdIteration/btcrecover/assets/43311340/65d9b19c-7002-4e39-8a6f-40320eeb91a3)

![image](https://github.com/3rdIteration/btcrecover/assets/43311340/7a629c11-43f8-4be3-9a34-ef5529236a01)

**Comment by GSinatra** [comment]
I use python 3.9, opencl cl12+39.

**Comment by 3rdIteration** [comment]
Can't reproduce, looks like an issue with your system, not a bug.

**Comment by GSinatra** [comment]
I install windows 10, original drivers for nvidaia, then Python, requests.txt, then pyopenCL.

I use motherboard Gigabyte Fintech b250, i5 7gen old, 7x 3060ti, 2x 3080.

**Comment by GSinatra** [comment]
> Can't reproduce, looks like an issue with your system, not a bug. 

It mean conflict with Windows?

**Comment by 3rdIteration** [comment]
This isn't a support channel, ask in the YouTube comments
