### ISSUE TITLE
Hashcat rule support

### ISSUE THREAD

**Issue by Drax4545** [3rdIteration/btcrecover#415]
Please add Hashcat rule support.

**Comment by 3rdIteration** [comment]
You are welcome to bring a PR that implements this as an alternative to the current arguments for typos, etc.

**Comment by Drax4545** [comment]
What do you mean pr? Sorry English is not my first language.

**Comment by 3rdIteration** [comment]
Write the code and bring a pull request on GitHub

**Comment by Drax4545** [comment]
I do not know how to program.

**Comment by 3rdIteration** [comment]
In that case I have no plans to implement this, so will close the issue.
