### ISSUE TITLE
need some help with token list 

### ISSUE THREAD

**Issue by Hosseinsh99** [3rdIteration/btcrecover#416]
so i have two questions :
how can i stop the program from trying tokens with repetitive characters? 
the other question is what command should i use so the program saves generated passwords to a txt file? i used this command before but know i don't remember the command. 
thanks for your help. <3

**Comment by 3rdIteration** [comment]
This isn't a support channel, so you can ask a question in comments of my YouTube channel or request a paid & private consultation here: https://cryptoguide.tips/recovery-services-consultations/
