### ISSUE TITLE
Tron cannot recover mnemonics using addressdb

### ISSUE THREAD

**Issue by jack0000001** [3rdIteration/btcrecover#421]
I compared the two methods of directly using addresses and address libraries during testing. Directly using addresses can restore mnemonics. However, establishing an address library with a known address cannot restore mnemonics.I have added an address to my address library, and it is not possible to restore mnemonics.

**Comment by 3rdIteration** [comment]
Creating an addressDB isn't currently supported for Tron. (A company was offering this on Google Bigquery a few years back but dropped support)

If you want to sponsor the feature ($500 USD) then I noticed that it should be possible due to a TronETL package that someone made.

**Comment by jack0000001** [comment]
Thank you. Is it okay to sponsor 200USDT? I haven't graduated from college yet.
















At 2023-08-15 08:59:37, "3rd Iteration" ***@***.***> wrote:

Creating an addressDB isn't currently supported for Tron. (A company was offering this on Google Bigquery a few years back but dropped support)

If you want to sponsor the feature ($500 USD) then I noticed that it should be possible due to a TronETL package that someone made.

**Comment by 3rdIteration** [comment]
No, but you are free to implement it yourself and share the result to Github so that everyone else benefits.
