### ISSUE TITLE
Why BTCRecover is slower than Hashcat more than 200 times when running v0 - v1 Blockchain Wallets?

### ISSUE THREAD

**Issue by Drax4545** [3rdIteration/btcrecover#423]
Why BTCRecover is slower than Hashcat more than 200 times when running v0 - v1 Blockchain Wallets?

**Comment by 3rdIteration** [comment]
Probably because hashcat is mostly pure OpenCL and also requires you to manually to some other steps to prepare and run the tool. (Never mind having a narrower compatibility)
