### ISSUE TITLE
Getting my Seed Phrase with my Address 

### ISSUE THREAD

**Issue by G1Convoy** [3rdIteration/btcrecover#426]
I need help is there away to get my Seed Phrase using BTC Recover to get my Wallet back into Trust Wallet witch is a Muilt Coin Wallet the thing is I lost my Seed Phrase and I have 400$ in that account I need it really bad thats basicly my life savings with out it I am homeless

**Comment by 3rdIteration** [comment]
If you have none of the seed words then no, this is unrecoverable.
This isn't a support channel, only for bugs, so if you have further questions, ask in my YouTube channel comments section.
