### ISSUE TITLE
TRON keys missing chars

### ISSUE THREAD

**Issue by dcdcdcdcdcdcdcdcf** [3rdIteration/btcrecover#429]
Hello, i have saved TRX private key, one of symbol in it are wrong, how to try a lot of combinations to it? i have address which must be inside

**Comment by dcdcdcdcdcdcdcdcf** [comment]
smth like this 

https://web.archive.org/web/20190308051631/http://trxrecovery.hashfables.com/

**Comment by 3rdIteration** [comment]
Raw private key recovery is not currently supported for Tron. (As it is with things like Bitcoin, Eth, etc)

You can implement it yourself and bring a PR or if you are in a hurry, sponsor the feature directly.
