### ISSUE TITLE
Btcrecover not working on ubuntu live

### ISSUE THREAD

**Issue by screwthegov13** [3rdIteration/btcrecover#430]
Followed your install for Ubuntu live USB to the letter, and for some reason I have to use safe graphics mode or it freezes. When I do that I'm able get to the install python3-pip but then my mouse pointer disappears and it also won't install resources. Can you tell me what I need to do. I tried making the USB on Linux and Windows no luck. Do I have to download a past Linux system ?

Thank you

**Comment by 3rdIteration** [comment]
Have you tried a different PC?

**Comment by screwthegov13** [comment]
Yep tried two different laptops one windows 10 the other Ubuntu Jammy, tried 32bit Ubuntu.  Really not sure what I'm doing wrong. I will try a another windows system.  Using Ubuntu Jammy live. I get to install Python3-pip then it freezes same thing every time.

**Comment by 3rdIteration** [comment]
There is something wrong with your systems or system image. Either way this isn't related to a bug in BTCRecover or the documentation, best bet is to ask in Ubuntu support channels

**Comment by screwthegov13** [comment]
Very long story but it seems to have sorted itself out.  The test went fine skipped 14 then installed OpenCL and its getting hung up on Blockchain Brute decrypt.  Also do you offer a token list.  I'm trying to get Trezor hidden wallet pass. I have wallet address, seed, and password ?

**Comment by 3rdIteration** [comment]
This isn't a support channel, free support happens in the YouTube comments section, or you can request paid private sessions here https://cryptoguide.tips/recovery-services-consultations/
