### ISSUE TITLE
seedreocvery on vastai

### ISSUE THREAD

**Issue by ramazanalii2023** [3rdIteration/btcrecover#431]
hi
i want to do seedreocvery on vastai and i need fast speed
what kind of config should i rent?
there are systems that have 256 cpu cores and  several gpu
does this increase my speed or not?
what is your suggestion?

**Comment by 3rdIteration** [comment]
This isn't a support channel

Also, read the manual
https://btcrecover.readthedocs.io/en/latest/Usage_Examples/2020-10-06_Multi-GPU_with_vastai/Example_Multi-GPU_with_vastai/
