### ISSUE TITLE
Blockchain.com wallet: improve verification

### ISSUE THREAD

**Issue by Banaanhangwagen** [3rdIteration/btcrecover#433]
Can the regex-verification of the `unencrypted_block` be updated so that we avoid false negatives ?
I had a wallet where the password was not found since the decrypted text started with "sharedKey".

There was a commit for avoiding false positives (see: https://github.com/3rdIteration/btcrecover/commit/60a0a122aceda586e3f295ef4b3eefa938b3a8a6), but now we need an update for the false negatives.

A dirty fix would be [replacing ](https://github.com/3rdIteration/btcrecover/blob/master/btcrecover/btcrpass.py#L2268)
`if re.search(b"\"guid\"|\"tx_notes\"|\"address_book|\"double", unencrypted_block):`

with 
`if re.search(b".", unencrypted_block):`

Hashcat fixed the same issue a couple of years ago by simply checking for ASCII characters in the block (see this: https://github.com/hashcat/hashcat/pull/2249)
What do you think?

**Comment by 3rdIteration** [comment]
That regex will produce a bunch of false positives... 

BTCRecover already checks for ASCII and puts those in the possible_passwords log file.

If you are suggesting that you have a wallet file that wasn't correctly detected, can you verify that it appeared in possible passwords and post the text from there in this issue?

**Comment by Banaanhangwagen** [comment]
The correct password is indeed mentioned in the log as a possible password. So far so good.

On the other hand, I find it _very_ confusing that the output of the script is telling me: 
`All possible passwords (as specified in your tokenlist or passwordlist) have been checked and none are correct for this wallet. You could consider trying again with a different password list or expanded tokenlist...`
I had no idea that a possible password could be found in the log...
It makes no sense to explicitly print this message, but in fact, the user has to look in the log to see if there is a _possible_ password found.

Maybe adding the word "sharedKey" to the regex then ?
And/or changing the output message ?

**Comment by 3rdIteration** [comment]
It should have spat out a message every time one landed in that log, but I
will update the final message to draw attention to it as well.

**Comment by 3rdIteration** [comment]
Added in https://github.com/3rdIteration/btcrecover/commit/bad9e0e2d6f88718f54fd40275422816a3e72f31
