### ISSUE TITLE
Get Master Private Key from Electrum v1 Mnemonic/Seed?

### ISSUE THREAD

**Issue by anarchymachines** [3rdIteration/btcrecover#436]
I have the correct 12 word seed, I just want to verify that the addresses it derives are the correct ones. The wallet in question is actually not an Electrum wallet, per se, but rather a tool that used to use the old Electrum seed system with a different wallet structure (sub-wallets at different paths).  Anyway, the software for that tool doesn't provide a way to view the master private key,  it only lets me see the mnemonic and its associated hex seed...so I was hoping I could use this software to calculate the master private key...but have been unsuccessful in figuring out exactly how to do it (if it is indeed possible).

Any help would be greatly appreciated...have been trying to figure this out for longer than I care to admit!

**Comment by 3rdIteration** [comment]
Just put in the seed and an address derived from the software, if BTCRecover finds the match then everything is following standards.

**Comment by anarchymachines** [comment]
Thanks for the response. The reason I wanted to verify the derivation is because when I initially recovered the wallet after not using it for about a year, the balance was slightly off from what I remembered. I did find some sent-to UTXOs that roughly added up to the missing amount, so I wanted to figure out the master private key so I could derive the keys myself and look for any parent keys with leading zeros that may have caused some keys to be incorrectly derived years ago before the leading zero bug had been addressed.

For instance, if I use a very old version of Electrum v1's  mnemonic.py and put in my mnemonic phrase, it returns a 31 character hex seed that is missing a zero. Newer releases show the correct 32 character seed. I can't be certain which version of Electrum's code was running in the tool when I first created the wallet (or which version of the tool, for that matter), so I figured I could just do it myself and go from there...but figuring out how to get the master private key from the mnemonic has proved to be more complicated than I had hoped.

**Comment by 3rdIteration** [comment]
It's going to be binary in that if there was a problem with master key derivation, you would see zero transactions and zero balance.

**Comment by anarchymachines** [comment]
Well, the way it works is there are multiple depths, basically separate sub-wallets derived from the same seed. m/0/0/0 is the first one (where the actual addresses are at m/0/0/0/0, m/0/0/0/1, m/0/0/0/2 etc), and its change addresses are at m/0/0/1, then the next sub-wallet is at m/0/1/0, with its change addresses at m/0/1/1, and so forth. If I understand the leading zero bug issue correctly, any key with a leading zero byte that other keys are derived from could cause those keys to be derived incorrectly. So, the affected keys could potentially have been deep in the wallet. And if for instance there was an update that corrected the bug while I had coins at one or two erroneously derived keys in one particular depth, I probably wouldn't even have noticed when they disappeared (due to bug fix) since their respective balances would have been insignificant (at the time).

If I could just figure out how to convert an old electrum mnemonic to a master private key, that would be enough I think for me to manually rule out the possibility of any missing funds. Or is it even possible to do that conversion? Maybe there is something about the format of those old electrum wallets that I don't understand?
