### ISSUE TITLE
Can't find seed for Polkadot wallet

### ISSUE THREAD

**Issue by pelguetat** [3rdIteration/btcrecover#440]
I have a Polkadot wallet with the last 3 words missing. I have got the main public address, the one starting with '1', but the recovery is not working. If I just input the 9 words, it says there are not enough words, and if I replace them with others, it cycles quickly through 287465 possibilities and says it can't be found. These are the arguments I'm passing:
python3.11 seedrecover.py --wallet-type polkadotsubstrate --addrs [address] --mnemonic [Seed_phrase] --mnemonic-length 12 --typos 3 --no-dupchecks --addr-limit 1.

**Comment by 3rdIteration** [comment]
This isn't a support channel. You need to generate a test wallet (that you share in the issue) and demonstrate that there is an actual reproducible bug...

Free support happens on my YouTube channel and paid support can be requested here https://cryptoguide.tips/recovery-services-consultations/
