### ISSUE TITLE
--seedlist argument slow

### ISSUE THREAD

**Issue by igotwigsonwigsonwigs** [3rdIteration/btcrecover#441]
Ok so please feel free to correct me on anything I may be misunderstanding.  I am descrambling a seed phrase on my m1 which is on it's last leg,, so I don'thave computer power amongst a few other things. I Also know that the total number of permutations is 479 million, however out of those only 29 million (roughly) are valid. so my logic says hey, let's use lostword to create a file with only valid seed phrases and then let's use the --seedlist textfile.txt so that I'm not even checking seed phrases that aren't valid. My problem/question is why is it so slow at reading and is there anything I can do to speed it up, I've even tested it on a paperspace gpu notebook and it's stilll looking like this,

python3 seedrecover.py --no-dupchecks --mnemonic-length 12 --language EN --dsw --wallet-type ethereum --addr-limit 1 --addrs 0x42E4A90932cd05AD87fa36CEfC50FE49350E30b4 --seedlist 10.txt --bip32-path "m/44'/60'/0'/0"

Starting seedrecover 1.13.0-CryptoGuide, btcrecover 1.13.0-Cryptoguide on Python 3.11.7 64-bit, 21-bit unicodes, 64-bit ints
Using the 'en' wordlist.
2024-01-18 09:09:00 : Phase 1/1: up to 12 mistakes, 12 of which can be an entirely different seed word.
Wallet Type: btcrseed.WalletEthereum
Notice: Loading File:  10.txt
Counting passwords ...
  29,900,000  ETA: 4 minutes and counting   Notice: Finished File:  10.txt
Done                                                                          
2024-01-18 09:09:31 : Using 8 worker threads
Notice: Loading File:  10.txt
20797677 of 29941959 [#####################################--------------------] 1:36:35, ETA:  0:41:49

why is is so slow? ANy ways to speed it up? tthanks in advance!

**Comment by 3rdIteration** [comment]
This isn't a support channel and you should just follow the usage example for descrambling....

**Comment by igotwigsonwigsonwigs** [comment]
I was asking in reference to the speed/time of --seedlist but geez ok

**Comment by 3rdIteration** [comment]
This is likely normal, as you aren't getting any speed boost due to it automatically skipping seeds where the checksum fails.

It's not a bug so you can ask any further questions in the YouTube comments.
