### ISSUE TITLE
Increased Typos limit. How to increase permitted number of missing words?

### ISSUE THREAD

**Issue by darasr** [3rdIteration/btcrecover#442]
I changed the mnemonic words, but everything else is the same. Please give some guidance on how I can allow for 5 missing words. I know it might take long, but I want to find it. When I ran the first command, it opens up python like it should and I input my bitcoin address instead of the public key, which i do not have. It works well, but errors out due to not enough permitted missing words.

genghiskhan@genghisk-MBP btcrecover-master % python3.11 seedrecover.py --mnemonic "search pottery tonight cable job bomb head" --typos 5

Starting seedrecover 1.13.0-CryptoGuide, btcrecover 1.13.0-Cryptoguide on Python 3.11.7 64-bit, 21-bit unicodes, 64-bit ints
btcrseed
* * * * * * * * * * * * * * * * * * * *
*          Security: Warning          *
* * * * * * * * * * * * * * * * * * * *

Most crypto wallet software and hardware wallets go to great lengths to protect your wallet password, seed phrase and private keys. BTCRecover isn't designed to offer this level of security, so it is possible that malware on your PC could gain access to this sensitive information while it is stored in memory in the use of this tool...

As a precaution, you should run this tool in a secure, offline environment and not simply use your normal, internet connected desktop environment... At the very least, you should disconnect your PC from the network and only reconnect it after moving your funds to a new seed... (Or if you run the tool on your internet conencted PC, move it to a new seed as soon as practical)

You can disable this message by running this tool with the --dsw argument

* * * * * * * * * * * * * * * * * * * *
*          Security: Warning          *
* * * * * * * * * * * * * * * * * * * *

Using the 'en' wordlist.
Assuming a 12 word mnemonic. (This can be overridden with --mnemonic-length)
Seed sentence was too short, inserting 5 words into each guess.
2024-01-22 16:21:04 : Phase 1/1: up to 5 mistakes, excluding entirely different seed words.
Not enough entirely different seed words permitted; skipping this phase.
2024-01-22 16:21:04 : Search Complete
 Seed not found, sorry...
genghiskhan@genghisk-MBP btcrecover-master %

**Comment by 3rdIteration** [comment]
There is no point, 5 missing words is a math problem, not a software problem...
