### ISSUE TITLE
Trying to recover Helium wallet getting Invalid checksum

### ISSUE THREAD

**Issue by azzarin** [3rdIteration/btcrecover#454]
Trying to get back two of my phrases. But with my address and the only address i know of i get the error.

Starting seedrecover 1.12.0-CryptoGuide, btcrecover 1.12.0-Cryptoguide on Python 3.10.11 64-bit, 21-bit unicodes, 64-bit ints
Invalid checksum

Using the example with the example wallet address it works just fine. 

Is there any way to update the Helium addresses ? 

Here is my promt with the test mnemonic.

 python3 seedrecover.py --wallet-type helium --addrs 5YCpNsTonr74NsPeWWWC3qfpNMQV4f2NayTx1otqZChy --mnemonic "arm hundred female steel describe tip physical weapon peace write advice" --dsw

This does not work, so i believe it has to do with the address.

**Comment by 3rdIteration** [comment]
This isn't a support channel, only for reporting bugs, so you can ask questions like this on either the YouTube comments section or in a private session. https://cryptoguide.tips/recovery-services-consultations/
