### ISSUE TITLE
Isn't `--seedlist` and `--tokenlist` supposed to do the same thing?

### ISSUE THREAD

**Issue by lasermind** [3rdIteration/btcrecover#455]
Hi folks!

I'm playing with btcrecover, read through the docs and try to wrap my head around the usage examples. Maybe it's just an issue with my understanding, or an issue with the docs ...

 **The task:** What is the best way to (theoretically) recover a scrambled 24-word BIP39 seed phrase for BTC? I came up with two possible variants to do this with btcrecover:

#### Using `--seedlist`
> python seedrecover.py **--seedlist the-24-seed-words.txt --mnemonic-length 24 --transform-wordswaps 12** --typos 0 --wallet-type bip39 --addr-limit 3 --addrs bc1qq4fwwkzarl7nqajuxw79p750dpmw5vtlunqjsy --language en --dsw --no-dupchecks --no-eta

<details>
<summary>the-24-seed-words.txt</summary>
<pre>
card winter cereal music toy wire void act obtain almost page sponsor depth security decline ostrich auction enrich oval toward mutual economy unique renew
</pre>
</details>

#### Using `--tokenlist`
> python seedrecover.py **--tokenlist the-24-seed-tokens.txt --mnemonic-length 24** --typos 0 --wallet-type BIP39 --addr-limit 3 --addrs bc1qq4fwwkzarl7nqajuxw79p750dpmw5vtlunqjsy --language en --dsw --no-dupchecks --no-eta

<details>
<summary>the-24-seed-tokens.txt</summary>
<pre>
card
winter
cereal
music
toy
wire
void
act
obtain
almost
page
sponsor
depth
security
decline
ostrich
auction
enrich
oval
toward
mutual
economy
unique
renew
</pre>
</details>

**Questions:** Are these two prompts doing the same thing? Are they even capable of recovering a scrambled 24-word seed phrase? Which one is more efficient? Do these prompts maybe work differently but eventually achieve the same result – or are they doing completely different tasks? Is it correct to assume `--transform-wordswaps 12` for a totally scrambled 24-word seed phrase?

<hr>

**Bonus:** Also when running these prompts, one can get a little bit confused about this output:

![phase11](https://github.com/3rdIteration/btcrecover/assets/126513496/2a61bf24-e1f0-4a31-aebe-0ffb78a2761d)

Why does it say, that "up to 24 words can be entirely different seed words"? I provided a list, that narrows it down to exactly 24 seed words in question. To me, this output seems, as if btcrecover assumes, that it has to test for more than these 24 provided words ("entirely different"). Is maybe just the phrasing of this output a little bit odd and misleading (and thus should be adjusted) or what is the logic behind it?

**Thanks for reading and thanks for your thoughts!**

**Comment by 3rdIteration** [comment]
No, seedlist is the equivalent of passwordlist.
