### ISSUE TITLE
I'm lost in recovering my wallet

### ISSUE THREAD

**Issue by liberatedmind9** [3rdIteration/btcrecover#456]
Hi there, I'm new to this and I tried to recover following the btcrecover instructions but I got stuck somewhere in step 4. I'm not even sure if this is how I can resolve my problem.

Just to share some details, I was logged on my meta mask app on my phone by biometrics and one day it asked for my password and I forgot it, so I reset using the phrase but it turned out that phrase belongs to a different wallet provider. So now, I don't know how I can get back to trying out passwords on my phone. I don't have the seed phrase written down because I thought that was the srp for the wallet that has crypto in it.

On my laptop, I can only see it in my dashboard but not connected to do any transactions. If someone could help me recover this please, I would really appreciate it. Thank you. I know a little bit of coding but new to the crypto wallet part. I have been transferring crypto to that address until I was ready to take some out and now I can't access it... Please help.

**Comment by 3rdIteration** [comment]
This isn't a support channel, you can request paid support here: https://cryptoguide.tips/recovery-services-consultations/ or free support on the YouTube comments section of the CryptoGuide YouTube channel.
