### ISSUE TITLE
Need add new Electrum2 not crypted wallet to extract strings and check finding pass results

### ISSUE THREAD

**Issue by Layder76** [3rdIteration/btcrecover#457]
problem at pass check - new Electrum not crypted wallets  have xprv string, beginned from "zprv", instead of "xprv", and btcrecover.py and hashcat can't found it. a btc recover need add check to zprv at module btcrpass.py

module  btcrpass.py need change:

            if xprv.startswith(b"xprv"):  # BIP32 extended private key version bytes

to

            if xprv.startswith(b"xprv") or xprv.startswith(b"zprv"):  # BIP32 extended private key version bytes

module extract-electrum2-partmpk.py need change:

    if wallet.get("seed_version") not in (11, 12, 13) and wallet_type != "imported":  # all 2.x versions as of Oct 2016

to

    if wallet.get("seed_version") > 33 and wallet_type != "imported":  # all 2.x, 3x versions as of Mar 2024

maybe and some new after 33

**Comment by 3rdIteration** [comment]
Fixed https://github.com/3rdIteration/btcrecover/commit/4d5a597d240a6f569ede15173c788bf9a40ad53c
