### ISSUE TITLE
OpenCL support for old blockchain.com wallet

### ISSUE THREAD

**Issue by Bushstar** [3rdIteration/btcrecover#458]
I have a very old blockchain.com wallet, one of those 7.1 entropy bits per byte ones. When trying OpenCL on this wallet I got the following error.

```
ERROR: The version of your blockchain.com wallet doesn't support OpenCL acceleration, this cannot changed. Please disable it and try again...
```

Is it possible to get OpenCL support for old blockchain.com wallet, the message suggest not?

Happy to donate to the project to get OpenCL support for old wallet added. Would also donate a bit more if i can ever got into it!

**Comment by 3rdIteration** [comment]
You have correct read the message. It means what it says, even if added opencl would not improve performance for that particular wallet file.

**Comment by Bushstar** [comment]
Thanks for the response. Will keep trying on my CPU. Not 100% confident my wallet is supported, it is a super tiny file, backup from 2012. Actually throws an entropy bytes error saying 7.1 is below the min of 7.1 which is odd. Changed the check to 7.0 to get it running. Might start a new issue as I wonder if I've got some ancient v0 wallet, swear I should have hit the password by now.

**Comment by 3rdIteration** [comment]
It's very likely just a v0 wallet (which is supported) with low entropy in the bytes, so changing the check to 7 is the right approach.

**Comment by Bushstar** [comment]
Thanks. I'll keep going. Checked and the file is 224 bytes if that seems familiar with other v0 wallets?

**Comment by 3rdIteration** [comment]
There is no bug here so ask any further questions in the YouTube comments section.
