### ISSUE TITLE
        if xprv.startswith(b"xprv"):  # BIP32 extended private key version bytes

### ISSUE THREAD

**Issue by arashjooooon** [3rdIteration/btcrecover#459]
if xprv.startswith(b"xprv"):  # BIP32 extended private key version bytes

**Comment by 3rdIteration** [comment]
If you have an xprv then you don't need BTCRecover. What are you attempting to do?

**Comment by 3rdIteration** [comment]
Looks like duplicate of https://github.com/3rdIteration/btcrecover/issues/457
