### ISSUE TITLE
btc rocket high and i am back to try my luck again for the 22k waiting for the second password .

### ISSUE THREAD

**Issue by umairnawaz786** [3rdIteration/btcrecover#460]
i try to download the wallet file i.e json but it wont and gives lots of errors.
and when i try on the old wallet file which i downloaded last year , the main password is shown wrong .
very confused . any help guys ?

**Comment by 3rdIteration** [comment]
If you want private support you can request it here: https://cryptoguide.tips/recovery-services-consultations/
