### ISSUE TITLE
Metamask Not Cracking 

### ISSUE THREAD

**Issue by sa976171** [3rdIteration/btcrecover#463]
Btcrecover is not recovering password. I tried with extract script also

**Comment by 3rdIteration** [comment]
I pushed an update a few weeks ago to fix compatabiliy with the newest wallet format. 

Have you tried with a test wallet on your system? (Obviously after making a backup of the wallet you are trying to recover)

**Comment by sa976171** [comment]
I tried with a demo wallet but it's not working

**Comment by 3rdIteration** [comment]
Can you share that demo wallet and the password here?
