### ISSUE TITLE
Decrypting a Multibit Style AES Wallet with Unexpected Content

### ISSUE THREAD

**Issue by anarchymachines** [3rdIteration/btcrecover#469]
I'm sure there is a better title but thats the best I can come up with right now.

Basically, I have an AES encrypted xprv from Bitgo that is basically in the same format as the Multibit HD wallet files. The only difference is the "ks" value is 256 instead of 128, and the "ct" value is significantly smaller (since it is just 1 encrypted xprv).

Unfortunately, when I try to decrypt/dump its contents (I have the correct password), instead of showing me the result, it says "Doesn't look random enough to be an encrypted Multibit HD wallet (only 5.7 bits of entropy per byte)"

I know this is a sort of hacky way to use btcrecover, but is there any way to get it to show the decrypted output anyway?

Or if there is an easier way to accomplish this please let me know. Thank you!

**Comment by 3rdIteration** [comment]
Shouldn't be an issue to mod it to support it, but this isn't a bug. If you want free support for this then you can ask in the YouTube comments, alternatively if you want private support to do the mod you can request it here https://cryptoguide.tips/recovery-services-consultations/
