### ISSUE TITLE
New option

### ISSUE THREAD

**Issue by roi35** [3rdIteration/btcrecover#47]
Hello, very thanks for u work!! can u add target list address (.txt) file? 1 address per line. And use random mode generation seed (mnemonic) all 12 words random, thanks. Very need This option from GPU. please please do it. so that you can add all addresses with balances, and randomly generate seeds to them...

**Comment by 3rdIteration** [comment]
What are you actually achieve? How many words in your seed do you have?

You can already run the tool against an AddressDB that will let you know if the tool finds the correct seed.

Simply attempting to brute-force random seeds until you find one with a balance is a complete waste of time, if you don't believe this, just start run the tool against an addressDB with 12 "big typos" for a 12 word seed.
