### ISSUE TITLE
Known order of words, possible random words

### ISSUE THREAD

**Issue by coolcash** [3rdIteration/btcrecover#470]
I have 8 words that I know, but I have a possible list of what the other 4 could be. Could I use a seed list to limit the tries of those 4 words. How would that be formatted if I can?

**Comment by 3rdIteration** [comment]
This isn't a support channel, only for reporting bugs. 

Free support happens in the YouTube comments section, alternatively you can request private support here https://cryptoguide.tips/recovery-services-consultations/
