### ISSUE TITLE
Blockchain.com V3 Wallet Formatting

### ISSUE THREAD

**Issue by glennlp** [3rdIteration/btcrecover#472]
Hello,
I extracted a v3 wallet from blockchain but was not sure how to format it for the wallet.aes.json. 

[wallet.aes.json](https://github.com/3rdIteration/btcrecover/files/15334223/wallet.aes.json)
It currently looks like this in the Chrome Developer Tools output.

I tried to paste in the payload value in the v4 format (as shown in the video) but have no confidence this is correct. Would appreciate any help!

**Comment by 3rdIteration** [comment]
Yea there is a bunch of extra crap on there that you need to remove, just look at the examples in the repository and it will make it pretty clear
