### ISSUE TITLE
use RTX 4090 as gpu acceleration but the gpu not performance 100%

### ISSUE THREAD

**Issue by maldiohead** [3rdIteration/btcrecover#473]
I recover the bitcoincore wallet password. with command :` python btcrecover.py --wallet wallet.dat --tokenlist tokens.txt --enable-gpu`
but I see the cpu perfromance isv very low, I can confirmed the gpu itself works well

**Comment by 3rdIteration** [comment]
You will see that the performance does increase when using it, but there are multiple reasons why it could be bottlenecking.

Basically this isn't a bug, but you had best review the documentation and also the video on multi GPU wallet recovery on my YouTube channel.
