### ISSUE TITLE
Feature Request: implement scanning a failed hard drive for crackable keys

### ISSUE THREAD

**Issue by RecRanger** [3rdIteration/btcrecover#474]
Pywallet and [crackBTCwallet](https://github.com/albertobsd/crackBTCwallet) both implement this feature. 

It would be awesome if this tool implemented it as well so that it was fully all-in-one.

It could support scanning for way more types of wallets.

**Comment by 3rdIteration** [comment]
I have no intention to add this, but feel free to bring a PR
