### ISSUE TITLE
can't decrypt trust wallet, even with the right password

### ISSUE THREAD

**Issue by yo-aiv1** [3rdIteration/btcrecover#475]
this might be off topic, but i guess this is the only place i can get answer.
what is the cryptography algorithm trust wallet uses to encrypt the mnemonic and the password used to encrypt it, also number of iterations for PBKDF and key length?
thanks

**Comment by yo-aiv1** [comment]
tested on trust wallet with wallet file and the right password and it couldnt decrypt it

**Comment by 3rdIteration** [comment]
BTCRecover doesn't currently support Trust Wallet. Support could be added if you want to sponsor it.

**Comment by 3rdIteration** [comment]
So do you have a PR for this functionality somewhere?
