### ISSUE TITLE
Blockchain.com v2 wallet Decrypted Block

### ISSUE THREAD

**Issue by b1654at** [3rdIteration/btcrecover#477]
Hi!

When I was recovering the password, a message appeared, what does it mean?

`**NOTICE** Possible (Unlikely) Match Found, recorded in possible_passwords.log`

Log file

`2024-06-01 Possible Password ==>This my password<== in Decrypted Block ==>{" /;L c.3q ] 8B<==`

What does that mean?

`==>{" /;L c.3q ] 8B<==`

**Comment by 3rdIteration** [comment]
It means what it says in the possible passwords.log file

Basically it decrypted to random crap so it's not the password. (And not related to it in any way)

**Comment by b1654at** [comment]
Does this mean there is a match in the password? The match is not the password itself, but words, letters or symbols?

**Comment by b1654at** [comment]
In possible_passwords.log there are 3 different passwords with the same words and characters, only the order is different. Does it mean that the password consists of these words? 

Example passwords:
Possible Password ==>btcsatoshiwallet<== in Decrypted Block ==>
Possible Password ==>walletSatoshiBTC<== in Decrypted Block ==>
Possible Password ==>walletsatoshiBitcoin<== in Decrypted Block ==>

**Comment by 3rdIteration** [comment]
Just read the file, it's all explained in the header there.

There is no bug here, ask further questions in the YouTube comments section.
