### ISSUE TITLE
Allow creation of Address Database from a file of addresses

### ISSUE THREAD

**Issue by B10wfish** [3rdIteration/btcrecover#48]
Hello!
I have my own list of addresses that I want to use as an AddressDB File. (Text sorted list of addresses or a list hash160s of them).
Can I fast somehow convert it into a * .db file, suitable for use with seedrecovery.py?
Maybe 'hash160_of_addresses.txt | xxd -r -p 'or something else?
Thanks

**Comment by 3rdIteration** [comment]
How many addresses are we at talking about here? Is this 5-10 or something like 100+?

As it stands, there is no provision for this beyond just adding multiple addresses in the UI, but it would be a trivial feature to add.

**Comment by B10wfish** [comment]
Of course, I meant a list of n-millions of addresses.
To not use your tool to create *.db file. (if already have addresses list)

**Comment by 3rdIteration** [comment]
No worries, millions won't be a problem but is certainly impractical with the existing UI.

It will be quite straight forward to do this with a small patch to the existing create-address-db list. 

It will just take a text file with one address per line and spit out a corresponding addressDB file at the end.

Will post any updates in this issue, so just keep an eye out over the next month unless someone else throws the code together and submits a PR.

If you are in a hurry, you might as well just use the entire AddressDB in the meantime, there isn't any performance penalty and I'm unlikely to give this any attention in the next week or two.

**Comment by hitendrapharmacy** [comment]
as i do have a addressdb file with many thousand addresses.....can you please find me a command to check passphrases for all at once with an decrypted(no passphrase) wallet?

**Comment by hitendrapharmacy** [comment]
i am saying, can i run python to crack all bitcoin addresses at same time with address.db? or not

**Comment by 3rdIteration** [comment]
Sure, you can give it a go, but you are wasting your time.

**Comment by hitendrapharmacy** [comment]
means can i scan all addresses for their passwords at the same time?

**Comment by hitendrapharmacy** [comment]
python is scanning only one wallet file right now.....i wanna scan all addresses for my passwords rather than one wallet.dat? possible?

**Comment by 3rdIteration** [comment]
Which wallet were you using to store your crypto and what have your lost? (Seed, BIP39 passphrase or wallet password?)

**Comment by hitendrapharmacy** [comment]
wallet password or passphrase

**Comment by 3rdIteration** [comment]
And which wallet were you using where you lost these?

**Comment by hitendrapharmacy** [comment]
all of them are bitcoin core wallet.dat

**Comment by 3rdIteration** [comment]
Recovering a wallet.dat file has nothing to do with an addressDB, trying to recover the password for a wallet file simply tries to decrypt the file itself, rather than checking for addresses/etc, as with BIP39 wallets. 

You can only test one Bitcoin core wallet at a time.

**Comment by hitendrapharmacy** [comment]
whats the best geforce that can scan most keys per second? like what system you knows....

**Comment by 3rdIteration** [comment]
2080ti will give you the best OpenCL performance, but it's expensive. The performance numbers on the GPU acceleration page reflect what I can get with a 1660ti.

If you have a bitcoin core wallet, your best bet is probably to generate a wallet extract and then use something like vast.ai to run it with a few 2080ti cards. (Though I think it will probably bottlekneck after a few cards, haven't really checked where the performance ceiling is for bitcoin core wallet files)

**Comment by hitendrapharmacy** [comment]
any idea how many passwords scanned per seconds?

**Comment by hitendrapharmacy** [comment]
u have telegram id?

**Comment by 3rdIteration** [comment]
Performance info is here https://github.com/3rdIteration/btcrecover/blob/master/docs/GPU_Acceleration.md

No telegram. If you are stuck, the options for a paid consultation are

**Comment by 3rdIteration** [comment]
Performance summary is here https://github.com/3rdIteration/btcrecover/blob/master/docs/GPU_Acceleration.md

No telegram, options for paid consultation are here https://cryptoguide.tips/recovery-services-consultations/

If your issue isn't related to creating an address DB from a list of addresses, as per the title of the issue, you should post your questions somewhere else.

**Comment by 3rdIteration** [comment]
Initial functionality added in https://github.com/3rdIteration/btcrecover/commit/99f716ce6bf19fb84980504d5ac75bc17fb5330e will add some updated documentation and more comprehensive testing later.
