### ISSUE TITLE
unable to install pip3 

### ISSUE THREAD

**Issue by jaymakos** [3rdIteration/btcrecover#485]
I'm trying to recover my bitcion with python the way you explained it here but its not working it keeps saying pip3' is not recognized as an internal or external command, operable program or batch file. pls what am i going to do?
![WhatsApp Image 2024-06-26 at 18 57 55_64163723](https://github.com/3rdIteration/btcrecover/assets/173969018/bace7213-ee94-4b20-9615-2957c717ec2e)

**Comment by jaymakos** [comment]
How can you help me out on this pls?

**Comment by 3rdIteration** [comment]
Just ask in the YouTube comments section and I will answer there.

If you want paid private support you can request it here: https://cryptoguide.tips/recovery-services-consultations/
