### ISSUE TITLE
Is it possible to specify positions for search words?

### ISSUE THREAD

**Issue by mloffer156** [3rdIteration/btcrecover#486]
Hi. I have a 12-word seed phrase and I know the first 6 words, but the last 6 words are lost. The standard phrase search is pointlessly long. Is it possible to specify that we are looking for the second half of the seed phrase, to avoid substituting the searched words into the first 6 places? And will this somehow speed up the process? Or is it still pointless?

**Comment by 3rdIteration** [comment]
Yes but recovery from 6 missing words isn't practical and will take millions of years. 

I'm sorry for your loss.
