### ISSUE TITLE
Decrypted block ==>{Fs" `%	>F5a<==

### ISSUE THREAD

**Issue by KTbusiness** [3rdIteration/btcrecover#487]
I used btcrecovery.py and found unseen block in possible log :(

**Comment by KTbusiness** [comment]
it's show

Decrypted Block ==>{Fs"�`%	>F5a<==

**Comment by KTbusiness** [comment]
![pslog](https://github.com/user-attachments/assets/e4cce39e-c12e-4977-9b77-68b128d6e3c6)

**Comment by KTbusiness** [comment]
![pslog](https://github.com/user-attachments/assets/918a00a5-6bc9-4f4f-ba05-0f6e08da4d13)

**Comment by KTbusiness** [comment]
![pslog](https://github.com/user-attachments/assets/20ddfd57-78e6-44f1-a347-ae0065259a01)

**Comment by 3rdIteration** [comment]
Just random garbage, doesn't mean anything
