### ISSUE TITLE
Lost 2 seed phrase 

### ISSUE THREAD

**Issue by Sharonyuken** [3rdIteration/btcrecover#488]
Want to recover

**Comment by 3rdIteration** [comment]
This isn't a support channel, only for reporting bugs. 

I have a bunch of videos on my YouTube channel https://www.youtube.com/channel/UCEviBQwLv-yfv3BErm0ojHg/ or if you want private support or trusted recovery, you can request it here: https://cryptoguide.tips/recovery-services-consultations/
