### ISSUE TITLE
Space inside `school%0,1[, ]something` raises error

### ISSUE THREAD

**Issue by willianantunes** [3rdIteration/btcrecover#494]
If the token file contains `school%0,1[, ]something`, the command `python btcrecover.py --listpass --tokenlist tokens.txt` raises the following error:

```txt
Starting btcrecover 1.13.0-Cryptoguide on Python 3.12.4 64-bit, 21-bit unicodes, 64-bit ints
Error: on line 1: invalid wildcard (%) syntax (use %% to escape a %)
```

If I change the space to a dot, let 'say `school%0,1[,.]something`, it works:

```txt
schoolsomething
school,something
school.something
3 password combinations
```

The token `%0,1[, ]schoolsomething` works though:

```txt
schoolsomething
,schoolsomething
 schoolsomething
3 password combinations
```

In the same sense, `^,^%0,2[, ]%[i]%sam%s` does not work, but `^,^%0,2[,.]%[i]%sam%s` does work.

**Comment by 3rdIteration** [comment]
Yea you will need to change the delimiter if you put a space in there.

**Comment by willianantunes** [comment]
For those who didn't understand like me, the answer is documented [here](https://btcrecover.readthedocs.io/en/latest/tokenlist_file/#delimiters-spaces-and-special-symbols-in-passwords).

Create a file with the content `school%0,1[, ]something` and then issue the command `python btcrecover.py --delimiter '*' --listpass --tokenlist password_list_file_generator/possible-tokens.txt`, then the output will be the following:

```
schoolsomething
school,something
school something
3 password combinations
```
