### ISSUE TITLE
Bug in BTCrecover when working with --rawprivatekey

### ISSUE THREAD

**Issue by SourceCodeGrim** [3rdIteration/btcrecover#495]
I followed your steps in this video (https://www.youtube.com/watch?v=SfW7Ir3xtNo) for BTC private key recovery, but unfortunately the program fell over when I ran this command:
![Uploading for Steve.jpeg…]()

btcrecover.py --rawprivatekey --addrs 1FYMZEHnszCHKTBdFZ2DLrUuk3dGwYKQxh --passwordlist "C:\RMCW\Tnd\Tndprivkey.txt" --typos-replace %B

(the error screen is attached as a jpg)

I'm running the latest version of BTCrecover which I downloaded from 3rditeration on Github.

Can you suggest how I can progress this please? I believe I'm doing everything right.

**Comment by 3rdIteration** [comment]
Whatever image you uploaded doesn't work, but I just tested it and it works fine.

Make sure you are running the latest code from the Github repo.
