### ISSUE TITLE
Questions about RAM in regards to recovery with an Address Database

### ISSUE THREAD

**Issue by gernotpokorny** [3rdIteration/btcrecover#501]
This is stated in the docs:

> You must use a computer with enough space for the full blockchain that you want to process and RAM equal to double the AddressDB size that you will end up with (This is an extremely generous estimate, you will likely be fine with less, but pretty much need to have at least as much as the AddressDB you want to create) .

> Note that running with an AddressDB will use about the same amount of RAM as the size of the AddressDB file while it is running with an address database.

I have two questions:

1) Currently the `address.db` size of Bitcoin is 17.2 GB. Can you still use `btcrecoverer` to create the `address.db` file from blockchain data and run `seedrecoverer.py` and will it work if you just have 8GB of RAM or 16GB of RAM and the  `address.db` size is 17.2 GB?

2) What if the `addressdb` size grows to a size greater then the amount of RAM which OSs do support, can you then still use `btcrecoverer` to create the `address.db` file from blockchain data and run `seedrecoverer.py` and will it work?

Thank you for your answers.

**Comment by 3rdIteration** [comment]
The addressdb needs to be smaller than your amount of ram. 

If it doesn't fit, then an addressdb that covers a smaller date range is the solution. (This is what happens with the premade files which target 8gb of ram as the minimum requirement)

**Comment by gernotpokorny** [comment]
Thanks, but the options to specify the range do not work, in particular the `--blocks-enddate BLOCKS_ENDDATE` option. It does not stop at the specified end date and address count is also no 0 after the specified end date. Doesn't matter if I specify `BLOCKS_ENDDATE` with or without quotes. For example `python3 ./seedrecover.py --blocks-enddate BLOCKS_ENDDATE 2013-01-01` does not work. Can you please explain how I can get this option working?

**Comment by gernotpokorny** [comment]
Thanks, is a sufficiently large swapfile also an option of you do not have enough RAM on the machine?

**Comment by 3rdIteration** [comment]
The performance will be terrible. Just limit the date range, it works fine.
