### ISSUE TITLE
https://github.com/3rdIteration/btcrecover/issues/499#issue-2471677697Never heard of it. Have you generated a test wallet to try?

### ISSUE THREAD

**Issue by Layaung230** [3rdIteration/btcrecover#509]
Never heard of it. Have you generated a test wallet to try?

_Originally posted by @3rdIteration in https://github.com/3rdIteration/btcrecover/issues/499#issuecomment-2305974472_

**Comment by 3rdIteration** [comment]
Duplicate of https://github.com/3rdIteration/btcrecover/issues/499#issuecomment-2305974472
