### ISSUE TITLE
Seed list ??

### ISSUE THREAD

**Issue by Coby23** [3rdIteration/btcrecover#51]
Looking for the best way to make a seed list to recover a passphrase with btcrecover.  Its a 12 word pass phrase where 3 words are known and there positions.  The issue is I have 24 words but only need 12 the passphrase was spilt into 2 for better security, not my greatest idea.  I know the 1st, 5th and 12th word 100%. 10 words from 1 group words are known but not the position, and 11 words are known but not the position from the second group.  I was thinking if there was a way to spilt these up so that bct recover only pulls 4 words from group 1 set of words and 5 words from group 2 words.  
This is what I tried 
Ex:
+ ^1^ 1 word
+ ^5^ 5 word
+ ^12^ 13 word
+  2 3 4 6 7 8 9 10 11
+ 2 3 4 6 7 8 9 10 11
+ 2 3 4 6 7 8 9 10 11
+ 2 3 4 6 7 8 9 10 11
+ 14 15 16 17 18 19 20 21 22 23 24
+ 14 15 16 17 18 19 20 21 22 23 24
+ 14 15 16 17 18 19 20 21 22 23 24
+ 14 15 16 17 18 19 20 21 22 23 24
+ 14 15 16 17 18 19 20 21 22 23 24
In the example the 1 through 24 are just place holders for the actual words.  

Is there a way to make btcrecover only pull one word from each line without duplicating a word.  I tried this example and was getting many duplicate words from each group.  
Example of seed phrase I was getting from the above seed list.
Ex: (1) 3 7 13 (5) 3 16 24 7 8 15 (13)  (words in parenthesis are known words in correct positions).

If the example seed list wood pull 1 word from each line without duplicating the word I believe it would reduce the total passphrases need to be checked and result in the possible recovery of this wallet.  I open to any ideas.

**Comment by Coby23** [comment]
I also tried this in place and btc recover just sat there and never ran
+ ^2 ^3 ^4 ^6 ^7 ^8 ^9 ^10 ^11

I understand that this is the way to right (or) on a line

**Comment by 3rdIteration** [comment]
The first thing to add would be to add a + to the words where you know they are there, having not only an anchor but also forcing it to use them at that position every time.

That said, as I understand your situation, it sounds like there are basically 10! * 11! possibilities to check. (10 factorial for the first group and 11 factorial for the second) so no matter how you construct the token file it will take decades. That said, if you can locate even a single extra word with known position, it starts to come down to something that could be solved within three years, with an extra words after that bringing it down to months.

The only silver lining for this is that computing power might increase by a factor of 10 or 20 over the next decade, or some work on the GPU accelerated branch (There is an issue open for this), might actually make this solvable within a more reasonable timeframe.
