### ISSUE TITLE
Pause & Resume

### ISSUE THREAD

**Issue by crypt0inf0** [3rdIteration/btcrecover#510]
Hi, As we all know recovering seed phrase takes lot of time if the seed length is 24.

Is there any way to log the current process state and resume later from where we left off to find the correct seed phrase. Instead of every time we have to start again from the beginning.

Thanks

**Comment by 3rdIteration** [comment]
It normally doesn't take a lot of time, what kind of recovery are you doing? Can't you just use the skip command?

**Comment by crypt0inf0** [comment]
I have 24 seed words in a incorrect order, I want to find the right order. How to use the skip command?

**Comment by 3rdIteration** [comment]
Unrecoverable. This isn't a support channel, so you can ask further questions in the YouTube comments section.
