### ISSUE TITLE
Forgotten of Metamask Secret Recovery Phrase

### ISSUE THREAD

**Issue by Lamarwalker** [3rdIteration/btcrecover#511]
can somebody help me to bring my lost wallet back please?

**Comment by Dappsnode** [comment]
@Lamarwalker  losing a wallet can be really stressful! The best thing to do is to contact the support team.I'll have to refer you to the official support live chat with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[Metamask Network DApps Support Ticket Requests.](https://thedappsupport.com/
)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by 3rdIteration** [comment]
Just ask on my YouTube channel of if you want a private session or trusted recovery, you can request it here: https://cryptoguide.tips/recovery-services-consultations/

Just to be clear, if you have lost all of the seed words and no longer have a working copy/backup of your wallet, then you have caused an unrecoverable loss.
