### ISSUE TITLE
Is an archive node required for ethereum-etl?

### ISSUE THREAD

**Issue by gernotpokorny** [3rdIteration/btcrecover#512]
Hello,

Do I need an archive node or a full node for [Generating Address Lists using Ethereum-ETL](https://btcrecover.readthedocs.io/en/latest/Creating_and_Using_AddressDB/#generating-address-lists-using-ethereum-etl)? You write that I probably need 10TB of space, I assume that means I need an archive node? 

If I just export the addresses of the last month (by specifying a start date and an end date), how much disk space would I need?

Thank you very much.

**Comment by 3rdIteration** [comment]
You will need the full blockchain data, so it will be a few TB. 

Your best bet is to just use Google Bigquery instead.

**Comment by gernotpokorny** [comment]
With full blockchain data you mean an archive node?

To export the result from Google Cloud you actually need a billing account and pay for it. I'd prefer not to setup such an account.

**Comment by 3rdIteration** [comment]
If your node doesn't have the data then it will query it from the network which will take a long time, so the more data you have locally the better.

**Comment by gernotpokorny** [comment]
Ok, thank you
