### ISSUE TITLE
Blockchain.com v5 wallet

### ISSUE THREAD

**Issue by danielneal** [3rdIteration/btcrecover#515]
It looks like blockchain.com  have updated their wallet format again. Running btcrecover with a known password fails with "Unable to decrypt wallet, likely due to incorrect password.." The password works for logging in but the BTC do not appear.

I think there is a bug either in their site - perhaps they had a workaround for old wallets that they accidentally removed, or they've done some kind of internal migration and bungled some data.

I'm hoping it's the former as I'm trying to help someone who's had BTC disappear from their wallet. 
Blockchain support have not been much help so far. 

I can't find any info on the v5 format anywhere (just when you access the site it ouputs "v5 wallet" in the console). 

What would you suggest on how to figure this out? Any ideas? 

Base64 decoding the wallet file (taken from the devtools) gives something that looks like random binary bytes, so I'm guessing needs decryption with the password - but by what method?

**Comment by 3rdIteration** [comment]
Does it show up in the possible passwords.log file?

**Comment by danielneal** [comment]
Nothing in possible passwords.log. 

This isn't useful for btcrecover, but there is some good news though - I was able to recover the wallet contents by using a workaround. 

I checked the blockchain UI source and found that (at least, today 2024-11-17) it checks local storage to decide whether to show the new v5 UI or not. 

https://github.com/blockchain/blockchain-wallet-v4-frontend/blob/8d04d1ea3edd902ff1182595ac669d746bf7c4bb/packages/blockchain-wallet-v4-frontend/src/scenes/app.tsx#L180

So if you go to local storage and add a key/value for  `opt_out_wallet_v5_ui`: true, you can get access to the v4 UI. 
This showed the correct balance, that was invisible in the v4 UI seemingly to issues with some addresses. 

I imagine they're probably working on a fix for this but if anyone else is panicking and support is not helping this might be worth a try.
