### ISSUE TITLE
Addressdb for solana wallet

### ISSUE THREAD

**Issue by cctdd** [3rdIteration/btcrecover#520]
How do i create an addressdb for solana wallet? I know it is a Bip32 wallet and most solana seed will generate an eth and btc address also, using this, can I use an eth address db and do a seedrecovery for the eth address instead? Or is there another way to do this?

**Comment by enolife** [comment]
> How do i create an addressdb for solana wallet? I know it is a Bip32 wallet and most solana seed will generate an eth and btc address also, using this, can I use an eth address db and do a seedrecovery for the eth address instead? Or is there another way to do this?

I can help if i know exactly what you want to accomplish

**Comment by cctdd** [comment]
Endgame is to have an addressdb for the solana wallets also.

**Comment by 3rdIteration** [comment]
> > How do i create an addressdb for solana wallet? I know it is a Bip32 wallet and most solana seed will generate an eth and btc address also, using this, can I use an eth address db and do a seedrecovery for the eth address instead? Or is there another way to do this?
> 
> I can help if i know exactly what you want to accomplish

It's quite straightforward, you just need to code it up in a few places to add the functionality to BTCRecover. (Similar to other coins where it is supported like BTC, Eth)

**Comment by cctdd** [comment]
What about the source of the addressdb itself. I guess thats what I can't figure out yet.

**Comment by 3rdIteration** [comment]
Same as everything else, either parsing the data directly from a full node or use something like Google BigQuery. (Though until it is actually implemented on the BTCRecover side, having the list of addresses won't help)

But yea, would be straightforward to code up and bring a PR, or if you are in a hurry could sponsor it either directly or via a trusted recovery.
