### ISSUE TITLE
can i find my bitcoin private key with this?

### ISSUE THREAD

**Issue by zhangdulin** [3rdIteration/btcrecover#522]
0x0776657273696F6E
0xB01E0400

minversion
0xAC970200

0x05666C616773
0x0400000006000000

0x046D6B657901000000
0x30A2AFA4FE6A326D38718BF82CD7AEDC998DBC2BE8D864BAF493A158605C6CF7D299D5EE24AB48F63D64E0E1675A1D0571083E6C4516F4F331EA00000000CA15050000

bestblock
0x8011010000

0x1262657374626C6F636B5F6E6F6D65726B6C65
0x801101001D01E448A0CC75B8E49D3E0BD988468AC51CB70E461DEC67FDC00E000000000000D9A8813F2292B3CA061BBAE470523FE92F6F3F914A44D85FB900000000000000223E2D33669F48C7601B1313A85303715589F838FFB5D598FD010000000000009B8C7F9972CC2C2321ED7FE3E08A478A8B1211FEF4C9834F790E0000000000005FCF7C153F9223CA4FA7F3FFEA529D39FC644EBF908D271A99030000000000007D2000DDB2E145CEE09206D120F0FED25BB65184BEAF3AED0F0C00000000000087B7BF307A2F638412833DFDC466987507C179990DBB4FA4040B000000000000E1325ACC30004AACDBDABCDD5F32D87EBE87AF33E767A97C4C0C000000000000148B2EF7DA3A4137569BEE2488F7C7EE7E5CB833F009FA59FE05000000000000567A87679D3B3DE61FAFCA6D35C0BCC03202CE1D4B3837666F02000000000000A3C4C8557DD4570771926708D2A5E735D8E16C18907B7E61F109000000000000F9B8B5E7A40860342A2E00E483FEB839E875FB00953589B61D05000000000000A5AFBA20DE09B5FD694D1C6B0DCD961C425B5DF717F0E06FCF0E000000000000302D54FB83995D314BCF9FD461EC6894CD1AB97BCB9096847C02000000000000D4FBAB20877EB9247F66EE5D928DE6F8B4D09CC91C45A174EF0700000000000070A0FC3E55DD05F304F9CE7980BFFD52647E6ADC2F01F5E34807000000000000F6E8286E59A6EE20E62F939AEA740DA2D79EBBED10257468530B0000000000000409E5CBD6762FC27FB13605E56D6AC156EE7E24BA10C17A0105000000000000AAB1598FE5CD18D2045179882746A0798DD729D69A1DAE887D05000000000000A9366F96562FC06AA7B399922D12DD632BD8714F2AAEED8E4D0400000000000053230BA1D749FDBAA9262F3D782B725AEF5F7EFCC48C53B99B09000000000000098F078A9AEDF509747CF922704FD34C98882B63148B93199004000000000000EE242D01EB245408887E6DE6EAEEA826FB882EA703F46206AD09000000000000568F5BA03F7DA4E264DFE0A17B10C03240326131ECFD22BEBE000000000000004F0F87B38C242C0B5CBB6D5AD0BB11304F2BBBCD82B9C95A2803000000000000139E35AA570357B6F541ADD1F77406187CEF4C76E85883956D380000000000008B9896BD08549C4BB25A4A0B55D9D07591E45E61BA98AE4DFBBD100000000000709728D845F09489E57492D140656E22BC4D87CB8A23B105EEB62962000000006FE28C0AB6F1B372C1A6A246AE63F74F931E8365E15A089C68D6190000000000

**Comment by 3rdIteration** [comment]
This isn't a support channel
