### ISSUE TITLE
ETH addressdb not working

### ISSUE THREAD

**Issue by Is-none-lab** [3rdIteration/btcrecover#526]
I don't know if I am doing something wrong, I am trying to recover a wallet using the eth addressdb. I am using the eth-addressdb on the 3rd iteration site (~4gg). I started by trying to recover a wallet whose phrase i know completely using the addressDb but it wasn't successful. I then used the --checkaddress to check if the address of this wallet i know is in the address db and it is in it. But it is unable to recover its phrase even when all the phrases are given or when 1 word is removed. Is there something i am doing wrong?

**Comment by 3rdIteration** [comment]
Has the wallet made any transactions? (If not it won't be in the AddressDB)

**Comment by Is-none-lab** [comment]
Thanks for the timely response!
I guess it was my assumption that if the address had a transaction in another chain then I would be able to recover it using the ethdb address too. But as you have pointed out, the address had no eth trans. I just tested with an address with eth transaction and it works. Thank you.
