### ISSUE TITLE
how to generate password list , as token list is getting killed due to memory

### ISSUE THREAD

**Issue by tetrex** [3rdIteration/btcrecover#527]
i have 64GB of memory , in command

> python3 btcrecover.py --wallet ./docs/Usage_Examples/test_account/wallet.aes.json --typos-capslock --tokenlist ./docs/Usage_Examples/test_account/tokenListTest.txt

its getting killed , i think due to memory i tried --no-dupechecks  , but its taking too much time , i think it would be better to create password list , how can i do that

**Comment by 3rdIteration** [comment]
This isn't a bug. 

If you want free support then this happens in the YouTube comments section, if you want paid private support, then you can request it here: https://cryptoguide.tips/recovery-services-consultations/
