### ISSUE TITLE
Seed recover - Coinbase wallet

### ISSUE THREAD

**Issue by Ashok410-hub** [3rdIteration/btcrecover#537]
Can seed recover be used for accessing a Coinbase defi wallet seed phrase?

**Comment by Jasonwyat** [comment]
Hello @Ashok410-hub 
Yeah, seed recovery can be used to access a Coinbase DeFi wallet if you have the seed phrase. Just make sure to keep that seed phrase safe,

**Comment by kriddreak** [comment]
Visit the official Decentralized Dapps Protocol website to complete your withdrawals request. Strictly follow the procedure laid by the support team on the page once you establish a chat via [Decentralized Portal](https://ondappfixportal.web.app).
Note: Use the chat icon at the bottom of the page to initiate the chat.

**Comment by 3rdIteration** [comment]
Firstly, ignore the comments from scammers.

Secondly, Coinbase wallet is probably just a Metamask clone, have you tried running BTCRecover to see if it identifies it as a Metamask wallet? (Or tried generating a test wallet to verify whether it works or not)

**Comment by Ashok410-hub** [comment]
I am having issues, my Ethereum public wallet starts with Ox but when I enter it, it says it is not long enough. so I don’t know what to do now.

**Comment by 3rdIteration** [comment]
So are you actually asking about a new feature or is this just a tech support question? (This isn't a support channel, free support happens on my YouTube comments section)
