### ISSUE TITLE
Check Wallet Balance/Public Address Using Payload and Password

### ISSUE THREAD

**Issue by anhladang** [3rdIteration/btcrecover#538]
I am a user of blockchain.com wallet. I would like to request guidance or a feature to check the wallet balance or retrieve the public address of my wallet if I have the following:
	•	The payload file
	•	The wallet password

The key point is that I do not intend to log in via the blockchain.com website. Instead, I am looking for an alternative way (via API, local tools, or other methods) to access this information securely.

Is there a way to achieve this with the current tools or APIs provided by blockchain.com? If not, could such a feature be considered for future development?

Thank you for your support!

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by 3rdIteration** [comment]
It's straightforward, but this isn't a support channel, so ask in the YouTube comments section
