### ISSUE TITLE
Can't generate passwords from $ token

### ISSUE THREAD

**Issue by z3r0d0n3** [3rdIteration/btcrecover#54]
Like the title says, i am unable to generate passwords with $

tokens file:
$
@
4

command:
python3 ../btcrecover.py --token tokens --listpass

output:
@
4
4@
@4

no $ present in combinations, 
how can i solve it?

**Comment by 3rdIteration** [comment]
$ is a special character in terms of how you can anchor certain words. (like ^ as well)

If you want to use $, then you need to use %S in the token file, so what you want for this example is:

%S
@
4

More info here: https://github.com/3rdIteration/btcrecover/blob/master/docs/tokenlist_file.md

**Comment by z3r0d0n3** [comment]
got it thank you, solved, my bad
