### ISSUE TITLE
Add support for TRX, BNB, DECRED, ADA and other coins with non-standard derivation or address formats

### ISSUE THREAD

**Issue by hansfzlorenzana** [3rdIteration/btcrecover#58]
I have tried the derivation paths of these coins
TRX - m/44'/195'/0'/0
BNB - m/44'/714'/0'/0
DECRED - m/44'/42'/0'/0

But it can't either find the address even with correct seeds or it gives an error on BNB and DECRED. TRX can be scanned but no results on the address.

**Comment by 3rdIteration** [comment]
These basically all use non-standard BIP39 seed derivation. (Same is true for things like ADA)

If you or someone else from the communities of these coins can implement their derivation and open a pull request, I am happy to merge it.

**Comment by zorenskye** [comment]
> These basically all use non-standard BIP39/44 seed derivation or custom address formats. (Same is true for things like ADA)
> 
> If you or someone else from the communities of these coins can implement their derivation and open a pull request, I am happy to merge it.

I have seen a tool that generates address like the Ian Coleman bip39 but it supports Tron, decred, algorand and some more coins. Sadly, I don't have enough knowledge to implement the JS to the seed recover tool. 

Here is the repo: https://github.com/Coinomi/bip39-coinomi

**Comment by 3rdIteration** [comment]
The ones that are implemented on other reference tools like the Coinomi one are certainly more likely to be implemented as it makes things easier to verify. In addition to this, coins where there are pre-existing libraries in python that can be used to convert addresses to HASH160 and to go from seed to addresses are likely to be far easier to implement.

If anyone from the communities of these coins is happy to create a pull-request that adds this functionality, then that is great. Alternatively, if someone needs one of these to be added for a specific recovery situation, they could directly sponsor it.

**Comment by kipilk0** [comment]
Better make Seed Recovery by Ethereum Address db

**Comment by 3rdIteration** [comment]
> Better make Seed Recovery by Ethereum Address db

This actually works right now and I have a pre-created addressDB available for download, just haven't gotten around to making a YouTube video about it. :)

**Comment by 3rdIteration** [comment]
@zorenskye if you are still looking to recover a wallet where you have one or more of these altcoins (along with an address to search for) I have a bit of time coming up over the Christmas/Newyear break, so can do an assisted recovery that would essentially function as sponsoring of one of these coins to be added in to BTCRecover.

**Comment by 3rdIteration** [comment]
ADA and TRX have been supported via sponsorship/

**Comment by 3rdIteration** [comment]
Closed as stale issue
