### ISSUE TITLE
password search exhausted

### ISSUE THREAD

**Issue by reindhartbilly** [3rdIteration/btcrecover#6]
Wallet difficulty: 25,000 SHA-512 iterations
Using 4 worker threads
64 of 64 [##########################################################] 0:00:03,
Password search exhausted

C:\btc2\btcrecover-master>btcrecover.py --wallet wallet_rec.dat --tokenlist tokens.txt

check with --tokenlist tokens.txt --listpass and my password is there

**Comment by 3rdIteration** [comment]
This looks like a Bitcoin Core wallet, what version of Bitcoin core are you using and what address format? (Just so that I can try to reproduce it)

**Comment by 3rdIteration** [comment]
Closed after 4 months of inactivity from original poster.
