### ISSUE TITLE
OPENCL_brute install error

### ISSUE THREAD

**Issue by kipilk0** [3rdIteration/btcrecover#60]
No module named 'Library'

Windows 10 
Python 3.8.6
pyopencl-2020.2.2+cl21-cp38-cp38-win_amd64.whl

> PS C:\btcrecover\opencl_brute> python -m pip install pyopencl-2020.2.2+cl21-cp38-cp38-win_amd64.whl
> Processing c:\btcrecover\opencl_brute\pyopencl-2020.2.2+cl21-cp38-cp38-win_amd64.whl
> Requirement already satisfied: pytools>=2017.6 in c:\users\samet\appdata\local\programs\python\python38\lib\site-packages (from pyopencl==2020.2.2+cl21) (2020.3.1)
> Requirement already satisfied: numpy in c:\users\samet\appdata\local\programs\python\python38\lib\site-packages (from pyopencl==2020.2.2+cl21) (1.19.2)
> Requirement already satisfied: appdirs>=1.4.0 in c:\users\samet\appdata\local\programs\python\python38\lib\site-packages (from pyopencl==2020.2.2+cl21) (1.4.4)
> Requirement already satisfied: decorator>=3.2.0 in c:\users\samet\appdata\local\programs\python\python38\lib\site-packages (from pyopencl==2020.2.2+cl21) (4.4.2)
> Requirement already satisfied: six>=1.8.0 in c:\users\samet\appdata\local\programs\python\python38\lib\site-packages (from pytools>=2017.6->pyopencl==2020.2.2+cl21) (1.15.0)
> Installing collected packages: pyopencl
>   Attempting uninstall: pyopencl
>     Found existing installation: pyopencl 2020.1+cl12
>     Uninstalling pyopencl-2020.1+cl12:
>       Successfully uninstalled pyopencl-2020.1+cl12
> Successfully installed pyopencl-2020.2.2+cl21
> PS C:\btcrecover\opencl_brute>  python -m pip install scrypt
> Requirement already satisfied: scrypt in c:\users\samet\appdata\local\programs\python\python38\lib\site-packages (0.8.15)
> PS C:\btcrecover\opencl_brute> pip3 install scrypt
> Requirement already satisfied: scrypt in c:\users\samet\appdata\local\programs\python\python38\lib\site-packages (0.8.15)
> PS C:\btcrecover\opencl_brute> pip3 install pyopencl-2020.2.2+cl21-cp38-cp38-win_amd64.whl
> Requirement already satisfied: pyopencl==2020.2.2+cl21 from file:///C:/btcrecover/opencl_brute/pyopencl-2020.2.2%2Bcl21-cp38-cp38-win_amd64.whl in c:\users\samet\appdata\local\programs\python\python38\lib\site-packages (2020.2.2+cl21)
> Requirement already satisfied: decorator>=3.2.0 in c:\users\samet\appdata\local\programs\python\python38\lib\site-packages (from pyopencl==2020.2.2+cl21) (4.4.2)
> Requirement already satisfied: numpy in c:\users\samet\appdata\local\programs\python\python38\lib\site-packages (from pyopencl==2020.2.2+cl21) (1.19.2)
> Requirement already satisfied: appdirs>=1.4.0 in c:\users\samet\appdata\local\programs\python\python38\lib\site-packages (from pyopencl==2020.2.2+cl21) (1.4.4)
> Requirement already satisfied: pytools>=2017.6 in c:\users\samet\appdata\local\programs\python\python38\lib\site-packages (from pyopencl==2020.2.2+cl21) (2020.3.1)
> Requirement already satisfied: six>=1.8.0 in c:\users\samet\appdata\local\programs\python\python38\lib\site-packages (from pytools>=2017.6->pyopencl==2020.2.2+cl21) (1.15.0)
> 
> 
> PS C:\btcrecover\opencl_brute> python test.py
> Traceback (most recent call last):
>   File "test.py", line 8, in <module>
>     from Library import opencl
> ModuleNotFoundError: No module named 'Library'

**Comment by 3rdIteration** [comment]
Fixed in https://github.com/3rdIteration/btcrecover/commit/7d5e33842a649c82a295a29b2c4da4d2dbfe102e

**Comment by kipilk0** [comment]
Still error


PS C:\btcrecover\opencl_brute> python test.py
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    from Library import opencl
ModuleNotFoundError: No module named 'Library'

**Comment by 3rdIteration** [comment]
Test.py isn't in that folder anymore, so you will need to download the update and then run the file test_opencl_brute.py from the main BTCRecover folder.

**Comment by kipilk0** [comment]
C:\btcrecover>python test_opencl_brute.py
Traceback (most recent call last):
  File "test_opencl_brute.py", line 8, in <module>
    from opencl_brute import opencl
  File "C:\btcrecover\opencl_brute\opencl.py", line 17, in <module>
    import pyopencl as cl
  File "C:\Users\samet\AppData\Local\Programs\Python\Python38\lib\site-packages\pyopencl\__init__.py", line 29, in <module>
    import pyopencl.cltypes  # noqa: F401
  File "C:\Users\samet\AppData\Local\Programs\Python\Python38\lib\site-packages\pyopencl\cltypes.py", line 22, in <module>
    from pyopencl.tools import get_or_register_dtype
  File "C:\Users\samet\AppData\Local\Programs\Python\Python38\lib\site-packages\pyopencl\tools.py", line 37, in <module>
    from pyopencl._cl import bitlog2  # noqa: F401
ImportError: DLL load failed while importing _cl:

**Comment by 3rdIteration** [comment]
Did you follow my YouTube guide on installing BTCRecover and specifically, PyOpenCL?
