### ISSUE TITLE
How to choose specific GPU device

### ISSUE THREAD

**Issue by dimitriib** [3rdIteration/btcrecover#65]
I wanna chose a specific GPU device for seed recovery. How to use `--opencl-devices` argument? 
I don't see any device IDs by `--opencl-info` response

============================================================
OpenCL Platforms and Devices
============================================================
Platform 0 - Name: Apple
Platform 0 - Vendor: Apple
Platform 0 - Version: OpenCL 1.2 (Jun  8 2020 17:36:15)
Platform 0 - Profile: FULL_PROFILE
 --------------------------------------------------------
 Device - Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 Device - Type: ALL | CPU
 Device - Max Clock Speed: 2600 Mhz
 Device - Compute Units: 12
 Device - Local Memory: 32 KB
 Device - Constant Memory: 64 KB
 Device - Global Memory: 16 GB
 Device - Max Buffer/Image Size: 4096 MB
 Device - Max Work Group Size: 1024

 --------------------------------------------------------
 Device - Name: Intel(R) UHD Graphics 630
 Device - Type: ALL | GPU
 Device - Max Clock Speed: 1150 Mhz
 Device - Compute Units: 24
 Device - Local Memory: 64 KB
 Device - Constant Memory: 64 KB
 Device - Global Memory: 2 GB
 Device - Max Buffer/Image Size: 384 MB
 Device - Max Work Group Size: 256

 --------------------------------------------------------
 Device - Name: AMD Radeon Pro 555X Compute Engine
 Device - Type: ALL | GPU
 Device - Max Clock Speed: 907 Mhz
 Device - Compute Units: 12
 Device - Local Memory: 32 KB
 Device - Constant Memory: 64 KB
 Device - Global Memory: 4 GB
 Device - Max Buffer/Image Size: 1024 MB
 Device - Max Work Group Size: 256

**Comment by 3rdIteration** [comment]
I just pushed an update that will now include the device ID in the --opencl output.

If you run the updated code, you should find that the 555X device is on index 2, so you would select it with the command --opencl-device 2

**Comment by 3rdIteration** [comment]
Should be fixed, no response after 14 days.
