### ISSUE TITLE
Checksum skip

### ISSUE THREAD

**Issue by hypeconomist** [3rdIteration/btcrecover#66]
Let's say I have a mnemonics split card, where the last word is also missed

for example:
coconut mule recycle XXXX timber oven minor amazing mother XXXX hawk victory XXXX XXXX XXXX

doesn't that mean that this card has lower entropy? Because the last word is a checksum and doesn't have to be guessed by the algorithm.

Instead of 4 words, I can guess only 3. 
With this, how can I do this with the current btcrecover version?

I mean as I understand the program checks checksums anyway, why not just generate if the last word is unknown?

**Comment by 3rdIteration** [comment]
Yes but not really in a significant enough way to make the card guessable in a workable amount of time for four missing words. BTCRecover already runs the checksum and only hashes (the slow part) those seeds with a valid checksum. Your best bet is to enter the words where you know the location and just type X (or some other non-BIP39 word) for the ones where the word for that location is unknown.

If you have four missing words with known location, your best bet would be to use the fully OpenCL+Vast.ai solution that John Cantrell wrote earlier this year. (You can find a link to it in the open issue relating to OpenCL acceleration)
