### ISSUE TITLE
download-blockchain-wallet.py still supported ?

### ISSUE THREAD

**Issue by sgpowers** [3rdIteration/btcrecover#67]
Hi,

I have mail and 2FA authentication on my wallet, but have misplaced the password.

So using download-blockchain-wallet.py is the solution to my problems, I hope.

However, I do not get the email when entering the wallet ID, email is correct.

Do I need to obtain a new API key, or could someone confirm this wallet access call is still valid in the API?

**Comment by 3rdIteration** [comment]
Hi

It has worked since I updated it in May and I just tested it and it works fine.

After you enter your wallet ID, it should say:

```
Authorization Required. Please check your email.
Waiting for authorization (press Ctrl-C to give up)...
```
