### ISSUE TITLE
BIP39 GPU acceleration Ethereum passphrase - Error Msg: WalletBIP39 does not support GPU acceleration

### ISSUE THREAD

**Issue by joestu** [3rdIteration/btcrecover#68]
Thanks for your valuable work and this library. I'm wondering if you could implement GPU acceleration for Ethereum passphrase? I'm somehow stuck with my local CPU, will the GPU increase be of any significance or just neglectable?

TIA

**Comment by 3rdIteration** [comment]
The OpenCL kernels that are currently in use for BIP39 seeds don't support being used for a BIP39 passphrase. The performance improvement would be ~10x at most, so it's worth just running it on your CPU.

**Comment by joestu** [comment]
@3rdIteration I found it! Pheweeee....obviously needed some more days to crack it in my local machine. Will tip you soon for the work.
