### ISSUE TITLE
How do I display found address and private_key in btcrseed

### ISSUE THREAD

**Issue by urbanurba** [3rdIteration/btcrecover#69]
How do I display found address and private_key in btcrseed?
Currently only the found mnemonics are displayed...
I tried through print(binascii.hexlify(d_privkey_bytes)) but a completely different pk(seed) is output.

**Comment by 3rdIteration** [comment]
BTCRecover doesn't currently do this, but it isn't hard to add. 

Do you actually need the address and private key or would something like the derivation path be sufficient? (As displaying the derivation path would make it more general in terms of supporting multiple cryptos)

**Comment by urbanurba** [comment]
I think both options will work. 
Thanks.

**Comment by 3rdIteration** [comment]
Added in https://github.com/3rdIteration/btcrecover/commit/f0a9f5dd326221ba40c306b0009f41f8580ad493
