### ISSUE TITLE
XRP seed recovery does not work

### ISSUE THREAD

**Issue by DavidVeksler** [3rdIteration/btcrecover#73]
Steps to reproduce: 
- Load any seed into https://iancoleman.io/bip39/
- Change coin to XRP 
- Copy first XRP address
- Run seedrecover.py with the seed and XRP address.

No match is found.  
The "Convert XRP addresses to standard Bitcoin Legacy Addresses" branch does run, but the Bitcoin address generated by the conversion is not in the list if you change the coin to BTC in the bip39 tool.

**Comment by 3rdIteration** [comment]
Can't replicate this failure, did you specify the derivation path for XRP? (eg: python seedrecover.py --bip32-path m/44'/144'/0'/0)

**Comment by DavidVeksler** [comment]
Success!  Thanks
