### ISSUE TITLE
Terminal Only Usage?

### ISSUE THREAD

**Issue by bonedaddy** [3rdIteration/btcrecover#74]
I'm attempting to use this on a server with no display, and it doesn't seem to be working. Even using the various `--X-prompt` CLI flags causes seedrecovery.py to fail to start as it can't detect a display. Is it possible to run seedrecovery.py in a command line only environment

**Comment by 3rdIteration** [comment]
Should work fine over CLI, what error are you getting?

**Comment by 3rdIteration** [comment]
Added some better messages to more gracefully handle TK not being present on the system in https://github.com/3rdIteration/btcrecover/commit/f7b2d150cb7aca5d3c7bfdfab8ce5ce968155383
