### ISSUE TITLE
using option '--mpk' in command line

### ISSUE THREAD

**Issue by AntonioRossi** [3rdIteration/btcrecover#75]
I did not found information on this in the documentation, but I guess that if I use '--mpk' with a master public key I can avoid of specifying these other options:
* --bit32-path
* --addrs
* --addr-limit

My use case is recovering a passphrase.
Am I correct?

**Comment by 3rdIteration** [comment]
It means that you can avoid --addrs and --addr-limit but you still need to specify the derivation path. The xpub does tell you the depth of a key derivation, it doesn't explicitly tell you the full derivation path. (Though you can make educated guesses) This causes issues in that different wallets sometimes represent the xpub in ambiguous ways (like Ledger Live) 

If you don't specify the derivation path, it will just search on the defaults for Bitcoin for the first account of each address type. (And it will detect and throw an error if the xpub you are using is from something other than the first account)

**Comment by AntonioRossi** [comment]
_?This causes issues in that different wallets sometimes represent the xpub in ambiguous ways (like Ledger Live)?_

Can you please elaborate a bit more your comment about ambiguity in some wallets?
Does it means that I should not trust the xpub given by ledger-live and use an addressdb instead?

**Comment by 3rdIteration** [comment]
Basically an xpub key doesn't have enough information in it to be entirely sure about what the full derivation path is, so the best you can do is make educated guesses in the software.

The xpub in Ledger Live is fine, you will just need to specify a derivation path if the xpub came from anything other than the first account in each account type. (And it BTCRecover will detect this and throw an error if it looks like the xpub is from something like the 2nd account)
