### ISSUE TITLE
Electrum1-en.txt word list different that what's published on the Electrum.org site

### ISSUE THREAD

**Issue by giantmonster** [3rdIteration/btcrecover#76]
Hi,
I was chatting on bitcointalk.org with some people that mentioned the Electrum word list. I found that Electrum pre 2015 uses a different word list than the Electrum-v1.txt list used here in btcrecover.
https://github.com/spesmilo/electrum/blob/1.9.8/lib/mnemonic.py is the pre-version v2 word list.
My selected words are in this mnemonic.py list however not in your electrum1-en.txt list. 
Can you check on this?
Thanks,
Dr.Mindset

**Comment by 3rdIteration** [comment]
I just had a look at the wordlist in mnemonic.py you linked is the same as you find in electrum1-en.txt in the repo... (in btcrecover\wordlists)

Is there some other list you are referring to somewhere that you haven't linked?

**Comment by giantmonster** [comment]
Must be my error. I'll take a closer look this evening. Perhaps it my issued command line then.

**Comment by giantmonster** [comment]
This was due to user error.
