### ISSUE TITLE
Btcrecover.py is not working bc (--listpass)

### ISSUE THREAD

**Issue by Dockload** [3rdIteration/btcrecover#78]
When I use this command `C:\Python27\python btcrecover.py --listpass` I get this filled error.
```
print()
	print("Starting", btcrpass.full_version(),
		  file=sys.stderr if any(a.startswith("--listp") for a in sys.argv[1:]) else sys.stdout)  # --listpass'
```
I am not sure how to fix it can anyone help, this is the only step that is holding me back.

**Comment by Dockload** [comment]
``C:\Python27\python btcrecover.py --listpass``

**Comment by Newbie62** [comment]
I've got the same issue.  How did you solve it?
