### ISSUE TITLE
Hive Wallet support

### ISSUE THREAD

**Issue by cruno91** [3rdIteration/btcrecover#79]
Hi,

The README.md mentions support for Hive wallets but I'm unsure of how to use it with the bitcoinkit.wallet file I have from Hive.

In addition to the bitcoinkit.wallet file, I also the know the BTC address and I have a 16-digit key, although I'm not sure if the key is actually for the Hive wallet.

**Comment by 3rdIteration** [comment]
Hive wallets are just old bitcoinj files, so if you needed to recover your password BTCRecover should recognize the wallet file if you load it, same as any other wallet type. (You could try testing it with BTCRecover)

BTCRecover doesn't currently dump the decrypted wallet file contents, but it wouldn't be hard and would actually be quite useful. (I just added a new issue for that feature here: https://github.com/3rdIteration/btcrecover/issues/80)

If you haven't tried to decrypt and export the seeds then you could just try this: https://github.com/JesseCorrington/bitcoinj-wallet-export

**Comment by 3rdIteration** [comment]
Closed due to inactivty.
