### ISSUE TITLE
Can't decrypt the wallet (wrong main password?),i know my first password

### ISSUE THREAD

**Issue by teefash** [3rdIteration/btcrecover#83]
tolas-MBP:~ teefash$ cd d
-bash: cd: d: No such file or directory
tolas-MBP:~ teefash$ cd Downloads
tolas-MBP:Downloads teefash$ cd btcrecover
-bash: cd: btcrecover: No such file or directory
tolas-MBP:Downloads teefash$ cd btcrecover
tolas-MBP:btcrecover teefash$ python ./extract-scripts/download-blockchain-wallet.py
  File "./extract-scripts/download-blockchain-wallet.py", line 48
    print("usage:", prog, "[NEW_BLOCKCHAIN_WALLET_FILE]", file=sys.stderr)
                                                              ^
SyntaxError: invalid syntax
tolas-MBP:btcrecover teefash$ python ./extract-scripts/download-blockchain-wallet.py
  File "./extract-scripts/download-blockchain-wallet.py", line 48
    print("usage:", prog, "[NEW_BLOCKCHAIN_WALLET_FILE]", file=sys.stderr)
                                                              ^
SyntaxError: invalid syntax
tolas-MBP:btcrecover teefash$ pip3 install -r requirements.txt
Collecting coincurve~=13.0.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/69/94/f2b44a793d2796810f498edd56b5e59b3b750ca86f8c1c8ca2463326eae2/coincurve-13.0.0-cp37-cp37m-macosx_10_9_x86_64.whl (374kB)
    100% |████████████████████████████████| 378kB 42kB/s 
Collecting green~=3.2.5 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/b8/17/3007239a0fb85f8c1e43a1801fa73b5f83ac257fdf3280d2bebb7639e475/green-3.2.5.tar.gz (72kB)
    100% |████████████████████████████████| 81kB 10kB/s 
Collecting protobuf~=3.14.0 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/fd/38/dc1b4ec33d3ebd540f2410c14743d3dc24f9df6556fde8c13983a9ba2a0a/protobuf-3.14.0-cp37-cp37m-macosx_10_9_x86_64.whl (1.0MB)
    100% |████████████████████████████████| 1.0MB 50kB/s 
Collecting pycryptodome~=3.9.9 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/be/ef/484a33589a7b8bfbeb02d3eb28308217087e3de768520e0a8af5631cea1c/pycryptodome-3.9.9-cp37-cp37m-macosx_10_6_intel.whl (14.1MB)
    100% |████████████████████████████████| 14.1MB 97kB/s 
Collecting asn1crypto (from coincurve~=13.0.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/b5/a8/56be92dcd4a5bf1998705a9b4028249fe7c9a035b955fe93b6a3e5b829f8/asn1crypto-1.4.0-py2.py3-none-any.whl (104kB)
    100% |████████████████████████████████| 112kB 138kB/s 
Collecting cffi>=1.3.0 (from coincurve~=13.0.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/c9/b3/39687d321725baf7f831c5868b6ba44922f5693947bf0e8a0110cffd7fb4/cffi-1.14.4-cp37-cp37m-macosx_10_9_x86_64.whl (176kB)
    100% |████████████████████████████████| 184kB 40kB/s 
Collecting colorama (from green~=3.2.5->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Collecting coverage (from green~=3.2.5->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/29/7c/890e84955a056af4296aa774624fdafbad5cb4b6eeabeeca9cd9f0b3494d/coverage-5.3.1-cp37-cp37m-macosx_10_9_x86_64.whl (208kB)
    100% |████████████████████████████████| 215kB 313kB/s 
Collecting unidecode (from green~=3.2.5->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/74/65/91eab655041e9e92f948cb7302e54962035762ce7b518272ed9d6b269e93/Unidecode-1.1.2-py2.py3-none-any.whl (239kB)
    100% |████████████████████████████████| 245kB 38kB/s 
Collecting lxml (from green~=3.2.5->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/94/59/f44a83ea47c42af27e3afef9ee2a0a1a38f466d507dc568400537926b185/lxml-4.6.2-cp37-cp37m-macosx_10_9_x86_64.whl (4.5MB)
    100% |████████████████████████████████| 4.5MB 27kB/s 
Collecting six>=1.9 (from protobuf~=3.14.0->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.3.0->coincurve~=13.0.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)
    100% |████████████████████████████████| 112kB 235kB/s 
Installing collected packages: asn1crypto, pycparser, cffi, coincurve, colorama, coverage, unidecode, lxml, green, six, protobuf, pycryptodome
  Running setup.py install for green ... done
Successfully installed asn1crypto-1.4.0 cffi-1.14.4 coincurve-13.0.0 colorama-0.4.4 coverage-5.3.1 green-3.2.5 lxml-4.6.2 protobuf-3.14.0 pycparser-2.20 pycryptodome-3.9.9 six-1.15.0 unidecode-1.1.2
You are using pip version 19.0.3, however version 20.3.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
tolas-MBP:btcrecover teefash$ python run-all-tests.py -vv

************************************ Python Version Error ******************************************

Sorry, BTCRecover no longer supports Python2 as it is officially End-of-Life...

Some features of this tool also require Python 3.6 or above to work....

You will need either to upgrade to at least Python 3.6 or download the final Python2 release.

Note: Python2 versions of this tool are now unsupported and will not receive improvements or fixes

Python2 releases and documentation for installing and using this tool with Python3 can be found at from https://github.com/3rdIteration/btcrecover.

************************************ Python Version Error ******************************************

tolas-MBP:btcrecover teefash$ 
tolas-MBP:btcrecover teefash$ 
tolas-MBP:btcrecover teefash$ sudo apt install python3-tk
Password:
Sorry, try again.
Password:
No Java runtime present, requesting install.
tolas-MBP:btcrecover teefash$ sudo apt install python3-tk
Password:
No Java runtime present, requesting install.
tolas-MBP:btcrecover teefash$ sudo apt install python3-tk

No Java runtime present, requesting install.
tolas-MBP:btcrecover teefash$ 
tolas-MBP:btcrecover teefash$ sudo apt install python3-tk
Password:
Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home/bin/apt" (-1)
tolas-MBP:btcrecover teefash$ sudo apt install python3-tk
Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home/bin/apt" (-1)
tolas-MBP:btcrecover teefash$ python run-all-tests.py -vv

************************************ Python Version Error ******************************************

Sorry, BTCRecover no longer supports Python2 as it is officially End-of-Life...

Some features of this tool also require Python 3.6 or above to work....

You will need either to upgrade to at least Python 3.6 or download the final Python2 release.

Note: Python2 versions of this tool are now unsupported and will not receive improvements or fixes

Python2 releases and documentation for installing and using this tool with Python3 can be found at from https://github.com/3rdIteration/btcrecover.

************************************ Python Version Error ******************************************

tolas-MBP:btcrecover teefash$ $ python3
-bash: $: command not found
tolas-MBP:btcrecover teefash$ $ brew install python3
-bash: $: command not found
tolas-MBP:btcrecover teefash$ python ./extract-scripts/download-blockchain-wallet.py
  File "./extract-scripts/download-blockchain-wallet.py", line 48
    print("usage:", prog, "[NEW_BLOCKCHAIN_WALLET_FILE]", file=sys.stderr)
                                                              ^
SyntaxError: invalid syntax
tolas-MBP:btcrecover teefash$ python./extract-scripts/download-blockchain-wallet.py
-bash: python./extract-scripts/download-blockchain-wallet.py: No such file or directory
tolas-MBP:btcrecover teefash$ python ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
  File "./extract-scripts/extract-blockchain-second-hash.py", line 86
    print("usage:", prog, "BLOCKCHAIN_WALLET_FILE", file=sys.stderr)
                                                        ^
SyntaxError: invalid syntax
tolas-MBP:btcrecover teefash$ python ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.jsonpython ./extract-scripts/download-blockchain-
  File "./extract-scripts/extract-blockchain-second-hash.py", line 86
    print("usage:", prog, "BLOCKCHAIN_WALLET_FILE", file=sys.stderr)
                                                        ^
SyntaxError: invalid syntax
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/download-blockchain-wallet.py
Please enter your wallet's ID (e.g. 9bb4c672-563e-4806-9012-a3e8f86a0eca)
> *******************
Authorization Required. Please check your email.
Waiting for authorization (press Ctrl-C to give up)...

Wallet file saved as wallet.aes.json

Press Enter to exit ...
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Can't decrypt the wallet (wrong main password?)
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Can't decrypt the wallet (wrong main password?)
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Can't decrypt the wallet (wrong main password?)
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Can't decrypt the wallet (wrong main password?)
tolas-MBP:btcrecover teefash$ python3./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
-bash: python3./extract-scripts/extract-blockchain-second-hash.py: No such file or directory
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Can't decrypt the wallet (wrong main password?)
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Can't decrypt the wallet (wrong main password?)
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Can't decrypt the wallet (wrong main password?)
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Can't decrypt the wallet (wrong main password?)
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Can't decrypt the wallet (wrong main password?)
tolas-MBP:btcrecover teefash$ python3 extract-blockchain-main-data.py wallet.aes.json
/Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'extract-blockchain-main-data.py': [Errno 2] No such file or directory
tolas-MBP:btcrecover teefash$ \python27\python extract-blockchain-second-hash.py wallet.aes.json
-bash: python27python: command not found
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Encrypted Blockchain files must be decrypted to extract the second password hash
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Can't decrypt the wallet (wrong main password?)
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Can't decrypt the wallet (wrong main password?)
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Can't decrypt the wallet (wrong main password?)
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Can't decrypt the wallet (wrong main password?)
tolas-MBP:btcrecover teefash$ python ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
  File "./extract-scripts/extract-blockchain-second-hash.py", line 86
    print("usage:", prog, "BLOCKCHAIN_WALLET_FILE", file=sys.stderr)
                                                        ^
SyntaxError: invalid syntax
tolas-MBP:btcrecover teefash$ python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Can't decrypt the wallet (wrong main password?)
tolas-MBP:btcrecover teefash$ 
tolas-MBP:btcrecover teefash$  python3 ./extract-scripts/extract-blockchain-second-hash.py ./btcrecover/test/test-wallets/blockchain-v2.0-wallet.aes.json
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Can't decrypt the wallet (wrong main password?)
tolas-MBP:btcrecover teefash$

**Comment by teefash** [comment]
i logged in to download the file

**Comment by 3rdIteration** [comment]
I have seen a few instances of this but have never been able to replicate it with either new or archived wallet files on any platform.

There may be an undocumented wallet file version floating around doing something exotic in terms of how the file is structured, so can you send me a copy of the wallet.aes.json and the main password? (Don't post it here, just email it to steve@cryptoguide.tips)

**Comment by teefash** [comment]
hello steve, i just emailed it to you . thanks

**Comment by 3rdIteration** [comment]
Can’t replicate your issue. Just tried it on both Windows 10 and Ubuntu 20.04, works fine. (Running python 3.8.6 and 3.8.5 respectively)
