### ISSUE TITLE
Error: unrecognized wallet format

### ISSUE THREAD

**Issue by vitlib** [3rdIteration/btcrecover#85]
Hi, I'm trying to recover the password of what I'm pretty sure is the backup of an old ethereum keystore with some eth in it.
So, the file has extension aes.json and schema:
iv 24 characters
v 1
iter 1000
ks 128
ts 64
mode ccm
adata ""
cypher aes
salt 12 characters
ct 2032 characters

I tried vanilla bitrecover, I guess I should add some options in order to guess the correct structure of the file but I can't figure out which ones.

**Comment by 3rdIteration** [comment]
Ethereum UTC (keystore) files are not currently supported, only recovery for seed based wallets. (The issue to add UTC file support is here: https://github.com/3rdIteration/btcrecover/issues/35)

**Comment by vitlib** [comment]
Thanks, I discovered your repo from this issue https://github.com/gurnec/btcrecover/issues/380 and thought it applied to my case.
I was wondering, is it possible that my JSON is a seed based wallet and not a keystore?
I can't find out how I produced the file, importing in MEW/Metamask failed...
If I recall correctly it was an export made from mist in 2017.
Any help is appreciated!
