### ISSUE TITLE
Explore Coinomi mobile wallet password recovery

### ISSUE THREAD

**Issue by 3rdIteration** [3rdIteration/btcrecover#9]
For the situation where the user can extract the app data from the phone.

**Comment by SknerusMcK** [comment]
@3rdIteration you solved it.

**Comment by 3rdIteration** [comment]
Never heard from those who had the issue as to whether they could get the data out of the wallet as a file that can be tested or used... (This would required the Devs to implement it if the phone isn't rooted)

**Comment by 3rdIteration** [comment]
Added in https://github.com/3rdIteration/btcrecover/commit/354cba6d7fa26de81ac7336b19e44eb2680b39d0
