### ISSUE TITLE
Cardano Yoroi IOS Wallet

### ISSUE THREAD

**Issue by Luftloch80** [3rdIteration/btcrecover#90]
Hey. 
any chance to Support spending Password recovery or Master password recovery for yoroi ios wallet. 
on a jailbroken iOS device you have access to the Files?
would spent 1000Ada
Thx

**Comment by 3rdIteration** [comment]
BTCRecover doesn't support ada or that wallet on your phone at the time. You could opt to sponsor the development with an assisted recovery. (So i world need some example wallet files, the actual one and would collect the usual fee of 10% of recovered funds) 

The 1000 ADA would cover the functionality, regardless of whether your particular recovery is successful.

**Comment by Luftloch80** [comment]
Okay. I Can sent you ZIP archive of files On my phone. 
do you have Telegram?

**Comment by 3rdIteration** [comment]
Just email it to steve@cryptoguide.tips

**Comment by 3rdIteration** [comment]
Looks do-able, the specifications for encryption/decryption of the master passwords is also quite well documented, (https://github.com/Emurgo/EmIPs/blob/master/specs/emip-003.md and https://github.com/Emurgo/emip3js)

**Comment by 3rdIteration** [comment]
Progress:
Implemented EMIP-003 in Python https://github.com/3rdIteration/emip3-python

Next step is to include in BTCRecover, add tests and push the update.

**Comment by 3rdIteration** [comment]
Added in https://github.com/3rdIteration/btcrecover/commit/4031ed8c25b34fd8ededd3614f679e9105b72b15
