### ISSUE TITLE
When does GPU acceleration take place with BIP-39 12 word seed recovery?

### ISSUE THREAD

**Issue by olso** [3rdIteration/btcrecover#91]
AMD GPU is not getting used at all

<img width="1080" alt="Screenshot 2021-01-08 at 14 52 24" src="https://user-images.githubusercontent.com/7975158/104022969-4a2e0500-51c1-11eb-81ae-1ca53c4ac1fc.png">

**Comment by 3rdIteration** [comment]
Have you tried checking it's usage with something like MSI afterburner

**Comment by olso** [comment]
@3rdIteration yes, msi afterburner, amd control panel, all show minimum activity ~1%

**Comment by 3rdIteration** [comment]
I just checked and even with Bitcoin core acceleration, the GPU usage reporting isn't reliable. 

If you run something like 
`python3 btcrecover.py --wallet ./btcrecover/test/test-wallets/bitcoincore-wallet.dat --performance --enable-gpu --global-ws 4096 --local-ws 256 `

You will see the performance difference, as well as massive power draw on your GPU, coupled with low CPU usage. (Compared to if you delete everything after the word --performance
