### ISSUE TITLE
Too much combinations

### ISSUE THREAD

**Issue by fablee1** [3rdIteration/btcrecover#93]
Hi!

i run seedrecover with the following command python seedrecover.py --no-dupchecks --mnemonic-length 12 --language EN --dsw --wallet-type BIP39 --addr-limit 1 --addrs bc1q(not pasting address) --tokenlist comb.txt --bip32-path "m/84'/0'/0'/0" --no-eta --enable-opencl

I use a tokenlist with 12 positional anchors and ran a test, using basic multiplication there are 3million combinations, but it runs well over 10 million, i just stopped it. why having positional anchors for all 12 words and i counted all possible combinations it gets going over it? Maybe it has to do something with the bc1 addresses or the path? 

With ETA its still counting way over 100 million when should be only 3

How the tokenlist looks like: https://imgur.com/5ciEZQN

**Comment by fablee1** [comment]
Just ran a test, if i give 1 word per position it calculates correctly 1 combination and finds
Then i changed for some positions amount of words: 5pos - 2 words, 6pos - 4 words, 7pos - 2 words, 8pos - 4 words. With this total combinations should be 64, but when running ETA showed 182 combinations, i just dont get whats wrong

**Comment by 3rdIteration** [comment]
This is user error, you also need to use "required" achors, see here: https://github.com/3rdIteration/btcrecover/blob/master/docs/Usage_Examples/2020-05-23_multi_device_descrambling_12_word_seed_with_extras/Example.md

**Comment by fablee1** [comment]
Used + along with ^1^ 
+ ^2^
and etc for every line still 16 combinations turn in to 38 as eta calculates i dont get it

**Comment by fablee1** [comment]
+ ^1^diamond
+ ^2^month
+ ^3^spread
+ ^4^narrow
+ ^5^fetch
+ ^6^gauge apple fetch narrow
+ ^7^apple
+ ^8^lunch
+ ^9^write
+ ^10^unaware
+ ^11^stamp unaware
+ ^12^hole write

seedrecover for this token file checks 38 combinations where does it get 22 more?

**Comment by 3rdIteration** [comment]
Positional anchors also need to apply to each item on a row, so words like Apple, Fetch and narrow don't have any positional anchor applied.

**Comment by nicoschtein** [comment]
```
^6^gauge ^6^apple ^6^fetch ^6^narrow
```

Change the line to the above. 
If you need more help let me know

**Comment by fablee1** [comment]
Oh, cool thank you very much guys! 

Btw another problem: does the worker option work with gpu?
I made --worker 1/100
and gpu is at zero, aswell as the overall speed went down to 1KP/s

**Comment by nicoschtein** [comment]
Not sure what the setup is, assuming you have 100 workers (you would do this if you have 100 instances of this same script running, normally on different computers) the total amount of possible guesses might be too low.

**Comment by fablee1** [comment]
Basically I have about 200 billion combinations
I want to divide that to 100 pieces, so I would not run the script 24/7 but only when I can.
For example today I will do 1/100, tomorrow 2/100, 3/100 and etc. 
without the worker option with gpu I get about 90-100 KP/s
And with worker 1/100 I get 1 KP/s
Why did the speed fall 100x times? I just told to process every 100th combination, so the speed should remain the same.

**Comment by 3rdIteration** [comment]
If you are doing a BIP39 seed recovery, even with the worker thread it still needs to generate all of the possible seeds, it just doesn't hash them. (And since the bottlekneck with BIP39 seeds is basically on seed generation, you will lose a massive amount of performance by using 1/100 workers.)

200 billion isn't too bad, depending on your security requirements you might be better renting some server time on a service like vast.ai and just letting it run for a month. (Most of these servers, even the lower end ones, should be able to easily achieve ~12 billion per day)
