### ISSUE TITLE
Add function seedlist + passphraselist in seedrecover

### ISSUE THREAD

**Issue by urbanurba** [3rdIteration/btcrecover#94]
Add function seedlist + passphraselist in seedrecover

**Comment by 3rdIteration** [comment]
So you would be happy to simply use lists for both? Not tokenlists of any kind? 

Are you likely to be testing more than 1000 seeds? (In terms of whether GPU acceleration is worthwhile)

**Comment by urbanurba** [comment]
Yes, you got it right, I would like to use my own lists, without tokenists, and more than a thousand seeds.

**Comment by 3rdIteration** [comment]
Just to manage expectations, this will be **extremely** slow. Basically it will run a checksum on the seeds, only checking either 1/16 (for 12 word seeds) or 1/256 (for 24 word seeds) and then do the full hashing on every passphrase. (Which will happen at about 1000 passphrases per second)

So basically if you have 1000 possible passphrases, it will check about 1 possible seed per second. (Which could translate to either 16 or 256 candidate seeds effectively checked, based on the seed length)

**Comment by urbanurba** [comment]
Can I choose multiple GPUs for parallel computing?

**Comment by 3rdIteration** [comment]
Sure, this might get you a 10x speed increase if you have a large number of both seeds and passphrases, but will still be very slow. (And might actually be slower depending on whether you have enough candidate seeds to get maximum parallelism)

**Comment by 3rdIteration** [comment]
Added https://github.com/3rdIteration/btcrecover/commit/5489fc3304cf7c3e39bfc9cd7fde6c666bbbdc2f
